canyongbs/advisingapp

app/Filament/Resources/UserResource.php, app/Filament/Resources/UserResource/Pages/CreateUser.php, app/Filament/Resources/UserResource/Pages/EditUser.php, app/Filament/Resources/UserResource/Pages/ListUsers.php, app/Providers/Filament/AdminPanelProvider.php, composer.json, composer.lock, config/app.php, config/filament.php, php-cs-fixer.php
Filament's initial installation and setup with a base resource setup for `User`. Installed so we can continue work on generating resources for Models, though we first need to determine Domain/Module structuring.
=> [Feature] Filament Installation

app-modules/case/src/Policies/CaseItemPolicy.php, app-modules/case/tests/CaseItem/CreateCaseItemTest.php, app-modules/case/tests/CaseItem/EditCaseItemTest.php, app-modules/case/tests/CaseItem/ListCaseItemTest.php, app-modules/case/tests/CaseItem/ViewCaseItemTest.php, app/Models/User.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/113/
Adds RBCA to Case Module and sets up testing to ensure proper gating
=> [Feature] Case Module RBAC

app-modules/case/database/seeders/CaseUpdateSeeder.php, database/seeders/DatabaseSeeder.php, database/seeders/DemoDatabaseSeeder.php
Sets up repo to allow better demo set up with Redshift and seeding.
=> [Feature] Redshift Testing

app-modules/assist-data-model/composer.json, app-modules/assist-data-model/composer.lock, app-modules/assist-data-model/src/Filament/Resources/StudentResource.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/RelationManagers/SubscriptionsRelationManager.php, app-modules/assist-data-model/src/Models/Student.php, app-modules/notifications/database/migrations/2023_08_23_204728_create_subscriptions_table.php, app-modules/notifications/src/Actions/SubscriptionToggle.php, app-modules/notifications/src/Models/Contracts/Subscribable.php, app-modules/notifications/src/Models/Subscription.php, app-modules/notifications/src/Providers/NotificationsServiceProvider.php, app-modules/prospect/src/Models/Prospect.php, app/Models/User.php
Sets up Student Subscription handling the following items:
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/191/
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/193/
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/195/
=> [Feature] Subscribe to student

app-modules/task/src/Filament/Resources/TaskResource.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/CreateTask.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/141/
Also some loose setup of the view
=> [Feature] Create Task

app/Filament/Pages/Dashboard.php, app/Filament/Widgets/Concerns/FormatsCount.php, app/Filament/Widgets/MyProspects.php, app/Filament/Widgets/MyStudents.php, app/Filament/Widgets/RecentLeadsList.php, app/Filament/Widgets/StatsOverviewWidget.php, app/Filament/Widgets/TotalProspects.php, app/Filament/Widgets/TotalStudents.php, app/Providers/Filament/AdminPanelProvider.php, resources/views/vendor/filament-panels/components/logo.blade.php
This PR introduces some baseline User Dashboard functionality, including:
- Total Student count widget
- Total Prospect count widget
- My Student count widget
- My Prospect count widget
- Recent leads table (need to consolidate language between lead/prospect)
Currently, the welcome message for the admin user is not ideal. I'm working with Dan to see if there is a slightly better way to customize this without touching too many Filament components. If there is not, we may want to consider revising how we approach this.
=> [Feature] User Dashboard

app-modules/assist-data-model/src/Filament/Resources/StudentResource.php, app-modules/assist-data-model/src/Models/Student.php, app-modules/engagement/src/Models/EngagementResponse.php, app-modules/prospect/src/Filament/Resources/ProspectResource.php, app-modules/prospect/src/Models/Prospect.php, app-modules/task/src/Filament/Resources/TaskResource/Components/TaskViewAction.php, app-modules/task/src/Filament/Resources/TaskResource/RelationManagers/TasksRelationManager.php, app-modules/webhook/src/Models/InboundWebhook.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/181/
=> [Feature] Student and Prospect task managers

app-modules/engagement/src/Filament/Resources/EngagementFileResource/Pages/ViewEngagementFile.php, config/logging.php
Small deployment fixes for access and permissions.
=> [Hotfix] Deployment fixes

app-modules/alert/composer.json, app-modules/assist-data-model/composer.json, app-modules/assist-data-model/composer.lock, app-modules/audit/composer.json, app-modules/audit/composer.lock, app-modules/authorization/composer.json, app-modules/authorization/composer.lock, app-modules/engagement/composer.json, app-modules/integration-twilio/composer.json, app-modules/knowledge-base/composer.json, app-modules/notifications/composer.json, app-modules/prospect/composer.json, app-modules/prospect/composer.lock, app-modules/service-management/composer.json, app-modules/service-management/composer.lock, app-modules/task/composer.json, app-modules/webhook/composer.json, composer.json, composer.lock
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/319/
Update all packages that we can to be at a stable version.
Additional details can be found in the ticket.
=> [ASSIST-319] Package Stability Update

app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php, app-modules/assist-data-model/src/Models/Student.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/333/
=> [ASSIST-333]: Address Search Bug on Students and Prospects 

app-modules/alert/src/Filament/RelationManagers/AlertsRelationManager.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementFilesRelationManager.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementResponsesRelationManager.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/RelationManagers/SubscriptionsRelationManager.php, app-modules/authorization/src/Filament/Resources/PermissionResource/RelationManagers/RolesRelationManager.php, app-modules/authorization/src/Filament/Resources/RoleGroupResource/RelationManagers/PermissionsRelationManager.php, app-modules/authorization/src/Filament/Resources/RoleGroupResource/RelationManagers/RolesRelationManager.php, app-modules/authorization/src/Filament/Resources/RoleGroupResource/RelationManagers/UsersRelationManager.php, app-modules/authorization/src/Filament/Resources/RoleResource/RelationManagers/PermissionsRelationManager.php, app-modules/engagement/src/Filament/Resources/EngagementResource/RelationManagers/EngagementDeliverablesRelationManager.php, app-modules/engagement/src/Filament/Resources/EngagementResource/RelationManagers/UserRelationManager.php, app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementFilesRelationManager.php, app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementResponsesRelationManager.php, app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementsRelationManager.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/AssignedToRelationManager.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/CreatedByRelationManager.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/ServiceRequestUpdatesRelationManager.php, app-modules/task/src/Filament/Resources/TaskResource/RelationManagers/TasksRelationManager.php, app/Filament/Resources/RelationManagers/RelationManager.php, app/Filament/Resources/UserResource/RelationManagers/PermissionsRelationManager.php, app/Filament/Resources/UserResource/RelationManagers/RoleGroupsRelationManager.php, app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php, stubs/filament/RelationManager.stub
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/339/
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/347/
=> ASSIST-339-347

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/335/
=> [ASSIST-335] Enhanced Prospects List View

app-modules/audit/src/Filament/Resources/AuditResource/Pages/ViewAudit.php, app-modules/engagement/src/Filament/Resources/EngagementFileResource/Pages/ViewEngagementFile.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/ViewEngagement.php, app-modules/engagement/src/Filament/Resources/EngagementResponseResource/Pages/ViewEngagementResponse.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseCategoryResource/Pages/ViewKnowledgeBaseCategory.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ViewKnowledgeBaseItem.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseQualityResource/Pages/ViewKnowledgeBaseQuality.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseStatusResource/Pages/ViewKnowledgeBaseStatus.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php, app-modules/prospect/src/Filament/Resources/ProspectSourceResource/Pages/ViewProspectSource.php, app-modules/prospect/src/Filament/Resources/ProspectStatusResource/Pages/ViewProspectStatus.php, app-modules/service-management/src/Filament/Resources/ServiceRequestPriorityResource/Pages/ViewServiceRequestPriority.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php, app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource/Pages/ViewServiceRequestStatus.php, app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ViewServiceRequestType.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Pages/ViewServiceRequestUpdate.php, app-modules/webhook/src/Filament/Resources/InboundWebhookResource/Pages/ViewInboundWebhook.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/343/
=> [ASSIST-343] Modify Background for View Mode When Presenting Record Information

app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php, app-modules/assist-data-model/src/Models/Student.php, app-modules/notifications/src/Filament/Actions/SubscribeBulkAction.php, app-modules/notifications/src/Filament/Actions/SubscribeHeaderAction.php, app-modules/notifications/src/Filament/Actions/SubscribeTableAction.php, app-modules/notifications/src/Models/Concerns/HasSubscriptions.php, app-modules/notifications/src/Models/Contracts/Subscribable.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php, app-modules/prospect/src/Models/Prospect.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/267/
=> [ASSIST-267] Ensure Subscription works for Prospects

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/409/
=> [ASSIST-409] Add Filters for KB Articles

app/Filament/Widgets/RecentLeadsList.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/417/
=> [ASSIST-417] Replace Recent Leads with Recent Prospects on Dashboard

app-modules/theme/src/Filament/Pages/ManageThemeSettings.php, resources/views/vendor/filament-panels/components/logo.blade.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/381/
=> [ASSIST-381]: Display theme settings logo as private signed URL 

app-modules/audit/database/migrations/2023_08_15_021059_create_audits_table.php, app-modules/audit/src/Filament/Resources/AuditResource/Pages/ListAudits.php, app-modules/audit/src/Filament/Resources/AuditResource/Pages/ViewAudit.php, app-modules/audit/src/Models/Audit.php, app/Models/User.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/305/
=> [ASSIST-305]: Searchability and filtering of Audit Table 

app-modules/task/database/factories/TaskFactory.php, app-modules/task/database/migrations/2023_08_28_155923_create_tasks_table.php, app-modules/task/src/Filament/Concerns/TaskEditForm.php, app-modules/task/src/Filament/Concerns/TaskViewActionInfoList.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/CreateTask.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php, app-modules/task/src/Models/Task.php, app-modules/task/tests/ListTasksTest.php, app-modules/task/tests/RequestFactories/EditTaskRequestFactory.php, resources/views/livewire/task-kanban.blade.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/455/
=> [ASSIST-455] Task Management Updates

.env.example, composer.json, composer.lock, config/debugbar.php, storage/debugbar/.gitignore
This is the first stage of identifying a possible performance issue on the staging server. Debugbar will help us identify any slow database queries or Livewire components which could affect the dashboard.
To clarify: this does not introduce any loading enhancement fixes, the ticket should be moved from "blocked" to "in progress" when this is merged.
=> [ASSIST-331]: Dashboard: Loading Enhancements

.github/workflows/ci.yml, _ide_helper_models.php, app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/ListInteractions.php, app-modules/interaction/src/Imports/InteractionsImporter.php, app-modules/interaction/src/Models/Interaction.php, app-modules/team/src/Models/Team.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/463/
=> [ASSIST-463] Implement Interaction Importer

.github/workflows/ci.yml, _ide_helper_models.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php, app-modules/task/src/Imports/TaskImporter.php, app-modules/task/src/Models/Task.php, app-modules/team/src/Models/Team.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/473/
=> [ASSIST-473]: Implement Task Importer

app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/EditEngagement.php, app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/CreateInteraction.php, app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/EditInteraction.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/CreateServiceRequest.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/EditServiceRequest.php, app-modules/task/src/Filament/Concerns/TaskEditForm.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/CreateTask.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/517/
=> [ASSIST-517]: Student/Prospect preload bugfix for search fields

app-modules/assistant/src/Filament/Resources/AssistantChatMessageLogResource.php, app-modules/audit/src/Filament/Resources/AuditResource.php, app-modules/authorization/src/Filament/Resources/PermissionResource.php, app-modules/authorization/src/Filament/Resources/RoleGroupResource.php, app-modules/authorization/src/Filament/Resources/RoleResource.php, app-modules/division/src/Filament/Resources/DivisionResource.php, app-modules/integration-google-analytics/src/Filament/Pages/ManageGoogleAnalyticsSettings.php, app-modules/integration-microsoft-clarity/src/Filament/Pages/ManageMicrosoftClaritySettings.php, app-modules/team/src/Filament/Resources/TeamResource.php, app/Filament/Pages/ProductHealth.php, app/Providers/Filament/AdminPanelProvider.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/525/
=> [ASSIST-525]: Minor Menu Item Changes

app-modules/form/src/Filament/Resources/FormResource.php, app/Providers/Filament/AdminPanelProvider.php
Part of this: https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/459/
=> [ASSIST-459-2]: Form menu changes

composer.json, composer.lock
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/571/
=> [ASSIST-571]: Resolve CVE-2023-43655 in GitHub repository 

app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentTasks.php, app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/CreateInteraction.php, app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/EditInteraction.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/CreateServiceRequest.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/EditServiceRequest.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource.php, app-modules/task/src/Filament/Concerns/TaskEditForm.php, app-modules/task/src/Filament/Concerns/TaskViewActionInfoList.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/CreateTask.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php, app-modules/task/src/Imports/TaskImporter.php, app/Filament/Widgets/MyServiceRequests.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/529/
=> [ASSIST-529]: Update relationship label in UI for multiple models

.gitignore, _ide_helper_models.php, app-modules/assistant/resources/js/assistantCurrentResponse.js, app-modules/assistant/resources/views/filament/pages/ai-assistant.blade.php, app-modules/assistant/src/Filament/Pages/PersonalAssistant.php, app-modules/assistant/src/Providers/AssistantServiceProvider.php, app-modules/integration-ai/src/Client/BaseAIChatClient.php, app-modules/task/src/Providers/TaskServiceProvider.php, bin/build.js, package-lock.json, package.json, resources/js/app.js
Set's up the process to display formatted AI text via markdown that is sanitized.
During this process, I have started the first implementation of how we should be setting up JS implementations that rely on NPM packages.
@danharrin let me know if you think there is a better way.
The important things are that it is compiled so that we can make use of NPM packages without having to load them directly onto the pages. It is easy to configure. And that the JS is only ever loaded on the page it is needed.
=> [ASSIST-429]: UI/UX: Artificial Intelligence Render Formatted Text 

app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentTasks.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectTasks.php, app-modules/task/src/Filament/RelationManagers/BaseTaskRelationManager.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/567/
=> [ASSIST-567]: Add ability to add a new task from Prospect Record like you can from the Student Record

app-modules/alert/src/Notifications/AlertCreatedNotification.php, app-modules/notifications/src/Listeners/NotifyUserOfSubscriptionCreated.php, app-modules/notifications/src/Listeners/NotifyUserOfSubscriptionDeleted.php, app-modules/task/src/Notifications/TaskAssignedToUser.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/577/
=> [ASSIST-577]: Enhance Notifications by Making Subscriptions Hyperlinked

app-modules/alert/src/Policies/AlertPolicy.php, app-modules/audit/src/Policies/AuditPolicy.php, app-modules/authorization/src/Policies/PermissionPolicy.php, app-modules/authorization/src/Policies/RoleGroupPolicy.php, app-modules/authorization/src/Policies/RolePolicy.php, app-modules/caseload-management/src/Policies/CaseloadPolicy.php, app-modules/division/src/Policies/DivisionPolicy.php, app-modules/engagement/src/Policies/EngagementDeliverablePolicy.php, app-modules/engagement/src/Policies/EngagementFilePolicy.php, app-modules/engagement/src/Policies/EngagementPolicy.php, app-modules/engagement/src/Policies/EngagementResponsePolicy.php, app-modules/knowledge-base/src/Policies/KnowledgeBaseCategoryPolicy.php, app-modules/knowledge-base/src/Policies/KnowledgeBaseItemPolicy.php, app-modules/knowledge-base/src/Policies/KnowledgeBaseQualityPolicy.php, app-modules/knowledge-base/src/Policies/KnowledgeBaseStatusPolicy.php, app-modules/prospect/src/Policies/ProspectPolicy.php, app-modules/prospect/src/Policies/ProspectSourcePolicy.php, app-modules/prospect/src/Policies/ProspectStatusPolicy.php, app-modules/service-management/src/Policies/ServiceRequestPolicy.php, app-modules/service-management/src/Policies/ServiceRequestPriorityPolicy.php, app-modules/service-management/src/Policies/ServiceRequestStatusPolicy.php, app-modules/service-management/src/Policies/ServiceRequestTypePolicy.php, app-modules/service-management/src/Policies/ServiceRequestUpdatePolicy.php, app-modules/task/src/Policies/TaskPolicy.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/447/
=> [ASSIST-447]: Use `canOrElse` in policies for consistency

app/Filament/Pages/Calendar.php, app/Filament/Pages/Events.php, app/Providers/Filament/AdminPanelProvider.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/625/
=> [ASSIST-625]: Create new navigation item "Meeting Center" under Productivity Tools.

app-modules/assistant/resources/views/filament/pages/ai-assistant.blade.php
Some sidebar styling fixes I made to the AI assistant while waiting for the tests to run earlier 😁
=> AI assistant styling fixes

composer.lock
Might be worth an immediate push to staging so Joe has this fix for his demos.
=> [ASSIST-637]: Bug: AI hanging on a task.

_ide_helper_models.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentSubscriptions.php, app-modules/assist-data-model/src/Models/Student.php, app-modules/notifications/database/migrations/2023_08_23_204728_create_subscriptions_table.php, app-modules/notifications/src/Events/SubscriptionDeleted.php, app-modules/notifications/src/Models/Subscription.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectSubscriptions.php, app-modules/prospect/src/Models/Prospect.php, app/Models/User.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/633/
=> [ASSIST-633]: Bug: Resolve view of student/prospect subscriptions 

app-modules/authorization/src/Models/Concerns/HasRolesWithPivot.php, app-modules/engagement/database/factories/EngagementDeliverableFactory.php, app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php, app-modules/engagement/src/Enums/EngagementDeliveryMethod.php, app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php, app-modules/engagement/src/Filament/Actions/EngagementCreateAction.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php, app-modules/engagement/src/Models/EngagementDeliverable.php, app-modules/engagement/tests/Feature/Actions/CreateEngagementBatchTest.php, app-modules/integration-twilio/src/Http/Controllers/TwilioInboundWebhookController.php, app-modules/interaction/src/Enums/InteractionStatusColorOptions.php, app-modules/prospect/database/seeders/ProspectStatusSeeder.php, app-modules/prospect/src/Enums/ProspectStatusColorOptions.php, app-modules/service-management/database/factories/ServiceRequestStatusFactory.php, app-modules/service-management/database/seeders/ServiceRequestStatusSeeder.php, app-modules/service-management/src/Enums/ColumnColorOptions.php, app-modules/task/src/Enums/TaskStatus.php, app-modules/task/src/Filament/Pages/Components/TaskKanbanViewAction.php, app-modules/task/src/Filament/RelationManagers/BaseTaskRelationManager.php, app-modules/task/src/Filament/Resources/TaskResource/Components/TaskViewAction.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php, app-modules/task/src/Models/Task.php, app-modules/task/tests/ListTasksTest.php, app-modules/webhook/src/Enums/InboundWebhookSource.php, resources/views/livewire/task-kanban.blade.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/443/
=> [ASSIST-443]: Consistent naming for ENUM cases within the application 

app-modules/task/resources/views/filament/pages/list-tasks.blade.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php, app-modules/task/src/Models/Task.php, app/Livewire/TaskKanban.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/531/
Within Ticket
=> [ASSIST-531]: Filter Kanban View for Tasks

.github/workflows/ci.yml, app/Providers/MultiConnectionParallelTestingServiceProvider.php, config/app.php, phpunit-ci.xml
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/489/
Allows for parallel testing with out multi-database setup.
=> [ASSIST-489]: Spike: Improve speed of tests

README.md
- [ASSIST-647](https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/647/)
Readme file update, functionality unaffected.
N/A
=> [ASSIST-647]: Update documentation - project details in README file

app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php, app-modules/caseload-management/src/Actions/TranslateCaseloadFilters.php, app-modules/caseload-management/src/Console/Commands/TranslateCaseload.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php, app/Models/User.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/615/
Altered the way that TranslateCaseloadFilters to simplify, and also fully support the query builder, which depends on a Livewire component existing for the filter form to be mounted to.
=> [ASSIST-615]: Create caseload filter for student and prospects.

app/Providers/Filament/AdminPanelProvider.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/675/
Changed admin panel to use the full max content width.
=> [ASSIST-675]: Use full screen option in Filament

.github/workflows/ci.yml, .github/workflows/pull_requests.yml, package-lock.json, resources/views/form-test.blade.php
Testing CI changes to trigger checks
=> Call for PAT secret

app-modules/authorization/src/Http/Controllers/SocialiteController.php, app/Filament/Pages/EditProfile.php, app/Filament/Resources/PronounsResource.php, app/Filament/Resources/PronounsResource/Pages/ManagePronouns.php, app/Models/Pronouns.php, app/Models/User.php, app/Providers/Filament/AdminPanelProvider.php, composer.lock, database/factories/PronounsFactory.php, database/migrations/2023_03_05_000005_create_pronouns_table.php, database/migrations/2023_03_06_000005_create_users_table.php, database/seeders/DatabaseSeeder.php, database/seeders/PronounsSeeder.php, resources/views/filament/pages/edit-profile.blade.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/657/
SSO avatar is not currently tested.
Divisions are skipped but can easily be added once the relationship exists.
=> [ASSIST-657]: Introduce User Profile

app-modules/form/src/Filament/Resources/FormResource/RelationManagers/FormSubmissionsRelationManager.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/757/
Remove UUID from Form Submissions Display (Replace with Date/Time Stamp).
=> [ASSIST-757]: Remove UUID from Form Submissions Display (Replace with Date/Time Stamp).

app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/727/
Update naming in Create Campaign wizard.
=> [ASSIST-727]: Update naming in Create Campaign wizard.

app/Filament/Pages/Dashboard.php, app/Filament/Widgets/MyProspects.php, app/Filament/Widgets/MyStudents.php, app/Filament/Widgets/ProspectGrowthChart.php, app/Filament/Widgets/RecentKnowledgeBaseArticlesList.php, app/Filament/Widgets/RecentLeadsList.php, app/Filament/Widgets/RecentProspectsList.php, composer.lock
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/695/
Dashboard Enhancements.
=> [ASSIST-695]: Dashboard Enhancements

app/Filament/Pages/EditProfile.php, app/Models/User.php, composer.json, composer.lock, database/migrations/2023_03_06_000005_create_users_table.php, resources/views/filament/widgets/welcome-widget.blade.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/759/
User timezone.
=> [ASSIST-759]: Add timezone configuration to user profiles.

app-modules/caseload-management/src/Filament/Resources/CaseloadResource/Pages/CreateCaseload.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/711/
Renamed as per ticket.
=> [ASSIST-711]: Rename Caseload Wizard Headings

_ide_helper_models.php, app-modules/consent/src/Models/UserConsentAgreement.php, app-modules/form/routes/api.php, app-modules/form/src/Actions/GenerateFormFieldFormKitSchema.php, app-modules/form/src/Actions/GenerateFormValidation.php, app-modules/form/src/Http/Controllers/FormWidgetController.php, app/Http/Middleware/VerifyCsrfToken.php, widgets/form/src/App.vue
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/691/
Sets up the process to submit an embedded form and allows us to easily define validation for form fields based on their configuration.
=> [ASSIST-691]: Create an API endpoint for form submission and handle submission on the frontend 

app-modules/assistant/resources/views/filament/pages/ai-assistant.blade.php, app-modules/assistant/src/Filament/Pages/PersonalAssistant.php, app-modules/assistant/src/Models/AssistantChatMessage.php, app-modules/assistant/src/Providers/AssistantServiceProvider.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/745/
Share AI chat with one or more users or  one or more teams.
=> [ASSIST-745]: Share AI chat with another staff member.

app-modules/meeting-center/src/Console/Commands/CreateEvent.php, app-modules/meeting-center/src/Console/Commands/SyncEvents.php, database/seeders/SuperAdminSeeder.php, database/seeders/UsersTableSeeder.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/761/
This PR updates the default super admin user email address
=> [ASSIST-761]: Change default user from superadmin@assist.com to sampleadmin@advising.app

app-modules/form/src/Filament/Pages/ManageAdmissions.php, app-modules/form/src/Filament/Pages/ManageSurveys.php, app-modules/form/src/Filament/Resources/FormResource.php, app-modules/form/src/FormPlugin.php, app/Providers/Filament/AdminPanelProvider.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/709/?MID=2419#com2419
This PR adds "coming soon" pages for "Manage Admissions" and "Manage Surveys", and changes the navigation group label to "Forms and Surveys".
=> [ASSIST-709]: Add Coming Soon Pages under Forms for Manage Applications and Manage Surveys 

app-modules/caseload-management/src/Filament/Resources/CaseloadResource.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/719/
This PR adds the QueryBuilder functionality to the prospect filters in the Caseload builder.
=> [ASSIST-719] Add Query Builder to Dynamic Prospect Caseload Builder

app-modules/campaign/src/Enums/CampaignActionType.php, app-modules/campaign/src/Filament/Blocks/CampaignActionBlock.php, app-modules/campaign/src/Filament/Blocks/EngagementBatchBlock.php, app-modules/campaign/src/Filament/Blocks/ServiceRequestBlock.php, app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php, app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/EditCampaign.php, app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php, app-modules/campaign/src/Models/CampaignAction.php, app-modules/campaign/src/Models/Contracts/ExecutableFromACampaignAction.php, app-modules/engagement/src/Models/EngagementBatch.php, app-modules/service-management/src/Models/ServiceRequest.php
https://engage.canyongbs.com/company/personal/user/15/tasks/task/view/723/
This PR adds support for Service Requests in Campaigns.
=> [ASSIST-723]: Add a new campaign type for Service Requests

app-modules/meeting-center/src/Jobs/SyncCalendar.php, app-modules/meeting-center/src/Jobs/SyncCalendars.php, app-modules/meeting-center/src/Managers/Contracts/CalendarInterface.php, app-modules/meeting-center/src/Managers/GoogleCalendarManager.php, app-modules/meeting-center/src/Managers/OutlookCalendarManager.php, app-modules/meeting-center/src/Providers/MeetingCenterServiceProvider.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/769/
Ongoing user calendar sync (with Google).
=> [ASSIST-769]: Google Sync (Ongoing Sync Process)

app-modules/audit/src/Filament/Pages/ManageAuditSettings.php
Fix reference to non-existent method “constraints” on Select within the ManageAuditSettings page. Change it to “rules”.
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/813/
Fixes a bug referencing a non-existent method for a Select input on the `ManageAuditSettings` page.
=> [ASSIST-813]: Bug: Product Administration > Audit Configuration Results in Laravel Error

app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/753/
=> [ASSIST-753]: Show all student characteristics from the student table in the "View" option

app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/753/
Quick update to change Entry to Enrollment
=> [ASSIST-753]: Update Entry to Enrollment

app-modules/assist-data-model/src/Filament/Resources/StudentResource/RelationManagers/PerformanceRelationManager.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/715/
Change Performances to be Performance in the Student Holistic view information area.
=> [ASSIST-715]: Rename Performances under Student > Information to Performance

app-modules/campaign/database/factories/CampaignActionFactory.php, app-modules/campaign/database/factories/CampaignFactory.php, app-modules/campaign/database/migrations/2023_10_11_204551_create_campaigns_table.php, app-modules/campaign/src/Actions/ExecuteCampaignActions.php, app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php, app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/EditCampaign.php, app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/ViewCampaign.php, app-modules/campaign/src/Models/Campaign.php, app-modules/campaign/src/Models/CampaignAction.php, app-modules/campaign/tests/Actions/ExecuteCampaignActionsTest.php, resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php, resources/views/filament/forms/components/campaigns/actions/service-request.blade.php, resources/views/filament/forms/components/campaigns/step-summary.blade.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/731/
This PR adds the "review campaign" timeline at the end of the campaign creation process, as well as an "enabled" flag on the campaign that will control whether or not campaign actions are executed.
=> [ASSIST-731]: Update "Review Campaign" to Show Timeline View of Journey Steps (Actions)

app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php, app-modules/assistant/src/Filament/Pages/PersonalAssistant.php, app-modules/consent/database/seeders/ConsentAgreementSeeder.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/661/
This PR updates some styles related to the AI Consent Agreement. It also renames the `ai-assistant` file to match the new convention of `personal-assistant`
=> [ASSIST-661]: Artificial Intelligence Consent Agreement UI/UX Updates

app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/713/
Split the caseload filter for Students and Prospects into a My Caseloads and All Caseloads filter for better UI/UX.
=> [ASSIST-713]: Enhance Student and Prospect Caseload Filters 

app/Filament/Widgets/RecentKnowledgeBaseArticlesList.php, app/Filament/Widgets/RecentProspectsList.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/793/
Condenses the dashboard tables to only show the most important information by default. 
=> [ASSIST-793]: Enhance Presentation of Latest Prospects and Latest KB articles tables in Dashboard. 

_ide_helper_models.php, app-modules/assistant/src/Models/AssistantChatFolder.php, app-modules/campaign/src/Models/CampaignAction.php
Tests on #240 are failing because I think this column has the wrong name?
=> fix: Campaign action column

app-modules/engagement/src/Filament/Resources/EngagementFileResource.php, app-modules/engagement/src/Filament/Resources/EngagementFileResource/Pages/CreateEngagementFile.php, app-modules/engagement/src/Filament/Resources/EngagementFileResource/Pages/EditEngagementFile.php, app-modules/engagement/src/Filament/Resources/EngagementFileResource/Pages/ViewEngagementFile.php, app-modules/engagement/src/Filament/Resources/EngagementFileResource/RelationManagers/EngagementFilesRelationManager.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/733/
Updates the text of the Engagement Files CRUD as described in the ticket.
=> [ASSIST-733]: Update Top Level Nav "Files and Documents" to Match Student/Prospect Experience Including Retention Capabilities

_ide_helper_models.php, app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php, app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/789/
As described in ticket.
https://github.com/canyongbs/assistbycanyongbs/assets/41773797/ecb28752-1fc9-4bdf-9af3-3e902dd984e2
=> [ASSIST-789]: Enhance UI/UX for Personal Assistant Clone and Email Features

_ide_helper_models.php, app-modules/assistant/config/permissions/web/custom.php, app-modules/assistant/config/roles/web/assistant_ai_settings_access.php, app-modules/assistant/src/Filament/Pages/AssistantConfiguration.php, app-modules/assistant/src/Filament/Pages/ManageAiSettings.php, app-modules/assistant/tests/Feature/Filament/Pages/AssistantConfigurationPageTest.php, app-modules/assistant/tests/Feature/Filament/Pages/ManageAiSettingsPageTest.php, app-modules/campaign/src/Models/CampaignAction.php, app-modules/care-team/src/Models/CareTeam.php, app-modules/consent/src/Filament/Resources/ConsentAgreementResource.php, app-modules/consent/src/Filament/Resources/ConsentAgreementResource/Pages/EditConsentAgreement.php, app-modules/consent/src/Filament/Resources/ConsentAgreementResource/Pages/ListConsentAgreements.php, app-modules/consent/src/Models/ConsentAgreement.php, app-modules/consent/src/Observers/ConsentAgreementObserver.php, app-modules/consent/src/Providers/ConsentServiceProvider.php, resources/views/assist/assistant/filament/pages/assistant-configuration.blade.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/703/
Adds additional configuration for an admin to be able to configure the base prompt for AI chat.
=> [ASSIST-703]: Introduce Product Level Configurability for the Personal Assistant Base Prompt

app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
=> fix: Assistant icon regression

app-modules/alert/src/Filament/Resources/AlertResource.php, app-modules/alert/src/Filament/Resources/AlertResource/Pages/ListAlerts.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/861/
Add ability to create a new alert from main navigation for a student or prospect.
=> [ASSIST-861]: Add ability to create a new alert from main navigation for a student or prospect.

.gitignore, app-modules/campaign/src/Enums/CampaignActionType.php, app-modules/campaign/src/Filament/Blocks/TaskBlock.php, app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php, app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php, app-modules/campaign/src/Models/CampaignAction.php, app-modules/campaign/tests/Actions/TaskCampaignTest.php, app-modules/task/src/Models/Task.php, resources/views/filament/forms/components/campaigns/actions/task.blade.php, resources/views/filament/forms/components/campaigns/step-summary.blade.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/725/
Add a new campaign type for Tasks.
=> [ASSIST-725]: Add a new campaign type for Tasks

app-modules/assistant/src/Jobs/ShareAssistantChatJob.php, app-modules/assistant/src/Jobs/ShareAssistantChatsJob.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/897/
Fixed sharing chats in folders.
=> [ASSIST-897]: Bug: Cloning a chat in a folder results in generation of a copy

app-modules/authorization/src/Http/Controllers/SocialiteController.php, app/Models/User.php, database/migrations/2023_03_06_000004_create_users_table.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/685/
Make API call to fetch Azure profile picture on SSO.
=> [ASSIST-685]: Make API call to fetch Azure profile picture on SSO

app-modules/service-management/src/Enums/ServiceRequestUpdateDirection.php, app-modules/service-management/src/Filament/Concerns/ServiceRequestUpdateInfolist.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/ServiceRequestUpdatesRelationManager.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Pages/ViewServiceRequestUpdate.php, app-modules/service-management/tests/ServiceRequestUpdate/CreateServiceRequestUpdateTest.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/919/
Default new Service Request Update to Outbound.
=> [ASSIST-919]: Default New SR Update to Outbound

app/Filament/Pages/AnalyticsPortal.php, app/Filament/Pages/DataLakehouse.php, app/Providers/Filament/AdminPanelProvider.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/901/
Create Data and Analytics primary navigation group.
=> [ASSIST-901]: Create Data and Analytics primary navigation group

app-modules/campaign/src/Filament/Blocks/CareTeamBlock.php, app-modules/campaign/src/Filament/Blocks/EngagementBatchBlock.php, app-modules/campaign/src/Filament/Blocks/InteractionBlock.php, app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php, app-modules/campaign/src/Filament/Blocks/ServiceRequestBlock.php, app-modules/campaign/src/Filament/Blocks/TaskBlock.php, app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/895/
Campaign build text changes.
=> [ASSIST-895]: Enhancements to display and label usage in campaign builder

app-modules/meeting-center/database/migrations/2023_10_16_133341_create_calendars_table.php, app-modules/meeting-center/database/migrations/2023_10_16_134402_create_calendar_events_table.php, app-modules/meeting-center/src/Filament/Resources/CalendarEventResource.php, app-modules/meeting-center/src/Filament/Resources/CalendarEventResource/Pages/CreateCalendarEvent.php, app-modules/meeting-center/src/Filament/Resources/CalendarEventResource/Pages/EditCalendarEvent.php, app-modules/meeting-center/src/Filament/Resources/CalendarEventResource/Pages/ListCalendarEvents.php, app-modules/meeting-center/src/Filament/Resources/CalendarEventResource/Pages/ViewCalendarEvent.php, app-modules/meeting-center/src/Http/Controllers/GoogleCalendarController.php, app-modules/meeting-center/src/Managers/GoogleCalendarManager.php, app-modules/meeting-center/src/Models/Calendar.php, app-modules/meeting-center/src/Models/CalendarEvent.php, app-modules/meeting-center/src/Observers/CalendarEventObserver.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/911/
Manage Google Calendar events.
=> [ASSIST-911]: Create a New Event

app/Providers/FilamentServiceProvider.php, resources/views/assist/filament/footer.blade.php
https://engage.canyongbs.com/company/personal/user/15/tasks/task/view/885/
This PR adds the Canyon GBS footer to all pages in Filament.
=> [ASSIST-885]: Create Product Footer

app-modules/meeting-center/src/Filament/Resources/CalendarEventResource.php, app-modules/meeting-center/src/Filament/Resources/CalendarEventResource/Pages/ListCalendarEvents.php, app-modules/meeting-center/src/Managers/GoogleCalendarManager.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/921/
Rename Events to Schedule. I noticed I was using the wrong create action, the table action instead of the page action so I switched that. I also noticed if you synced an existing event it did not sync the attendees so I added that.
=> [ASSIST-921]: Rename Events > Schedule

app-modules/form/src/Filament/Resources/FormResource/Pages/Concerns/HasSharedFormConfiguration.php, app/Filament/Resources/EmailTemplateResource/Pages/CreateEmailTemplate.php, app/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php, app/Forms/Components/ColorSelect.php, app/Providers/FilamentServiceProvider.php, package-lock.json, resources/views/vendor/mail/html/layout.blade.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/909/
Show Color on Left, Alphabetize List.
=> [ASSIST-909]: Show Color Next to Primary Color/Theme Name in Forms

package-lock.json, package.json, resources/js/bootstrap.js
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/955/
Remove unused dependencies that use an outdated version of axios.
=> [ASSIST-955]: Security: (CWE-352) Resolve Axios Cross-Site Request Forgery Vulnerability

app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php, app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php, app-modules/engagement/src/Filament/Actions/Concerns/ImplementsHasBulkEngagementAction.php, app-modules/engagement/src/Filament/Actions/Contracts/HasBulkEngagementAction.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/953/
Fixed creating a bulk engagement on the Student list generates an error.
=> [ASSIST-953]: Bug: Creating a bulk engagement on the Student list generates an error

_ide_helper_models.php, app-modules/form/database/factories/FormSubmissionFactory.php, app-modules/form/src/Events/FormSubmissionCreated.php, app-modules/form/src/Http/Controllers/FormWidgetController.php, app-modules/form/src/Listeners/NotifySubscribersOfFormSubmission.php, app-modules/form/src/Models/FormSubmission.php, app-modules/form/src/Notifications/AuthorLinkedFormSubmissionCreatedNotification.php, app-modules/form/src/Observers/FormSubmissionObserver.php, app-modules/form/src/Providers/FormServiceProvider.php, app-modules/form/tests/FormSubmissionCreatedTest.php, app/Models/EmailTemplate.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/859/
Adds a notification to subscribers when a Student or Prospect submits a Form.
=> [ASSIST-859]: Create a notification for subscribers when a submission is linked to a student or prospect

composer.lock
As featured in the demo ✨
The error in the demo originated from the TipTap editor. A fix was released 5 hours ago.
Might be worth patching this to prod as it affects building forms quite heavily and can result in data loss
=> Fix issue with TipTap Editor when adding blocks and no content

app/Filament/Pages/EditProfile.php, app/Models/User.php, database/migrations/2023_03_06_000004_create_users_table.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/923/
Set Profile Availability for Office Hours.
=> [ASSIST-923]: Set Profile Availability for Office Hours

LICENSE, README.md, package-lock.json
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1045/
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1043/
Update README and LICENSE files.
=> [ADVISINGAPP-1045] / [ADVISINGAPP-1043]: Updating README and LICENSE files.

LICENSE, README.md, package-lock.json, package.json, resources/js/bootstrap.js
Syncs `develop` with recent hotfixes in `main`
=> Sync with main

resources/views/assist/filament/footer.blade.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1055/
Updates the copyright text in the footer of the application.
=> [ADVISING-1055] Update Copyright Text in Footer

composer.lock
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1061/
Ran `composer update` which updated all of our dependencies and resolved the vulnerability.
=> [ADVISING-1061] Fix reported phpseclib vulnerability

_ide_helper_models.php, app-modules/assistant/src/Filament/Pages/AssistantConfiguration.php, app-modules/assistant/src/Filament/Resources/AssistantChatMessageLogResource.php, app-modules/audit/src/Filament/Pages/ManageAuditSettings.php, app-modules/audit/src/Filament/Resources/AuditResource.php, app-modules/engagement/src/Filament/Resources/EmailTemplateResource.php, app-modules/engagement/src/Filament/Resources/SmsTemplateResource.php, app-modules/integration-google-analytics/src/Filament/Pages/ManageGoogleAnalyticsSettings.php, app-modules/integration-microsoft-clarity/src/Filament/Pages/ManageMicrosoftClaritySettings.php, app-modules/theme/src/Filament/Pages/ManageBrandConfigurationSettings.php, app-modules/webhook/src/Filament/Resources/InboundWebhookResource.php, app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php, app/DataTransferObjects/LicenseManagement/LicenseData.php, app/DataTransferObjects/LicenseManagement/LicenseLimitsData.php, app/DataTransferObjects/LicenseManagement/LicenseSubscriptionData.php, app/Filament/Pages/EmailConfiguration.php, app/Filament/Pages/ManageLicenseSettings.php, app/Filament/Pages/ProductHealth.php, app/Filament/Resources/NotificationSettingResource.php, app/Settings/LicenseSettings.php, database/settings/2023_11_29_192230_create_license_settings.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/995/
Adds application settings for License/Subscription Management. Right now we are not doing anything with these and we are seeding default values. This will be changed later.
=> [ADVISING-995]: Introduce Subscription Management

app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
=> fix: Bulk engagement body

_ide_helper_models.php, app-modules/service-management/config/roles/web/service_request_history_management.php, app-modules/service-management/database/factories/ServiceRequestHistoryFactory.php, app-modules/service-management/database/migrations/2023_12_01_205730_create_service_request_histories_table.php, app-modules/service-management/resources/views/components/service-request-history-timeline-item.blade.php, app-modules/service-management/resources/views/components/service-request-update-timeline-item.blade.php, app-modules/service-management/src/Actions/CreateServiceRequestHistory.php, app-modules/service-management/src/Filament/Concerns/ServiceRequestHistoryInfolist.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Components/ServiceRequestHistoryViewAction.php, app-modules/service-management/src/Models/ServiceRequest.php, app-modules/service-management/src/Models/ServiceRequestHistory.php, app-modules/service-management/src/Observers/ServiceRequestHistoryObserver.php, app-modules/service-management/src/Observers/ServiceRequestObserver.php, app-modules/service-management/src/Policies/ServiceRequestHistoryPolicy.php, app-modules/service-management/src/Providers/ServiceManagementServiceProvider.php, app-modules/timeline/src/Events/TimelineableRecordCreated.php, app-modules/timeline/src/Timelines/ServiceRequestHistoryTimeline.php, resources/views/filament/infolists/entries/update-entry.blade.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/949/
This PR adds historical tracking to ServiceRequests for the purpose of showing changes to the ServiceRequest over time. This PR should be reviewed and merged after https://github.com/canyongbs/advisingapp/pull/319
=> [ADVISING-949]: Track and display the core updates to a service request in the timeline

app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentEngagement.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementResponsesRelationManager.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php, app-modules/engagement/src/Filament/Resources/EngagementResource.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectEngagement.php, app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementResponsesRelationManager.php, app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementsRelationManager.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1069/?any=group%2F3%2Ftasks%2Ftask%2Fview%2F1069%2F
This PR updates labeling for Engagements on both the Student/Prospect resources.
=> [ADVISING-1069]: Change Engagements in Profile to Email and Texts

app-modules/application/database/factories/ApplicationSubmissionFactory.php, app-modules/application/src/Listeners/NotifySubscribersOfApplicationSubmission.php, app-modules/application/src/Notifications/AuthorLinkedApplicationSubmissionCreatedNotification.php, app-modules/application/src/Observers/ApplicationSubmissionObserver.php, app-modules/application/src/Providers/ApplicationServiceProvider.php, app-modules/application/tests/ApplicationSubmissionCreatedTest.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource.php, app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentApplicationSubmissions.php, app-modules/assist-data-model/src/Models/Student.php, app-modules/form/src/Observers/FormSubmissionObserver.php, app-modules/prospect/src/Filament/Resources/ProspectResource.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectApplicationSubmissions.php, app-modules/prospect/src/Models/Prospect.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1051/
This PR introduces an Application manager for both the Student and Prospect resources. It also mimics the notification functionality that exists for Forms.
=> [ADVISING-1051]: Display Submitted Applications in Student and Prospect views

package-lock.json, package.json
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1109/
Fixes security vuln defined in the report.
=> [ADVISING-1109]: Vite XSS vulnerability Dependabot alert 

app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/EditEngagement.php, composer.lock, resources/lang/vendor/filament-tiptap-editor/en/editor.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1073/
Renamed as per ticket.
=> [ADVISING-1073]: Rename "Merge Tags" with "Merge Values"

app-modules/authorization/config/roles/web/notification_setting_management.php, app-modules/engagement/config/roles/web/email_template_management.php, app-modules/engagement/config/roles/web/sms_template_management.php, app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/ListEmailTemplates.php, app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/ListSmsTemplates.php, app-modules/engagement/src/Policies/EmailTemplatePolicy.php, app-modules/engagement/src/Policies/SmsTemplatePolicy.php, app/Filament/Resources/NotificationSettingResource/Pages/ListNotificationSettings.php, app/Policies/NotificationSettingPolicy.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1059/
Discrete Permissions for EmailTemplates, TextMessageTemplates, and NotificationSettings.
=> [ADVISING-1059]: Discrete Permissions for EmailTemplates, TextMessageTemplates, and NotificationSettings

.github/workflows/ci.yml
- N/A
Uses a non-archived ruby installing for GitHub Actions CI.
=> Use non-archived ruby installer

.shift, composer.json, composer.lock
This pull request includes minor version updates for your package dependencies as well as major version updates for packages with known compatibility. Feel free to commit any additional changes to the `shift-106137` branch.
- Checkout the `shift-106137` branch
Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))
=> Dependency Updater

app-modules/assistant/src/Filament/Pages/AssistantConfiguration.php, app-modules/assistant/src/Filament/Pages/ManageAiSettings.php, app-modules/assistant/src/Filament/Pages/PersonalAssistant.php, app-modules/assistant/src/Filament/Resources/AssistantChatMessageLogResource.php, app-modules/assistant/src/Policies/AssistantChatMessageLogPolicy.php, app-modules/consent/src/Filament/Resources/ConsentAgreementResource/Pages/ListConsentAgreements.php, app-modules/consent/src/Policies/ConsentAgreementPolicy.php, app/Concerns/FeatureAccessEnforcedPolicyBefore.php, app/Enums/Feature.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1007/
Enforces License rules for Personal Assistant and Configuration pages.
=> [ADVISING-1007]: Enforce License Rules for Personal Assistant

package-lock.json, package.json, widgets/form/src/FormKit/Inputs/OneTimePassword.vue, widgets/form/src/FormKit/Inputs/Signature.vue, widgets/form/tailwind.config.preset.js
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1155/
Added a typed option to the signature field. Used HTML Canvas to convert it to an image.
https://github.com/canyongbs/advisingapp/assets/41773797/8b82548e-7ced-4b93-9162-87f67321f3d0
=> [ADVISING-1155]: Introduce Typed Signature Option for Forms

resources/css/filament/admin/theme.css
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1135/
Reduced space between groups from 7 to 4. Ticket has no detail so not sure if this is enough.
=> [ADVISING-1135]: Reduce spacing throughout left navigation.

app-modules/service-management/src/Policies/ServiceRequestAssignmentPolicy.php, app-modules/service-management/src/Policies/ServiceRequestHistoryPolicy.php, app-modules/service-management/src/Policies/ServiceRequestPolicy.php, app-modules/service-management/src/Policies/ServiceRequestPriorityPolicy.php, app-modules/service-management/src/Policies/ServiceRequestStatusPolicy.php, app-modules/service-management/src/Policies/ServiceRequestTypePolicy.php, app-modules/service-management/src/Policies/ServiceRequestUpdatePolicy.php, app-modules/service-management/tests/RequestFactories/CreateServiceRequestRequestFactory.php, app-modules/service-management/tests/RequestFactories/EditServiceRequestRequestFactory.php, app-modules/service-management/tests/ServiceRequest/CreateServiceRequestTest.php, app-modules/service-management/tests/ServiceRequest/EditServiceRequestTest.php, app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php, app-modules/service-management/tests/ServiceRequest/ViewServiceRequestTest.php, app-modules/service-management/tests/ServiceRequestPriority/CreateServiceRequestPriorityTest.php, app-modules/service-management/tests/ServiceRequestPriority/EditServiceRequestPriorityTest.php, app-modules/service-management/tests/ServiceRequestPriority/ListServiceRequestPrioritiesTest.php, app-modules/service-management/tests/ServiceRequestPriority/ViewServiceRequestPriorityTest.php, app-modules/service-management/tests/ServiceRequestStatus/CreateServiceRequestStatusTest.php, app-modules/service-management/tests/ServiceRequestStatus/EditServiceRequestStatusTest.php, app-modules/service-management/tests/ServiceRequestStatus/ListServiceRequestStatusesTest.php, app-modules/service-management/tests/ServiceRequestStatus/ViewServiceRequestStatusTest.php, app-modules/service-management/tests/ServiceRequestType/CreateServiceRequestTypeTest.php, app-modules/service-management/tests/ServiceRequestType/EditServiceRequestTypeTest.php, app-modules/service-management/tests/ServiceRequestType/ListServiceRequestTypeTest.php, app-modules/service-management/tests/ServiceRequestType/ViewServiceRequestTypeTest.php, app-modules/service-management/tests/ServiceRequestUpdate/CreateServiceRequestUpdateTest.php, app-modules/service-management/tests/ServiceRequestUpdate/EditServiceRequestUpdateTest.php, app-modules/service-management/tests/ServiceRequestUpdate/ListServiceRequestUpdatesTest.php, app-modules/service-management/tests/ServiceRequestUpdate/ViewServiceRequestUpdateTest.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1009/
Enforce License Rules for Service Management.
=> [ADVISING-1009]: Enforce License Rules for Service Management

app-modules/care-team/graphql/care-team.graphql, app-modules/care-team/src/Models/CareTeam.php, app-modules/care-team/src/Providers/CareTeamServiceProvider.php, app-modules/care-team/src/Rules/EducatableIdExistsRule.php, app-modules/care-team/src/Rules/UniqueCareTeamRule.php, app-modules/notifications/graphql/subscription.graphql, app-modules/notifications/src/Rules/SubscribableIdExistsRule.php, app-modules/notifications/src/Rules/UniqueSubscriptionRule.php
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1143/?any=group%2F3%2Ftasks%2Ftask%2Fview%2F1143%2F
Added care team API based on subscriptions. Added validation rules to subscriptions to match the care team validation rules for uniqueness and subscribable existence.
Dependant on #364, please merge that into #365 to read the proper diff for this PR.
=> [ADVISING-1143]: Add API Capabilities for Care Team

app-modules/application/src/Http/Middleware/EnsureOnlineAdmissionsFeatureIsActive.php, app-modules/form/routes/web.php, app-modules/form/src/Http/Middleware/EnsureFormsFeatureIsActive.php, app-modules/form/src/Policies/FormPolicy.php
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1003/
Enforce License Rules for Forms.
=> [ADVISING-1003]: Enforce License Rules for Forms

composer.json, composer.lock, resources/views/components/layouts/app.blade.php, resources/views/vendor/cookie-consent/dialog.blade.php, resources/views/vendor/cookie-consent/index.blade.php, tailwind.config.js
- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1105/
Added package. Was very simple, so I did some minor tweaks to make it fit our app a little bit.
=> [ADVISING-1105]: Introduce Spatie GDPR Cookie Package

app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php, app/Filament/Pages/AssetManagement.php, app/Filament/Pages/ChangeManagement.php, app/Filament/Pages/SLAConfiguration.php, app/Filament/Pages/ServiceDashboard.php, app/Filament/Resources/SystemUserResource.php, app/Filament/Resources/SystemUserResource/Pages/CreateSystemUser.php, app/Filament/Resources/SystemUserResource/Pages/EditSystemUser.php, app/Filament/Resources/SystemUserResource/Pages/ListSystemUsers.php, app/Providers/Filament/AdminPanelProvider.php, composer.lock
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1151/
Update Service Management in Navigation.
=> [ADVISING-1151]: Update Service Management in Navigation

app-modules/prospect/src/Filament/Resources/ProspectResource.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectServiceRequests.php, app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/ServiceRequestsRelationManager.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/CreateServiceRequest.php, app-modules/student-data-model/src/Filament/Resources/StudentResource.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentServiceRequests.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/ServiceRequestsRelationManager.php
https://canyongbs.atlassian.net/browse/ADVAPP-10
This PR adds service requests to the Student and Prospect holistic views.
=> [ADVAPP-10]: Add Service Requests to Holistic Prospect and Student Record

app-modules/meeting-center/src/Filament/Resources/CalendarEventResource.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php, app-modules/prospect/src/Observers/ProspectObserver.php, app-modules/prospect/src/Providers/ProspectServiceProvider.php, app-modules/prospect/tests/Prospect/CreateProspectTest.php, app/Filament/Pages/Events.php, app/Filament/Pages/ProductHealth.php, app/Filament/Pages/Reports.php, app/Providers/Filament/AdminPanelProvider.php
https://canyongbs.atlassian.net/browse/ADVAPP-94
https://canyongbs.atlassian.net/browse/ADVAPP-95
https://canyongbs.atlassian.net/browse/ADVAPP-96
https://canyongbs.atlassian.net/browse/ADVAPP-97
https://canyongbs.atlassian.net/browse/ADVAPP-99
https://canyongbs.atlassian.net/browse/ADVAPP-101
https://canyongbs.atlassian.net/browse/ADVAPP-103
Label changes and Prospect observer.
=> [ADVAPP-94-95-96-97-99-101-103]: Label changes and Prospect observer

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.38.0` branch.
- Checkout the `shift-ci-v10.38.0` branch
=> Laravel 10.38.0 Shift

app-modules/task/src/Enums/TaskStatus.php, app-modules/task/src/Filament/Concerns/TaskViewActionInfoList.php, app-modules/task/src/Filament/RelationManagers/BaseTaskRelationManager.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/CreateTask.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php, app/Livewire/TaskKanban.php, resources/views/livewire/task-kanban.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-90
- https://canyongbs.atlassian.net/browse/ADVAPP-91
- https://canyongbs.atlassian.net/browse/ADVAPP-92
- https://canyongbs.atlassian.net/browse/ADVAPP-93
As described in tickets.
=> [ADVAPP-90], [ADVAPP-91], [ADVAPP-92] & [ADVAPP-93]

composer.json, composer.lock
=> Change the php version to be 8.2 specifically

app-modules/alert/src/Observers/AlertObserver.php, app-modules/application/src/Observers/ApplicationSubmissionObserver.php, app-modules/form/src/Observers/FormSubmissionObserver.php, app-modules/in-app-communication/src/Filament/Pages/UserChat.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectApplicationSubmissions.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectFormSubmissions.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentAlerts.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentApplicationSubmissions.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentFormSubmissions.php, app-modules/timeline/tests/Listeners/AddRecordToTimelineTest.php, app-modules/timeline/tests/Listeners/RemoveRecordFromTimelineTest.php, config/database.php
- https://canyongbs.atlassian.net/browse/ADVAPP-109
Sets up the system to be able to use our new serverless Redis instance. All tags/keys for Redis/Cache do now need to be surrounded by `{}` to be hash-mapped. But other than that everything else is the same.
When this is deployed, we will need to edit Demos `.env` to uncomment, pointing Redis at the new instance.
=> [ADVAPP-17]: Update Demo to Use Authenticated Redis Instance

app-modules/form/src/Filament/Actions/RequestFormSubmission.php
- https://canyongbs.atlassian.net/browse/ADVAPP-110
Made sure expression was escaped.
=> [ADVAPP-110]: Form submission request query issue

composer.json, docs/api.md, routes/web.php, spectaql.yml
- N/A
This returns the API documentation via a Laravel route to allow for authentication. It also cleans up the generation command to only do what is needed to generate the documentation itself. Other commands have been noted in the docs.
=> API Docs Authentication

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.38.2` branch.
- Checkout the `shift-ci-v10.38.2` branch
=> Laravel 10.38.2 Shift

composer.json, composer.lock
- N/A
Updates to the newest version of the TipTap editor plugin, allowing us to get to a version without the edit loading bug that required us to lock versions.
=> Update to the new version of tiptap with fixes

app-modules/inventory-management/database/seeders/MaintenanceProviderSeeder.php, database/seeders/DatabaseSeeder.php, database/seeders/DemoDatabaseSeeder.php
n/a
This PR updates our local and demo seeders for assets
=> [Chore] Update seeders to better reflect environment

app-modules/authorization/src/Http/Middleware/RedirectIfPasswordNotSet.php, app/Http/Middleware/RedirectIfAuthenticated.php, composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.39.0` branch.
- Checkout the `shift-ci-v10.39.0` branch
=> Laravel 10.39.0 Shift

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php, app-modules/prospect/src/Models/Prospect.php
https://canyongbs.atlassian.net/browse/ADVAPP-189
Remove OpenSearch fields and filters for Prospects.
=> [ADVAPP-189]: Remove AWS Open Search for prospects

app-modules/survey/src/Filament/Blocks/CheckboxSurveyFieldBlock.php, app-modules/survey/src/Filament/Blocks/RadioSurveyFieldBlock.php, app-modules/survey/src/Filament/Blocks/SelectSurveyFieldBlock.php, app-modules/survey/src/Filament/Blocks/SurveyFieldBlockRegistry.php, app-modules/survey/src/Filament/Blocks/TextAreaSurveyFieldBlock.php, app-modules/survey/src/Filament/Blocks/TextInputSurveyFieldBlock.php, app-modules/survey/src/Filament/Resources/SurveyResource/Pages/Concerns/HasSharedFormConfiguration.php
https://canyongbs.atlassian.net/browse/ADVAPP-136
This PR removes some unnecessary blocks for survey building, and re-labels others to more appropriately represent the blocks in the survey context.
=> [ADVAPP-136]: Remove Unnecessary Blocks in Surveys

app-modules/assistant/src/Filament/Pages/ManageAiSettings.php, app-modules/assistant/src/Filament/Pages/PersonalAssistant.php, app-modules/assistant/src/Filament/Pages/PromptLibrary.php, app-modules/assistant/src/Models/AssistantChat.php, app-modules/assistant/src/Models/AssistantChatFolder.php, app-modules/assistant/src/Models/AssistantChatMessage.php, app-modules/assistant/src/Models/AssistantChatMessageLog.php, app-modules/assistant/src/Models/Concerns/CanAddAssistantLicenseGlobalScope.php, app-modules/assistant/src/Policies/AssistantChatMessageLogPolicy.php, app-modules/assistant/src/Services/AIInterface/DataTransferObjects/Chat.php, app-modules/assistant/tests/Feature/Filament/Pages/AIAssistantPageTest.php, app-modules/assistant/tests/Feature/Filament/Pages/AssistantConfigurationPageTest.php, app-modules/assistant/tests/Feature/Filament/Pages/ManageAiSettingsPageTest.php, app-modules/consent/src/Filament/Resources/ConsentAgreementResource/Pages/ListConsentAgreements.php, app-modules/consent/src/Policies/ConsentAgreementPolicy.php, app/Filament/Pages/ArtificialIntelligence.php, app/Filament/Pages/AssetManagement.php, app/Filament/Pages/Concerns/HasChildNavigationItemsOnly.php, app/Filament/Pages/GlobalSettings.php, app/Filament/Pages/InteractionManagement.php, app/Filament/Pages/KnowledgeManagement.php, app/Filament/Pages/OnlineAdmissions.php, app/Filament/Pages/ProductIntegrations.php, app/Filament/Pages/ProfileManagement.php, app/Filament/Pages/RecruitmentCrm.php, app/Filament/Pages/ServiceManagement.php, app/Filament/Pages/UsageAuditing.php
- https://canyongbs.atlassian.net/browse/ADVAPP-201
Also refactored child navigation recently introduced, due to issues with conditional nav registration and policy checks.
Please note: `Product Administration > Artificial Intelligence` currently is still visible, even if you do not have an AI license. This is due to an issue with the way sub navigation items have been implemented on this page, and also on the `EmailConfiguration` page. We can fix this when child/sub navigation is refactored.
=> [ADVAPP-201]: Introduce license enforcement for Artificial Intelligence

app-modules/interaction/src/Models/Interaction.php, app-modules/interaction/src/Policies/InteractionCampaignPolicy.php, app-modules/interaction/src/Policies/InteractionDriverPolicy.php, app-modules/interaction/src/Policies/InteractionOutcomePolicy.php, app-modules/interaction/src/Policies/InteractionPolicy.php, app-modules/interaction/src/Policies/InteractionRelationPolicy.php, app-modules/interaction/src/Policies/InteractionStatusPolicy.php, app-modules/interaction/src/Policies/InteractionTypePolicy.php, app-modules/interaction/tests/Filament/InteractionCampaignResource/EditInteractionCampaignTest.php, app-modules/interaction/tests/Filament/InteractionOutcomeResource/CreateInteractionOutcomeTest.php, app-modules/interaction/tests/Filament/InteractionRelationResource/CreateInteractionRelationTest.php, app-modules/interaction/tests/Filament/InteractionRelationResource/EditInteractionRelationTest.php, app-modules/interaction/tests/Filament/InteractionRelationResource/ListInteractionRelationsTest.php, app-modules/interaction/tests/Filament/InteractionResource/EditInteractionTest.php, app-modules/service-management/database/migrations/2023_09_05_144251_create_service_requests_table.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/CreateServiceRequest.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/EditServiceRequest.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/AssignedToRelationManager.php, app-modules/service-management/src/Policies/ServiceRequestPolicy.php, app-modules/service-management/tests/RequestFactories/CreateServiceRequestRequestFactory.php, app-modules/service-management/tests/ServiceRequest/CreateServiceRequestTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-210
-
=> [ADVAPP-210]: Update interaction license handling

app-modules/inventory-management/src/Filament/Actions/CheckInAssetHeaderAction.php, app-modules/inventory-management/src/Filament/Actions/CheckOutAssetHeaderAction.php, app-modules/inventory-management/src/Filament/Resources/AssetResource/Pages/ViewAsset.php, app-modules/inventory-management/src/Models/Asset.php, app-modules/inventory-management/src/Models/AssetStatus.php, app-modules/inventory-management/src/Models/Scopes/ClassifiedAs.php
https://canyongbs.atlassian.net/browse/ADVAPP-198
https://canyongbs.atlassian.net/browse/ADVAPP-211
This PR resolves a bug related to the display of the check out button under certain circumstances, as well as disabling it (instead of hiding it) when a check out is not appropriate.
=> [ADVAPP-211] & [ADVAPP-198]

app-modules/authorization/resources/views/filament/widgets/unlicensed-notice.blade.php, app-modules/authorization/src/AuthorizationPlugin.php, app-modules/authorization/src/Filament/Widgets/UnlicensedNotice.php, app/Filament/Pages/Dashboard.php, app/Filament/Widgets/WelcomeWidget.php
- https://canyongbs.atlassian.net/browse/ADVAPP-184
Adds new widget to dashboard that contains the notice.
=> [ADVAPP-184]: Unlicensed user should see a message on the dashboard that indicates they do not have an active license

app-modules/notification/src/Exceptions/NotificationQuotaExceeded.php, app-modules/notification/src/Notifications/Channels/EmailChannel.php, app-modules/notification/src/Notifications/Channels/SmsChannel.php, app-modules/notification/src/Notifications/SmsNotification.php, app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementsRelationManager.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php, composer.json, composer.lock, tests/Unit/ClientMock.php, tests/Unit/LicenseSettingsEmailQuotaTracking.php, tests/Unit/LicenseSettingsSmsQuotaTracking.php, tests/Unit/TestSmsNotification.php
- https://canyongbs.atlassian.net/browse/ADVAPP-2
Enforce License rules for SMS Notifications.
=> [ADVAPP-2]: Enforce License Rules for SMS

app-modules/survey/resources/views/blocks/previews/rating.blade.php, app-modules/survey/src/Filament/Blocks/RatingScaleSurveyFieldBlock.php, app-modules/survey/src/Filament/Blocks/SurveyFieldBlockRegistry.php, widgets/form/src/FormKit/theme.js, widgets/survey/src/FormKit/Inputs/Rating.vue
https://canyongbs.atlassian.net/browse/ADVAPP-133
Implemented rating scale survey question type.
=> [ADVAPP-133]: Implement Rating Scale Survey Question Type

app/Filament/Resources/UserResource.php, app/Forms/Components/Licenses.php
https://canyongbs.atlassian.net/browse/ADVAPP-221
Fixed User creation due to License Management.
=> [ADVAPP-221]: User create page throws an Exception

app/Filament/Pages/Dashboard.php
https://canyongbs.atlassian.net/browse/ADVAPP-224
This PR simply returns the welcome and license widget before evaluating permissions for others in the event that a user is unlicensed. 
=> [ADVAPP-224]: Refactor dashboard experience for unlicensed user.

app-modules/alert/src/Notifications/AlertCreatedNotification.php, app-modules/application/src/Notifications/AuthorLinkedApplicationSubmissionCreatedNotification.php, app-modules/form/src/Http/Middleware/EnsureFormsFeatureIsActive.php, app-modules/form/src/Notifications/AuthorLinkedFormSubmissionCreatedNotification.php, app-modules/notification/src/Listeners/NotifyUserOfSubscriptionCreated.php, app-modules/notification/src/Listeners/NotifyUserOfSubscriptionDeleted.php
- https://canyongbs.atlassian.net/browse/ADVAPP-214
-
=> [ADVAP-214]: Filament::getModelResource only returns null now

_ide_helper_models.php, app-modules/alert/src/Models/Alert.php, app-modules/caseload-management/src/Models/Caseload.php, app-modules/prospect/src/Filament/Pages/RecruitmentCrmDashboard.php, app-modules/prospect/src/Filament/Widgets/ProspectAlertCount.php, app-modules/prospect/src/Filament/Widgets/ProspectCaseloadCount.php, app-modules/prospect/src/Filament/Widgets/ProspectCount.php, app-modules/prospect/src/Filament/Widgets/ProspectSubscriptionCount.php, app-modules/prospect/src/Filament/Widgets/ProspectTasks.php, app-modules/prospect/src/ProspectPlugin.php, app-modules/student-data-model/src/Filament/Pages/RetentionCrmDashboard.php, app-modules/student-data-model/src/Filament/Widgets/StudentAlertCount.php, app-modules/student-data-model/src/Filament/Widgets/StudentCaseloadCount.php, app-modules/student-data-model/src/Filament/Widgets/StudentCount.php, app-modules/student-data-model/src/Filament/Widgets/StudentSubscriptionCount.php, app-modules/student-data-model/src/Filament/Widgets/StudentTasks.php, app-modules/student-data-model/src/StudentDataModelPlugin.php, app-modules/task/src/Enums/TaskStatus.php, app-modules/task/src/Filament/Resources/TaskResource/Components/TaskViewAction.php, app-modules/task/src/Filament/Widgets/TasksWidget.php, app-modules/task/src/Models/Task.php, app-modules/task/src/TaskPlugin.php, app/Filament/Widgets/ProspectGrowthChart.php, app/Livewire/TaskKanban.php, app/Models/User.php, resources/views/livewire/task-kanban.blade.php
https://canyongbs.atlassian.net/browse/ADVAPP-225
https://canyongbs.atlassian.net/browse/ADVAPP-226
Retention and Recruitment dashboards and widgets.
=> [ADVAPP-225]: Introduce Retention CRM Dashboard, [ADV-226]: Introduce Recruitment CRM Dashboard

composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-60
Updates Filament.
=> [ADVAPP-60]: Issue with seeded form blocks when using a primary color, identified by Matthew

app-modules/campaign/src/Actions/ExecuteCampaignActions.php
- https://canyongbs.atlassian.net/browse/ADVAPP-218
Fix issue with process running in kernel.
=> [ADVAPP-218]: Execute campaign action run by the scheduler is currently erroring

app/Filament/Pages/Dashboard.php
- https://canyongbs.atlassian.net/browse/ADVAPP-272
Changes the navigation label for the main Dashboard.
=> [ADVAPP-272]: Update the navigation label for the homepage. 

widgets/survey/src/FormKit/Inputs/index.js
- https://canyongbs.atlassian.net/browse/ADVAPP-270
Added missing input type to surverys.
=> [ADVAPP-270]: Authenticated student or prospect unable to enter authorization code

app-modules/authorization/src/Enums/SocialiteProvider.php, app-modules/authorization/src/Http/Controllers/SocialiteController.php, app-modules/meeting-center/src/Http/Controllers/GoogleCalendarController.php, app-modules/meeting-center/src/Http/Controllers/OutlookCalendarController.php
- https://canyongbs.atlassian.net/browse/ADVAPP-216
Changes Azure and Google oauth flows to prompt the User to select an account when going through the flow.
=> [ADVAPP-216]: Adjust Meeting Center calendar oAuth flow to require you select what account to use

app-modules/service-management/src/Filament/Resources/SlaResource.php, app/Filament/Clusters/ServiceManagement.php
- https://canyongbs.atlassian.net/browse/ADVAPP-268
Moves the SLA menu items to the Product Administration cluster for Service Management
=> [ADVAPP-268]: Relocate SLAs menu

_ide_helper_models.php, app-modules/in-app-communication/database/migrations/2023_11_14_164338_create_twilio_conversation_user_table.php, app-modules/in-app-communication/resources/js/userToUserChat.js, app-modules/in-app-communication/resources/views/filament/pages/user-chat.blade.php, app-modules/in-app-communication/resources/views/livewire/chat-notifications.blade.php, app-modules/in-app-communication/src/Actions/CheckConversationMessageContentForMention.php, app-modules/in-app-communication/src/Actions/ConvertMessageJsonToText.php, app-modules/in-app-communication/src/Enums/ConversationNotificationPreference.php, app-modules/in-app-communication/src/Events/ConversationMessageSent.php, app-modules/in-app-communication/src/Filament/Pages/UserChat.php, app-modules/in-app-communication/src/InAppCommunicationPlugin.php, app-modules/in-app-communication/src/Jobs/NotifyConversationParticipant.php, app-modules/in-app-communication/src/Jobs/NotifyConversationParticipants.php, app-modules/in-app-communication/src/Livewire/ChatNotifications.php, app-modules/in-app-communication/src/Models/TwilioConversation.php, app-modules/in-app-communication/src/Models/TwilioConversationUser.php, app/Models/Export.php, app/Models/User.php, resources/css/filament/admin/theme.css
- https://canyongbs.atlassian.net/browse/ADVAPP-284
=> [ADVAPP-284]: Add notifications for Realtime Chat

app-modules/in-app-communication/src/Livewire/ChatNotifications.php
- https://canyongbs.atlassian.net/browse/ADVAPP-
=> fix: Chat notifications query incorrect

app-modules/inventory-management/database/factories/AssetFactory.php, app-modules/inventory-management/database/factories/AssetStatusFactory.php, app-modules/inventory-management/database/seeders/AssetStatusSeeder.php, app-modules/inventory-management/src/Actions/UpdateAssetStatusBasedOnMaintenanceActivity.php, app-modules/inventory-management/src/Models/Asset.php, app-modules/inventory-management/tests/Actions/UpdateAssetStatusBasedOnMaintenanceActivityTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-271
This PR introduces coordination between maintenance activities on an asset and the status of the asset.
=> [ADVAPP-271]: Coordinate activities of maintenance activity with asset status

app-modules/form/src/Actions/GenerateFormKitSchema.php
- https://canyongbs.atlassian.net/browse/ADVAPP-338
Introduced in #417. Pass blocks to Grid content components.
=> [ADVAPP-338]: More complex forms throw 500

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.44.0` branch.
- Checkout the `shift-ci-v10.44.0` branch
=> Laravel 10.44.0 Shift

package-lock.json
- https://canyongbs.atlassian.net/browse/ADVAPP-336
=> [ADVAPP-336]: CVE-2020-8203 - Prototype Pollution in lodash

.github/pull_request_template.md
- N/A
Fixes a minor typo in the PR template.
>
=> Fix minor typo in PR template

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php
- https://canyongbs.atlassian.net/browse/ADVAPP-355
- https://canyongbs.atlassian.net/browse/ADVAPP-356
No
=> [ADVAPP-355] & [ADVAPP-356]: Organize the Display of Information for the Student / Prospect Record

app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalArticleController.php
- https://canyongbs.atlassian.net/browse/ADVAPP-340
Ensures that media is properly decoded before being output to the KB portal.
>
=> [ADVAPP-340]: Images uploaded into a KB article fail to present in the public KB articles.

app-modules/portal/src/DataTransferObjects/KnowledgeBaseCategoryData.php, app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalController.php, portals/knowledge-management/src/App.vue, portals/knowledge-management/src/Components/DesktopSidebar.vue, portals/knowledge-management/src/Components/HelpCenter.vue, portals/knowledge-management/src/Components/MobileSidebar.vue, portals/knowledge-management/src/Components/SidebarContent.vue
- https://canyongbs.atlassian.net/browse/ADVAPP-324
>
>
=> [ADVAPP-324]: Display knowledge base category icon in knowledge portal.

app-modules/knowledge-base/database/migrations/2023_03_06_000012_create_knowledge_base_articles_table.php, app-modules/knowledge-base/database/migrations/2023_03_06_000039_create_division_knowledge_base_item_pivot_table.php, app-modules/knowledge-base/database/migrations/2023_03_06_000041_add_relationship_fields_to_knowledge_base_items_table.php, app-modules/knowledge-base/graphql/knowledge-base-item.graphql, app-modules/knowledge-base/src/Models/KnowledgeBaseItem.php
- https://canyongbs.atlassian.net/browse/ADVAPP-366
>
Renamed `knowledge_base_items` table to `knowledge_base_articles`.
>
=> [ADVAPP-366]: Table name change for KnowledgeBaseItems to KnowledgeBaseArticles

_ide_helper_models.php, app-modules/alert/src/Enums/AlertStatus.php, app-modules/assistant/src/Jobs/ShareAssistantChatJob.php, app-modules/inventory-management/database/factories/MaintenanceActivityFactory.php, app-modules/inventory-management/src/Enums/MaintenanceActivityStatus.php, app-modules/meeting-center/src/Jobs/CreateEventAttendee.php, app-modules/task/src/Enums/TaskStatus.php, app-modules/task/src/Filament/Resources/TaskResource/Components/TaskViewAction.php, app/Console/Commands/GenerateHelperFiles.php
- https://canyongbs.atlassian.net/browse/ADVAPP-241
>
Replaced references of `cancelled` with `canceled`.
>
=> [ADVAPP-241]: Replace "cancelled" references with "canceled"

app-modules/integration-ai/src/Client/AzureOpenAI.php
- N/A
Quick bugfix to ensure the openai URL has the forward slash trimmed when used.
>
=> [BUGFIX] rtrim the openai URL

app-modules/integration-ai/database/migrations/2024_02_26_191606_fix_ai_prompt_system_context_setting.php, app-modules/integration-ai/src/Client/BaseAIChatClient.php, app/Models/User.php
- https://canyongbs.atlassian.net/browse/ADVAPP-387
>
Corrects the dynamic context missing from the `AssistantChatMessageLog`.
>
=> [ADVAPP-387]: AI name and job title context not working as expected.

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.46.0` branch.
- Checkout the `shift-ci-v10.46.0` branch
=> Laravel 10.46.0 Shift

app-modules/knowledge-base/database/migrations/2024_03_04_154518_create_knowledge_base_item_upvotes_table.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ViewKnowledgeBaseItem.php, app-modules/knowledge-base/src/Models/KnowledgeBaseItem.php, app-modules/knowledge-base/src/Models/KnowledgeBaseItemUpvote.php
- https://canyongbs.atlassian.net/browse/ADVAPP-346
Implemented the same as #575.
=> [ADVAPP-346]: Upvote knowledge base articles

composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-396
Fixed within Filament.
=> [ADVAPP-396]: Menu jump on navigate no longer works

.github/workflows/prerelease.yml
- https://canyongbs.atlassian.net/browse/ADVAPP-277
This adds the CD flow for deploying an image to ECR on prerelease. Start of the tests to get CI/CD fully functional.
>
=> [ADVAPP-277]: Prerelease CD

app-modules/data-migration/src/OneTimeOperation.php, config/one-time-operations.php, database/factories/TenantFactory.php, database/operations/2024_03_01_173404_update_all_tenants_mail_from_address.php, stubs/one-time-operation.stub, tests/Unit/Test2024_03_01_173404_update_all_tenants_mail_from_address.php
- https://canyongbs.atlassian.net/browse/ADVAPP-399
- Creates a data migration to fix the URL for tenants
- Fixes one time operations so that they will us the proper queue
`php artisan operations:process landlord` will need to be run manually after this is deployed. Since we do not yet have that running during deployment.
=> [ADVAPP-399]: SMTP currently broken for tenants in Production and Development

.github/workflows/prerelease.yml, .gitmodules
- https://canyongbs.atlassian.net/browse/ADVAPP-277
Setup to trigger a deployment to ECS by pulling in a populating a template from a submodule.
>
=> [ADVAPP-277]: CI/CD to support production releases | ECS Deployment Dev

app-modules/knowledge-base/database/migrations/2024_03_04_154518_create_knowledge_base_item_upvotes_table.php, app-modules/knowledge-base/database/migrations/2024_03_04_155253_create_knowledge_base_item_views_table.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ViewKnowledgeBaseItem.php, app-modules/knowledge-base/src/Models/KnowledgeBaseItem.php, app-modules/knowledge-base/src/Models/KnowledgeBaseItemUpvote.php, app-modules/knowledge-base/src/Models/KnowledgeBaseItemView.php
- https://canyongbs.atlassian.net/browse/ADVAPP-345
Rate limiter applied to the "view" page of the View Knowledge Base Item page for 1 attempt every minute. It only gets bumped when the page gets loaded and not when any Livewire update request gets made.
=> [ADVAPP-345]: Track views of knowledge base articles

.github/workflows/prerelease.yml, .gitmodules
- https://canyongbs.atlassian.net/browse/ADVAPP-277
Updates the submodule to point to the new repo for devops related items.
>
=> [ADVAPP-277]: CI/CD to support production releases | Update devops submodule

.github/workflows/prerelease.yml, .github/workflows/release.yml
- https://canyongbs.atlassian.net/browse/ADVAPP-277
Sets up the production release workflow.
>
=> [ADVAPP-277]: CI/CD to support production releases | Production Release

composer.json, composer.lock
- N/A
Updates the devops submodule, which contains deployment script fixes.
>
=> Update devops submodule

config/auth.php
- N/A
Change the `api` guard driver to `session` as `token` causes issues.
>
=> Change the api driver to session

app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
Update the label for the insertFromPromptLibrary action
- https://canyongbs.atlassian.net/browse/ADVAPP-411
Updates the label for the `insertFromPromptLibrary` action.
>
=> [ADVAPP-411]: Modify Button Label for Prompt Library

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php
- https://canyongbs.atlassian.net/browse/ADVAPP-391
Presentational changes as described. Future merge conflicts when #590 and #591 are merged.
=> [ADVAPP-391]: Enhance Create Prospect experience by auto generating full name.

composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-418
=> [ADVAPP-418]: Resolve Prototype Pollution XSS issue

database/operations/2024_03_12_135601_activate_interaction_defaults_feature_flag.php
- N/A
Fixes the tag for one time operation.
>
=> Fix one time operation

app-modules/team/src/Policies/TeamPolicy.php
n/a
> Fix some incorrect text
> No
=> Fix model name reference in policy.

app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php, app-modules/report/resources/views/filament/pages/report-assistant.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-340
=> [ADVAPP-340]: Enhance AI by updating label for for button.

app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php, app-modules/report/resources/views/filament/pages/report-assistant.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-429
Textarea will expand from 5rem to 35dvh based on the content. Reset back to 5rem when a message is sent. Can expand and contract again when lines deleted, not just expand.
https://github.com/canyongbs/advisingapp/assets/41773797/48fddb7a-dd2c-425d-9400-34f52f3b5120
=> [ADVAPP-429]: Enhance AI experience by making prompt area expandable for larger when needed.

Dockerfile
- N/A
A quick fix to resolve permission issues that causes errors to be thrown in dev/prod
>
=> Fix build permissions

resources/css/filament/admin/theme.css
- https://canyongbs.atlassian.net/browse/ADVAPP-410
=> [ADVAPP-410]: Invert heading colors presenting in main navigation

app-modules/assistant/database/migrations/2024_03_26_143921_add_user_id_column_to_prompts_table.php, app-modules/assistant/database/migrations/2024_03_26_150742_data_activate_prompt_user_feature.php, app-modules/assistant/resources/views/filament/pages/personal-assistant/prompt-option.blade.php, app-modules/assistant/src/Filament/Pages/PersonalAssistant.php, app-modules/assistant/src/Models/Prompt.php, app-modules/assistant/src/Observers/PromptObserver.php, app-modules/assistant/src/Providers/AssistantServiceProvider.php, app-modules/assistant/tests/Feature/Filament/Resources/PromptResource/EditPromptTest.php, app-modules/assistant/tests/Feature/Filament/Resources/PromptResource/ViewPromptTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-450
- https://canyongbs.atlassian.net/browse/ADVAPP-451
- https://canyongbs.atlassian.net/browse/ADVAPP-452
=> [ADVAPP-450], [ADVAPP-451] & [ADVAPP-452]: Prompt selection improvements

app/Http/Controllers/Tenants/CreateTenantController.php, app/Http/Controllers/Tenants/DeleteTenantController.php
- https://canyongbs.atlassian.net/browse/OLYMPUS-17
Pairs with https://github.com/canyongbs/olympus/pull/16.
=> [OLYMPUS-17]: Delete New Tenant on Advising App Dev

docker/s6-overlay/s6-rc.d/nginx/data/check
- N/A
Hotfix the change the nginx check to get the last status code. Which should fix production deployment issues.
>
=> Updates the nginx check to grab the last status code

.env.example
- N/A
This new configuration should work to use real s3 buckets for local/remote development.
>
=> Update the .env.example for info on using the s3 bucks

app-modules/portal/database/migrations/2024_04_03_144133_delete_has_service_management_portal_setting.php, app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
- https://canyongbs.atlassian.net/browse/ADVAPP-432
Removed refs to the settings property and created a migration to drop it from the database.
=> [ADVAPP-432]: Update portal configuration

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectApplicationSubmissions.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectFormSubmissions.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ProspectServiceManagement.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentApplicationSubmissions.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentFormSubmissions.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/StudentServiceManagement.php
- https://canyongbs.atlassian.net/browse/ADVAPP-467
- https://canyongbs.atlassian.net/browse/ADVAPP-468
- https://canyongbs.atlassian.net/browse/ADVAPP-469
Updates features on Student and Prospect view to display or not display based on feature activation.
>
=> [ADVAPP-467], [ADVAPP-468], and [ADVAPP-469]

app-modules/authorization/src/Console/Commands/SetupPermissions.php, app-modules/authorization/src/Console/Commands/SetupRoles.php, app-modules/authorization/src/Console/Commands/SyncRolesAndPermissions.php, app-modules/campaign/src/Console/Commands/ExecuteCampaignActions.php, app-modules/caseload-management/src/Console/Commands/TranslateCaseload.php, app-modules/engagement/src/Console/Commands/DeliverEngagements.php, app-modules/meeting-center/src/Console/Commands/CreateEvent.php, app-modules/meeting-center/src/Console/Commands/DeleteEvent.php, app-modules/meeting-center/src/Console/Commands/RefreshCalendarRefreshTokens.php, app-modules/meeting-center/src/Console/Commands/SyncEvents.php, app-modules/meeting-center/src/Console/Commands/UpdateEvent.php, app-modules/notification/src/Console/Commands/SimulatedNotification.php, app/Console/Commands/BuildAssets.php, app/Console/Commands/ClearTestMigrationCache.php, app/Console/Commands/ConnectOlympus.php, app/Console/Commands/CreateSuperAdmin.php, app/Console/Commands/CreateTenant.php, app/Console/Commands/GenerateHelperFiles.php, app/Console/Commands/InitialMigration.php, app/Console/Commands/MigrateFreshLandlord.php, app/Console/Commands/MigrateLandlord.php, app/Console/Commands/OpenSearchDeleteAllIndices.php, app/Console/Commands/OpenSearchList.php, app/Console/Commands/PrintApiSchema.php, app/Console/Commands/ValidateGraphQL.php
- https://canyongbs.atlassian.net/browse/ADVAPP-353
=> [ADVAPP-353]: Ensure all commands return static::SUCCESS or static::FAILURE

docker/s6-overlay/s6-rc.d/generate-api-docs/dependencies, docker/s6-overlay/s6-rc.d/generate-api-docs/type, docker/s6-overlay/s6-rc.d/generate-api-docs/up, docker/s6-overlay/scripts/generate-api-docs, package-lock.json, package.json
- https://canyongbs.atlassian.net/browse/ADVAPP-466
Generates the API docs during container startup so that api-docs work in dev and prod.
>
=> [ADVAPP-466]: API docs link produces an error

app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
- https://canyongbs.atlassian.net/browse/ADVAPP-495
Fixes issue with prompt access since we added the user filter.
>
=> [ADVAPP-495]: Regression for inserting prompt from prompt library

app/Jobs/CreateTenantUser.php
When creating a tenant from Olympus, it should have the super admin role so it can manage the app.
=> fix: Create tenant as super admin

Dockerfile, docker/s6-overlay/scripts/initial-migration, docker/s6-overlay/scripts/laravel-migrate, docker/s6-overlay/scripts/laravel-octane
- https://canyongbs.atlassian.net/browse/ADVAPP-431
Updates all s6-overlay tasks to properly run dynamically as the `webuser`. This fixes Octane to run as `webuser` as well, so we fix the security issue of running the container as root.
We also now define the `USER` at the end of the `Dockerfile` as the `webuser` so we prevent it running as root from then on.
>
=> [ADVAPP-431]: Fix file permission issues in docker containers

app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
n/a
> Adjust the Run timeout to allow the AI a longer period to respond.
> No
=> [HOTFIX] Adjust Run Timeout

Dockerfile
- N/A
Removes defining the User as webuser
>
=> Remove changing the User

app-modules/authorization/tests/Feature/Filament/Resources/User/Actions/AssignLicensesBulkActionTest.php, app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php, app/Filament/Resources/UserResource.php, app/Filament/Resources/UserResource/Actions/AssignLicensesBulkAction.php, app/Models/User.php
- https://canyongbs.atlassian.net/browse/ADVAPP-483
>
Added a new bulk assign licenses action to the users list. Allows assigning multiple licenses to multiple users simultaneously or replacing their existing assignments. 
>
=> [ADVAPP-483]: Introduce new users list view bulk license assign operation

app/Filament/Pages/ManageLicenseSettings.php
- https://canyongbs.atlassian.net/browse/ADVAPP-478
> Rename the Add-ons to Enabled features.
=> Rename the add-ons to enabled features

_ide_helper_models.php, app/Console/Kernel.php, app/Exceptions/Handler.php, composer.json, composer.lock, config/sentry.php
- https://canyongbs.atlassian.net/browse/ADVAPP-458
Installs and sets up Sentry for AdvisingApp Dev and Prod.
>
=> [ADVAPP-458]: Install and set up Sentry

app-modules/student-data-model/database/factories/EnrollmentFactory.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EnrollmentsRelationManager.php, app-modules/student-data-model/src/Models/Enrollment.php, app/Console/Commands/CreateTenant.php, database/migrations/2024_04_05_172134_add_additional_columns_to_enrollments_table.php, database/migrations/2024_04_05_214332_data_active_new_enrollments_columns_feature.php, database/seeders/StudentSeeder.php
- https://canyongbs.atlassian.net/browse/ADVAPP-494
Adds additional columns to the Enrollments table.
>
=> [ADVAPP-494]: Enhance Enrollments model with additional fields

app-modules/authorization/src/Filament/Resources/PermissionResource.php, app-modules/authorization/src/Filament/Resources/RoleResource.php, app-modules/division/src/Filament/Resources/DivisionResource.php, app-modules/team/src/Filament/Resources/TeamResource.php, app/Filament/Clusters/UserManagement.php, app/Filament/Resources/SystemUserResource.php, app/Filament/Resources/UserResource.php, app/Providers/Filament/AdminPanelProvider.php
- https://canyongbs.atlassian.net/browse/ADVAPP-473
> Moved User & Permissions to Product Administration and Renamed it to "User Management". 
=> [ADVAPP-473]: Update Navigation Experience for Users and Permissions

app-modules/consent/database/seeders/ConsentAgreementSeeder.php
- https://canyongbs.atlassian.net/browse/ADVAPP-497
=> [ADVAPP-497]: Introduce template acceptable use policy for colleges upon tenant creation

app-modules/assistant/src/Filament/Pages/PersonalAssistant.php, app-modules/assistant/src/Services/AIInterface/DataTransferObjects/ChatMessage.php, app-modules/assistant/tests/Feature/Filament/Pages/AIAssistantPageTest.php, composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-367
> This PR preserves the initial message creation time in the ChatMessage DTO, so that the chat message order is correct upon saving.
> No
=> [ADVAPP-367]: AI chat history sometimes presents out of order

app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EnrollmentsRelationManager.php, database/migrations/2024_04_05_214333_data_clean_up_new_enrollments_columns_feature.php
- https://canyongbs.atlassian.net/browse/ADVAPP-500
Purges the feature flag only.
=> [ADVAPP-500]: [Cleanup] ADVAPP-494 new-enrollments-columns

app-modules/assistant/tests/Feature/Filament/Pages/AIAssistantPageTest.php
n/a
> Resolves an issue with AI tests intermittently failing because of timestamp precision.
> No
=> [Bugfix] Intermittent AI Test Failure

app/Console/Commands/CreateTenant.php, config/app.php, tests/Feature/Multitenancy/Actions/CreateTenantTest.php, tests/Feature/Multitenancy/Http/Middleware/NeedsTenantTest.php, tests/Feature/Multitenancy/LandlordTest.php, tests/Feature/Multitenancy/Tasks/PrefixeCacheTaskTest.php, tests/Feature/Multitenancy/Tasks/SwitchAppKeyTest.php, tests/Feature/Multitenancy/Tasks/SwitchAppNameTest.php, tests/Feature/Multitenancy/Tasks/SwitchAppUrlTest.php, tests/Feature/Multitenancy/Tasks/SwitchMailTaskTest.php, tests/Feature/Multitenancy/Tasks/SwitchS3FilesystemTaskTest.php, tests/Feature/Multitenancy/Tasks/SwitchS3PublicFilesystemTaskTest.php, tests/Feature/Multitenancy/Tasks/SwitchTenantDatabasesTaskTest.php, tests/TestCase.php
- https://canyongbs.atlassian.net/browse/ADVAPP-262
>
Some initial tests for multitenancy.
>
=> [ADVAPP-262]: Write unit tests to Ensure all Tenancy switches happen as we would expect

app-modules/meeting-center/src/Filament/Resources/CalendarEventResource.php
[ADVAPP-509] Update Navigation Placement for Schedule & Appointment Features
- https://canyongbs.atlassian.net/browse/ADVAPP-509
> Moved Schedule & Appointment features in main navigation from Engagement Features to Premium Features.
[ADVAPP-509]: https://canyongbs.atlassian.net/browse/ADVAPP-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ADVAPP-509] Update Navigation Placement for Schedule & Appointment Features

app-modules/form/src/Actions/InjectSubmissionStateIntoTipTapContent.php, app-modules/form/src/Filament/Blocks/EducatableEmailFormFieldBlock.php, app-modules/survey/resources/views/blocks/previews/checkbox-list.blade.php, app-modules/survey/resources/views/blocks/submissions/checkbox-list.blade.php, app-modules/survey/src/Filament/Blocks/MultipleCheckboxSurveyFieldBlock.php, app-modules/survey/src/Filament/Blocks/SurveyFieldBlockRegistry.php, app-modules/survey/src/Models/SurveyFieldSubmission.php, app-modules/survey/src/Models/SurveySubmission.php
- https://canyongbs.atlassian.net/browse/ADVAPP-519
>
Introduced a basic multiple choice survey block.
>
=> [ADVAPP-519]: Surveys multiple choice question type only allows one choice

resources/views/vendor/filament-panels/resources/relation-manager.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-536
>
A workaround to handle a change introduced in the tiptap plugin. I'm going to submit an issue with the maintainers to try to come up with a proper fix.
>
=> [ADVAPP-536]: Unable to insert email template.

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentCareTeam.php
- https://canyongbs.atlassian.net/browse/ADVAPP-535
>
Added user job title to the educatable care team relationship tables.
>
=> [ADVAPP-535]: Add user job title to care team presentation.

app-modules/engagement/src/Filament/Resources/EngagementFileResource/RelationManagers/EngagementFilesRelationManager.php
- https://canyongbs.atlassian.net/browse/ADVAPP-551
> Added download action in Student -> View Student -> Files & Document Section.
=> [ADVAPP-551] Introduce inline "Download" action for uploaded files and documents

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseArticleResource/Pages/EditKnowledgeBaseArticle.php
- https://canyongbs.atlassian.net/browse/ADVAPP-546
> Rename 'Edit Article Metadata' to 'Edit Article Properties' in header actions under Knowledge base when edit any Knowledge Management Base Item.
=> [ADVAPP-546] Rename article metadata

app-modules/prospect/src/Filament/Widgets/ProspectStats.php
- https://canyongbs.atlassian.net/browse/ADVAPP-533
> Rename the headings of cards under Recruitment CRM Dashboard.
=> [AIDAPP-533] Update recruitment dashboard headings

app-modules/task/src/Histories/TaskHistory.php, app-modules/timeline/database/migrations/2024_05_06_182651_data_purge_educatable_alerts_timeline_feature_flag.php, app-modules/timeline/src/Models/Concerns/InteractsWithHistory.php
- https://canyongbs.atlassian.net/browse/ADVAPP-503
>
Clean up `educatable-alerts-timeline` feature flag.
>
=> [ADVAPP-503]: Clean up "educatable-alerts-timeline" feature flag

app-modules/campaign/src/Filament/Blocks/EngagementBatchBlock.php, app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php, app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/CreateEmailTemplate.php, app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Fields/EngagementSmsBodyField.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php, app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/CreateSmsTemplate.php, app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/EditSmsTemplate.php, app-modules/engagement/src/Models/Engagement.php, app-modules/form/src/Filament/Resources/FormResource/Pages/ManageFormEmailAutoReply.php, app-modules/form/src/Models/FormEmailAutoReply.php, app-modules/prospect/src/Models/Prospect.php, app-modules/student-data-model/src/Models/Student.php
- https://canyongbs.atlassian.net/browse/ADVAPP-538
> Added student firstname, lastname in merge value section in email,sms, bulk messaging.
=> [ADVAPP-538] Add merge values for first name and last name

config/octane.php
- N/A
Removes garbage collection for Octane as it does not seem to be needed right now and results in slowdowns and masking of memory leaks.
Also updates DevOps to contain resource increases.
>
=> Octane and Resource increases

app-modules/engagement/src/Filament/Resources/EngagementFileResource/RelationManagers/EngagementFilesRelationManager.php, app-modules/student-data-model/src/Models/Student.php
- https://canyongbs.atlassian.net/browse/ADVAPP-560
> Added icon & tooltip in File and documents under Student/Prospect.
=> [ADVAPP-560] Enhance the icon display for mime types under files and documents

.env.example, Dockerfile, app/Console/Commands/ConnectOlympus.php, app/Multitenancy/Tasks/SwitchBindings.php, app/Providers/AppServiceProvider.php, app/Providers/RouteServiceProvider.php, config/app.php, config/multitenancy.php, docker-compose.dev.yml, docker-compose.prod.yml, docker-compose.yml, docs/local-setup.md
- N/A
Fixes the Dockerfile so that the build works correctly if there are not log files yet.
Changes the dev container name to match other projects and better connect to Olympus.
>
=> [Hotfix] Fix Dockerfile and dev container name

portals/knowledge-management/src/App.vue, portals/knowledge-management/src/Components/DesktopSidebar.vue, portals/knowledge-management/src/Pages/Home.vue
- https://canyongbs.atlassian.net/browse/ADVAPP-562
> Fixes navbar styling issue on portal embed.
https://github.com/canyongbs/advisingapp/assets/10821263/d190a55d-ac59-4759-8439-f61ad2e03ad5
> No
=> [ADVAPP-562]: Regression - Embed issue with navigation bar

app/Filament/Resources/UserResource.php
- https://canyongbs.atlassian.net/browse/ADVAPP-585
>Add default sort for users to be by name in ascending order in product user listing.
>
=> ADVAPP-585-Enhance the default sort for users to be by name

app-modules/ai/src/Console/Commands/ReInitializeAiThreads.php, app-modules/ai/src/Jobs/ReInitializeAiThread.php
=> Recreate AI thread command

app/Filament/Resources/UserResource.php
- https://canyongbs.atlassian.net/browse/ADVAPP-586
>Make job title and email toggleable in product user table.
=> Make job title and email toggleable in product user table

app/Filament/Resources/UserResource/Pages/CreateUser.php, app/Filament/Resources/UserResource/Pages/EditUser.php, app/Filament/Resources/UserResource/Pages/ViewUser.php
- https://canyongbs.atlassian.net/browse/ADVAPP-580
>Update label for Create User login via social provider in create user, edit user and view user pages .
>
=> [ADVAPP-580]: Update label for Create User login via social provider

app/Multitenancy/Tasks/SwitchS3FilesystemTask.php, app/Multitenancy/Tasks/SwitchS3PublicFilesystemTask.php
- N/A
Prevents file storage issues by wiping the Storage facade between Tenant switches.
>
=> [Bugfix] Reset the Storage Facade on change

app-modules/ai/resources/views/components/assistant.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-612
>Change label New chat with assistant to Use Custom Assistant. 
>
=> ADVAPP-612 Improve label for Custom AI Assistant usage

app-modules/ai/resources/js/chat.js, app-modules/ai/resources/views/components/assistant.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-611
> Update the chat buttons style for portrait mode. Updated the chat container height in landscape mode for device like iPhone SE.
Portrait mode :
Landscape mode :
=> [ADVAPP-611] Regression: Mobile view fails to display correctly for AI Assistant

app-modules/ai/resources/views/components/assistant.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-592
> Removed the classes "h-screen max-h-[calc(100dvh-20rem)]" that creating issue for sticky footer in assistant page.
=> [ADVAPP-592] Footer sticky issue fix in assistant page

app-modules/ai/resources/views/components/assistant.blade.php, tailwind.config.js
- https://canyongbs.atlassian.net/browse/ADVAPP-615
> Decrease prominence of AI Assistant badge. for that I have add xxs size to the extend section under theme.fontSize in tailwind config file.
>
=> ADVAPP-615 Decrease prominence of AI Assistant badge

app-modules/ai/resources/js/chat.js, app-modules/ai/resources/views/components/assistant.blade.php, app-modules/ai/src/Http/Requests/SendMessageRequest.php
- N/A
Contains previously approved changes that went out in `1.12.1-PRERELEASE` and `1.12.1`.
>
=> [Hotfix] 1.12.1 Hotfix

app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php, app-modules/integration-aws-ses-event-handling/tests/Feature/Filament/Pages/ManageAmazonSesSettingsTest.php, app/Filament/Pages/AmazonS3.php, database/migrations/2024_05_07_143413_seed_permissions_add_manage_s3_settings.php, resources/views/filament/pages/amazon-s3.blade.php, tests/Feature/Filament/Pages/AmazonS3Test.php
- https://canyongbs.atlassian.net/browse/ADVAPP-486
Setups up the ability to modify S3 and additional SES settings for a Tenant within Global settings. Adds tests to ensure they display and work properly and that they are properly protected by access control.
>
=> [ADVAPP-486]: Ensure storage settings are correct for Tenants

app-modules/ai/src/Filament/Pages/ManageAiSettings.php
…ngs and configurability
- https://canyongbs.atlassian.net/browse/ADVAPP-614
>Make changes as required in task description.
>
=> [ADVAPP-614]:Enhance the description of artificial intelligence settings and configurability

app-modules/prospect/src/Filament/Resources/ProspectSourceResource.php, app-modules/prospect/src/Filament/Resources/ProspectStatusResource.php, app/Filament/Clusters/ConstituentManagement.php, app/Filament/Clusters/ProspectManagement.php
- https://canyongbs.atlassian.net/browse/ADVAPP-623
> As per our discussion, I renamed cluster file.
>
=> [ADVAPP-623]:Update Label for Product Administration > Prospect Management to Constituent Management

app-modules/prospect/src/Filament/Resources/ProspectSourceResource.php, app-modules/prospect/src/Filament/Resources/ProspectStatusResource.php
…er Constituent Management
- https://canyongbs.atlassian.net/browse/ADVAPP-624
> Add grouping as required.
>
=> [ADVAPP-624]: Create an internal grouping for Prospect Management under Constituent Management

app-modules/ai/resources/js/chat.js, app-modules/ai/resources/views/components/assistant.blade.php, app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php, app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php, app-modules/report/resources/views/filament/pages/report-assistant.blade.php, resources/views/components/footer.blade.php, resources/views/filament/footer.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-589
- https://canyongbs.atlassian.net/browse/ADVAPP-592
- https://canyongbs.atlassian.net/browse/ADVAPP-611
Replaces #766. Replaces #769. Replaces #775.
Restructures the view to be full height and ensure the page never scrolls. Moves threads sidebar to dropdown on mobile to make space for chat. Makes footer minimal on mobile.
=> [ADVAPP-589]: Enhance the UI/UX for unfiled and filed chats using folders in the AI Personal Assistant

app-modules/report/src/Filament/Resources/ReportResource.php, app-modules/report/src/Filament/Resources/ReportResource/Pages/CreateReport.php, app-modules/report/src/Filament/Resources/ReportResource/Pages/ListReports.php
- https://canyongbs.atlassian.net/browse/ADVAPP-622
> Update label for Report Center to Custom Reports as well as in breadcrumb.
=> [ADVAPP-622]: Update label for Report Center to Custom Reports

app-modules/ai/src/Enums/AiApplication.php, app-modules/report/database/migrations/2024_06_05_110340_seed_permissions_add_report_library.php, app-modules/report/src/Filament/Pages/ReportLibrary.php
- https://canyongbs.atlassian.net/browse/ADVAPP-621
> Introduce Report Library coming soon page under Reporting.
=> [ADVAPP-621]: Introduce Report Library coming soon page under Reporting

app/Filament/Pages/EditProfile.php
- https://canyongbs.atlassian.net/browse/ADVAPP-645
> Change label for Edit Profile page to Profile Settings
=> [ADVAPP-645]: Change label for Edit Profile page to Profile Settings

app/Providers/Filament/AdminPanelProvider.php
- https://canyongbs.atlassian.net/browse/ADVAPP-646
> Enhance the dropdown menu for profile information to follow this order:
a. Icon Name
b. Mode Options
c. Profile Settings
d. Log Out
Please find the attachment below for reference:
=> [ADVAPP-646]: Enhance the dropdown menu for profile information with an explicit Profile Settings link

app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
…o describe subscriptions, alerts, and caseloads
- https://canyongbs.atlassian.net/browse/ADVAPP-640
>
>
=> [ADVAPP-640]: Update language used in Retention CRM dashboard cards to describe subscriptions, alerts, and caseloads

app-modules/ai/resources/views/components/assistant.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-617
=> [ADVAPP-617]: When using the AI Personal Assistant, the carriage return automatically sends message

app-modules/ai/src/Filament/Pages/ManageAiSettings.php, app-modules/integration-open-ai/composer.json, app-modules/integration-open-ai/src/Services/BaseOpenAiService.php, app-modules/integration-open-ai/src/Services/OpenAiGpt35Service.php, app-modules/integration-open-ai/src/Services/OpenAiGpt4Service.php, app-modules/integration-open-ai/src/Services/OpenAiGpt4oService.php, app/Filament/Forms/Components/Slider.php, composer.lock, resources/views/filament/forms/components/slider.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-642
Introduces a new slider field for setting the temp. Passes the temp and max completion length to new runs. Improves the timeout behaviour to calculate a dynamic timeout based on the current request duration.
Update .env to new API version:
```
OPEN_AI_GPT_35_API_VERSION=2024-05-01-preview
OPEN_AI_GPT_4_API_VERSION=2024-05-01-preview
OPEN_AI_GPT_4O_API_VERSION=2024-05-01-preview
```
=> [ADVAPP-642]: Update Institutional Assistant configuration for Creativeness and Response Length.

app/Http/Controllers/Tenants/CreateTenantController.php, app/Http/Controllers/Tenants/SyncTenantController.php, app/Http/Requests/Tenants/SyncTenantRequest.php
https://canyongbs.atlassian.net/browse/OLYMPUS-49
> Adds support for syncing subscription information
Corresponding Olympus PR: https://github.com/canyongbs/olympus/pull/45
> No
=> [OLYMPUS-49]: Add Subscription Information to the Subscriptions (formerly Application Plans)

composer.lock
Fixes:
- Student and prospect query builders
- Dynamic caseload creation
- Campaign actions
Due to the Builder component being broken in the Filament version we currently have installed.
=> hotfix: Filament builders broken

composer.lock
- N/A
Hotfix for Filament builders issues.
>
=> [Hotfix]: filament builders

app-modules/ai/resources/js/chat.js, app-modules/ai/src/Actions/RetryMessage.php, app-modules/ai/src/Actions/SendMessage.php, app-modules/ai/src/Http/Controllers/RetryMessageController.php, app-modules/ai/src/Http/Controllers/SendMessageController.php, app-modules/ai/src/Services/Contracts/AiService.php, app-modules/ai/src/Services/TestAiService.php, app-modules/ai/tests/Feature/Actions/RetryMessageTest.php, app-modules/ai/tests/Feature/Actions/SendMessageTest.php, app-modules/ai/tests/Feature/Http/Controllers/RetryMessageControllerTest.php, app-modules/ai/tests/Feature/Http/Controllers/SendMessageControllerTest.php, app-modules/integration-open-ai/src/Services/BaseOpenAiService.php, app-modules/integration-open-ai/tests/Feature/Services/OpenAiGptTestServiceTest.php, composer.json, composer.lock, overrides/Laravel/Octane/RoadRunner/RoadRunnerClient.php, overrides/OpenAI/Responses/Threads/Runs/ThreadRunResponse.php, package-lock.json, package.json
- https://canyongbs.atlassian.net/browse/ADVAPP-654
Utilizes a generator approach to return a streamed response from Octane.
=> [ADVAPP-654]: CLONE - Reintroduce streamed responses for AI Assistant

app-modules/ai/resources/views/components/assistant.blade.php, app/Providers/AppServiceProvider.php
- N/A
Applies the current commit has as a version to the assistant assets.
>
=> [Hotfix]: Version assistant assets

app-modules/ai/resources/js/chat.js, app-modules/ai/resources/views/components/assistant.blade.php, app-modules/ai/src/Actions/RetryMessage.php, app-modules/ai/src/Actions/SendMessage.php, app-modules/ai/src/Http/Controllers/RetryMessageController.php, app-modules/ai/src/Http/Controllers/SendMessageController.php, app-modules/ai/src/Services/Contracts/AiService.php, app-modules/ai/src/Services/TestAiService.php, app-modules/ai/tests/Feature/Actions/RetryMessageTest.php, app-modules/ai/tests/Feature/Actions/SendMessageTest.php, app-modules/ai/tests/Feature/Http/Controllers/RetryMessageControllerTest.php, app-modules/ai/tests/Feature/Http/Controllers/SendMessageControllerTest.php, app-modules/engagement/resources/views/components/message-center-content.blade.php, app-modules/integration-open-ai/src/Services/BaseOpenAiService.php, app-modules/integration-open-ai/tests/Feature/Services/OpenAiGptTestServiceTest.php, app/Providers/AppServiceProvider.php, composer.json, composer.lock, overrides/Laravel/Octane/RoadRunner/RoadRunnerClient.php, overrides/OpenAI/Responses/Threads/Runs/ThreadRunResponse.php, package-lock.json, package.json
- N/A
Contains fixes for asset versioning.
>
=> [Hotfix]: 1.14.3

app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php, app-modules/engagement/src/Actions/GenerateEngagementBodyContent.php, app-modules/engagement/src/Filament/Concerns/EngagementInfolist.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/ViewEngagement.php, app-modules/engagement/src/Models/Engagement.php, app-modules/engagement/src/Notifications/EngagementEmailNotification.php, app-modules/engagement/src/Notifications/EngagementSmsNotification.php, app-modules/form/src/Models/FormEmailAutoReply.php, app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementsRelationManager.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
- https://canyongbs.atlassian.net/browse/ADVAPP-659
Fixes some rendering issues with engagements when inserting images with titles. 
=> [ADVAPP-659]: Retention/Recruitment CRM emails fail to properly deliver embedded images

app-modules/report/src/Filament/Pages/ReportAssistant.php, app-modules/report/src/Filament/Pages/ReportLibrary.php, app-modules/report/src/Filament/Resources/ReportResource.php, app/Filament/Clusters/UsageAuditing.php, app/Filament/Pages/ProductHealth.php
- https://canyongbs.atlassian.net/browse/ADVAPP-663
> Set below order in Reporting navigation:
1. Report Library
2. Usage Auditing
3. Product Health
4. Custom Reports
5. Report Assistant
=> [ADVAPP-663]: Enhance the order of Reporting navigation in the application

app-modules/engagement/src/Notifications/EngagementFailedNotification.php
- https://canyongbs.atlassian.net/browse/ADVAPP-665
> Add notification type in notification when email is failed.
=> [ADVAPP-665]: enhance failure engagements notifications

app-modules/prospect/src/Filament/Resources/ProspectResource.php, app-modules/student-data-model/src/Filament/Resources/StudentResource.php, app/Filament/Resources/Concerns/HasGlobalSearchResultScoring.php
- https://canyongbs.atlassian.net/browse/ADVAPP-629
Introduces scoring to order results based on how they match common attributes, to the student and prospect resources.
Exact matches score 100% of the maximum score, matches at the start of the search term score 66% and matches that contain the search term anywhere score 33%. Different attributes have different maximum scores.
=> [ADVAPP-629]: Global search produces different results based on capitalization

app-modules/ai/database/migrations/2024_06_24_211022_data_change_default_name_description_for_default_personal_assistant.php, app-modules/ai/src/Actions/CreateThread.php, app-modules/ai/src/Exceptions/DefaultAssistantLockedPropertyException.php, app-modules/ai/src/Filament/Pages/ManageAiSettings.php, app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php, app-modules/ai/src/Models/AiAssistant.php, app-modules/ai/src/Observers/AiAssistantObserver.php
- https://canyongbs.atlassian.net/browse/ADVAPP-683
Revised Institutional Assistant settings and defaults.
=> [ADVAPP-683]: Revise Institutional Assistant Settings

app-modules/engagement/resources/views/components/message-center-content.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-685
> Improve language used to send an email or text from within the Message Center
=> [ADVAPP-685]: Improve language used to send an email or text from within the Message Center

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseArticleResource/Pages/ListKnowledgeBaseArticles.php, app/Support/MediaEncoding/TiptapMediaEncoder.php
- https://canyongbs.atlassian.net/browse/ADVAPP-658
> Add cloning feature for knowledge base articles.
=> [ADVAPP-658]: Introduce ability to duplicate knowledge base articles

database/migrations/2024_06_10_164958_data_update_existing_assistants_to_use_file_search_tool.php
=> [Bugfix]: Wrap adding file_upload in a try catch

app-modules/ai/src/Filament/Pages/ManageAiSettings.php, app-modules/integration-open-ai/src/Services/Concerns/UploadsFiles.php
- https://canyongbs.atlassian.net/browse/ADVAPP-698
Updates the assistant service when the settings UI is used, fixes issue with expired vector store checks when a thread is loaded.
=> [ADVAPP-698]: Resolve AI File Upload issues

app-modules/ai/src/Enums/AiModel.php, app/Multitenancy/Tasks/ClearBindingsTask.php, config/multitenancy.php
- https://canyongbs.atlassian.net/browse/ADVAPP-698
Creates a class to clear out bindings from tenancy. Starts with clearing out AI bindings.
>
=> [ADVAPP-698]: Add a multitenancy task to clear out bindings

app/Http/Requests/Tenants/CreateTenantRequest.php, app/Http/Requests/Tenants/SyncTenantRequest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-699
=> [ADVAPP-699]: Custom Assistants addon not syncing from Olympus

app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
- https://canyongbs.atlassian.net/browse/ADVAPP-698
Applies the `file_search` tool to a created Run if any message in the Thread contains files.
>
=> [ADVAPP-698]: Apply the file_search tool if any message has files

.github/pull_request_template.md
- https://canyongbs.atlassian.net/browse/ADVAPP-675
This updates the repository PR template to update details in each section and adds a section to list added Feature Flags.
N/A
No
=> [ADVAPP-675]: Update PR template to ask whether or not a Feature Flag was added in the PR

app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php, app-modules/ai/src/Models/AiAssistant.php
- https://canyongbs.atlassian.net/browse/ADVAPP-716
Fixes bugs with a AI Assistant create form caused by changes to the field for adding files to the Assistant.
N/A
No
No
=> [ADVAPP-716]: Attempting to create a new AI Assistant results in an exception

app-modules/basic-needs/database/migrations/2024_07_04_091421_data_purge_basic_needs_feature_flag.php, app-modules/basic-needs/src/Filament/Resources/BasicNeedsCategoryResource.php, app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource.php
- https://canyongbs.atlassian.net/browse/ADVAPP-695
> (Cleanup) basic-needs feature flag.
N/A
No
No
=> [ADVAPP-695]: (Cleanup) basic-needs feature flag

app-modules/campaign/src/Actions/ExecuteCampaignAction.php, app-modules/campaign/src/Actions/ExecuteCampaignActions.php, app-modules/campaign/src/Providers/CampaignServiceProvider.php, app-modules/engagement/src/Actions/QueuedEngagementDelivery.php, app-modules/engagement/src/Providers/EngagementServiceProvider.php, app-modules/meeting-center/src/Jobs/SyncCalendar.php, app-modules/meeting-center/src/Jobs/SyncCalendars.php, app-modules/meeting-center/src/Providers/MeetingCenterServiceProvider.php, app/Settings/DisplaySettings.php
- https://canyongbs.atlassian.net/browse/ADVAPP-733
Fixes issues caused by the unique functionality in jobs that prevent Engagements, Campaigns, and calendar syncs from being dispatched
N/A
No
No
=> [ADVAPP-733]: Engagement, Campaign, and CalendarSync jobs are not being dispatched by the scheduler

composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-719
This updates Filament to receive the fix.
No
No
=> [ADVAPP-719]: Third level navigation groups are not displaying appropriate arrow indicator when in an opened state

app/Filament/Resources/UserResource/Actions/AssignRolesBulkAction.php, app/Filament/Resources/UserResource/Pages/ListUsers.php
- https://canyongbs.atlassian.net/browse/ADVAPP-722
Added functionality to assign roles to multiple users.
No
No
=> [ADVAPP-722]: Introduce a user list bulk action to assign roles to users

app-modules/engagement/src/Filament/Actions/Concerns/ImplementsHasBulkEngagementAction.php
- https://canyongbs.atlassian.net/browse/ADVAPP-726
Make language as needed.
No
No
=> [ADVAPP-726]: Enhance modal warning language when canceling bulk engagement for students or prospects

app-modules/report/src/Filament/Pages/Students.php, app-modules/report/src/Filament/Widgets/MostRecentStudentsTable.php, app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php, app-modules/report/src/Filament/Widgets/StudentsState.php, app-modules/report/src/Filament/Widgets/StudentsStats.php, app-modules/student-data-model/database/factories/StudentFactory.php, app-modules/student-data-model/database/migrations/2024_07_08_182424_add_new_timestamps_columns_in_students_table.php, app-modules/student-data-model/database/migrations/2024_07_08_182958_data_update_timestamps_columns_data_in_student_table.php, app-modules/student-data-model/database/migrations/2024_07_08_184533_data_activate_student_timestamp_fields.php, app-modules/student-data-model/src/Models/Student.php
- https://canyongbs.atlassian.net/browse/ADVAPP-705
Add report widgets as per requirements.
No
Yes,
Feature flag name : student_timestamp_fields
=> [ADVAPP-705]: Create report for the report library for Students

app/Filament/Resources/UserResource/Pages/ListUsers.php, app/Models/User.php
- https://canyongbs.atlassian.net/browse/ADVAPP-720
> Add a new column for Team with a default off status that can be turned on.
> No
> No
=> [ADVAPP-720]: Enhance the display of employee information for user administrators by displaying the team they are on.

app-modules/basic-needs/database/migrations/2024_07_12_183702_data_purge_manage_program_participants_feature_flag.php, app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource/Pages/ManageParticipants.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectPrograms.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentPrograms.php
- https://canyongbs.atlassian.net/browse/ADVAPP-735
> (Cleanup) manage-program-participants feature flag
> No
> No
=> [ADVAPP-735]: (Cleanup) manage-program-participants feature flag

app-modules/task/src/Filament/Widgets/TasksWidget.php
- https://canyongbs.atlassian.net/browse/ADVAPP-724
> Added related to field in Retention CRM Dashboard.
> No
> Specifically Feature Flags to gate and control logic/flow changes to protect against database schema changes.
> No
=> [ADVAPP-724] Enhance the retention and recruitment dashboards by including related to fields for employee tasks

spectaql.yml
- https://canyongbs.atlassian.net/browse/ADVAPP-732
> Replace this block. Describe your changes in detail. This should include technical/architectural decisions and reasoning, if applicable.
> Updated the /api-docs
> No
> Specifically Feature Flags to gate and control logic/flow changes to protect against database schema changes.
> No
=> [ADVAPP-732] Enhance API Docs to contain helpful support information

app-modules/ai/src/Filament/Resources/AiAssistantResource/Pages/ListAiAssistants.php
- https://canyongbs.atlassian.net/browse/ADVAPP-742
Display avatar in round shape.
No
No
=> [ADVAPP-742]: Enhance the avatar display in the AI Assistant listing

app-modules/authorization/tests/Feature/Filament/Resources/User/RestoreUserTest.php, app/Filament/Resources/UserResource/Pages/CreateUser.php, app/Filament/Resources/UserResource/Pages/EditUser.php, app/Rules/EmailNotInUseOrSoftDeleted.php
- https://canyongbs.atlassian.net/browse/ADVAPP-718
> Change validation message for deleted user email address.
> 
>No.
> No.
=> [ADVAPP-718]: Inaccurate validation error presents when creating a new user with existing email address

app-modules/report/src/Filament/Widgets/MostRecentStudentsTable.php, app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php, app-modules/student-data-model/database/factories/StudentFactory.php, app-modules/student-data-model/database/migrations/2024_07_12_195608_data_clean_up_student_timestamp_fields.php, app-modules/student-data-model/src/Models/Student.php
- https://canyongbs.atlassian.net/browse/ADVAPP-743
> Cleaned up "student_timestamp_fields" feature flag.
> Might be ! `composer generate-api-docs` needs to run to update doc.
> Specifically Feature Flags to gate and control logic/flow changes to protect against database schema changes.
> No
=> [ADVAPP-743] (Cleanup) student_timestamp_fields feature flag

.github/actions/composer-dependency-setup/action.yml, .github/workflows/ci.yml, phpunit-ci.xml
- https://canyongbs.atlassian.net/browse/ADVAPP-717
Fixes the composer caching to truly cache the vendor directory and improve test time.
No
No
=> [ADVAPP-717]: Fix GitHub Action issues found in ticket

.github/actions/composer-dependency-setup/action.yml, .github/workflows/ci.yml, app-modules/ai/database/factories/AiAssistantFactory.php, app-modules/ai/src/Enums/AiApplication.php, app-modules/ai/src/Enums/AiModel.php, app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php, app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/CreateAiAssistantTest.php, app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/EditAiAssistantTest.php, app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/ListAiAssistantsTest.php, app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/RequestFactories/CreateAiAssistantRequestFactory.php, app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/RequestFactories/EditAiAssistantRequestFactory.php, app-modules/ai/tests/Feature/Policies/AiAssistantPolicyTest.php, phpunit-ci.xml
- https://canyongbs.atlassian.net/browse/ADVAPP-717
Add tests for common actions for Custom AI Assistants. Improved some of the validation along the way.
No
No
=> [ADVAPP-717]: Implement unit testing for common actions for Custom AI Assistants

resources/lang/vendor/filament-panels/en/global-search.php
- https://canyongbs.atlassian.net/browse/ADVAPP-725
> Change the Global search placeholder from 'Search' to  'Global Search'
> No.
> No.
=> [ADVAPP-725]: Enhance the placeholder text for global search

app-modules/ai/resources/js/chat.js, app-modules/ai/resources/views/components/assistant.blade.php, app-modules/ai/routes/web.php, app-modules/ai/src/Actions/CompleteResponse.php, app-modules/ai/src/Actions/RetryMessage.php, app-modules/ai/src/Actions/SendMessage.php, app-modules/ai/src/Exceptions/AiResponseToCompleteDoesNotExistException.php, app-modules/ai/src/Exceptions/AiStreamEndedUnexpectedlyException.php, app-modules/ai/src/Http/Controllers/CompleteResponseController.php, app-modules/ai/src/Http/Requests/CompleteResponseRequest.php, app-modules/ai/src/Services/Contracts/AiService.php, app-modules/ai/src/Services/TestAiService.php, app-modules/ai/tests/Feature/Actions/CompleteResponseTest.php, app-modules/ai/tests/Feature/Http/Controllers/CompleteResponseControllerTest.php, app-modules/integration-open-ai/src/Services/BaseOpenAiService.php, app-modules/integration-open-ai/src/Services/Concerns/UploadsFiles.php, app-modules/integration-open-ai/tests/Feature/Services/OpenAiGptTestServiceTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-697
Moves to an event based streaming system to handle more complex streaming events, such as incomplete responses and mid-stream errors.
Encodes response content in base64 in order to avoid issues parsing events in JSON.
No
No
=> [ADVAPP-697]: Improve processing of long AI responses by creating a "continue generating" button and process

app-modules/campaign/resources/views/filament/blocks/draft-campaign-engagement-block-with-ai-modal-content.blade.php, app-modules/campaign/src/Filament/Blocks/Actions/DraftCampaignEngagementBlockWithAi.php, app-modules/campaign/src/Filament/Blocks/EngagementBatchEmailBlock.php, app-modules/campaign/src/Filament/Blocks/EngagementBatchSmsBlock.php, app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php, app-modules/engagement/resources/views/filament/actions/draft-with-ai-modal-content.blade.php, app-modules/engagement/resources/views/filament/resources/draft-template-with-ai-modal-content.blade.php, app-modules/engagement/src/Enums/EngagementDeliveryMethod.php, app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php, app-modules/engagement/src/Filament/Actions/DraftWithAiAction.php, app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords.php, app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords/Actions/DraftWithAiAction.php, app-modules/engagement/src/Filament/Resources/Actions/DraftTemplateWithAiAction.php, app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/CreateEmailTemplate.php, app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php, app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/CreateSmsTemplate.php, app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/EditSmsTemplate.php
- https://canyongbs.atlassian.net/browse/ADVAPP-736
- https://canyongbs.atlassian.net/browse/ADVAPP-737
- https://canyongbs.atlassian.net/browse/ADVAPP-739
Extracts these actions into their own classes for easier maintainability. Based on the original implementation and tweaked the messaging and prompt to suit the situation.
No
No
=> [ADVAPP-736], [ADVAPP-737] & [ADVAPP-739]: Introduce the ability to use AI to draft emails in more places

app/Filament/Resources/UserResource/Actions/AssignTeamBulkAction.php, app/Filament/Resources/UserResource/Pages/ListUsers.php, app/Models/User.php
- https://canyongbs.atlassian.net/browse/ADVAPP-738
Introduce the ability to assign teams to users in bulk
No
No
=> [ADVAPP-738]: Introduce the ability to assign teams to users in bulk

app-modules/report/src/Filament/Widgets/LineChartReportWidget.php, app-modules/report/src/Filament/Widgets/PromptsCreatedLineChart.php, app-modules/report/src/Filament/Widgets/ProspectEngagementLineChart.php, app-modules/report/src/Filament/Widgets/SavedConversationsLineChart.php, app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php, app-modules/report/src/Filament/Widgets/StudentEngagementLineChart.php, app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php
- https://canyongbs.atlassian.net/browse/ADVAPP-755
Added abstract height for line chart.
No
No
=> [ADVAPP-755]: Enhance and standardize the maximum height display for line charts in dashboards

app-modules/report/src/Filament/Pages/ProspectReport.php, app-modules/report/src/Filament/Widgets/ProspectReportLineChart.php, app-modules/report/src/Filament/Widgets/ProspectReportStats.php, app-modules/report/src/Filament/Widgets/ProspectReportTableChart.php
- https://canyongbs.atlassian.net/browse/ADVAPP-706
> Create report in report library for Prospects module
> No.
> No.
=> [ADVAPP-706]: Create report for the report library for Prospects

app-modules/report/src/Filament/Pages/ArtificialIntelligence.php, app-modules/report/src/Filament/Pages/ProspectEnagagementReport.php, app-modules/report/src/Filament/Pages/ProspectReport.php, app-modules/report/src/Filament/Pages/StudentEngagementReport.php, app-modules/report/src/Filament/Pages/Students.php, app-modules/report/src/Filament/Pages/TaskManagement.php, app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php
- https://canyongbs.atlassian.net/browse/ADVAPP-766
> Change Report library navigation order and labels.
> No.
> No.
=> [ADVAPP-766]: Improve the third level navigation in the Report Library

app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
- https://canyongbs.atlassian.net/browse/ADVAPP-762
> Updates the column headings in the student list from "Sisid" to "SIS ID" and "Otherid" to "Other ID".
> No
> No
=> [ADVAPP-762]: Improve the display of SIS and Other ID columns in the student list

app-modules/engagement/src/Actions/CreateEngagementBatch.php, app-modules/engagement/src/Notifications/EngagementBatchFinishedNotification.php, app-modules/engagement/src/Notifications/EngagementBatchStartedNotification.php
- https://canyongbs.atlassian.net/browse/ADVAPP-749
> Update the titles for notifications and emails for processing and successful completion.
**Email Processing:** Bulk email request is being processed and will be sent shortly.
**Email Success:** Bulk email request has been processed and emails have been sent successfully.
**Text Processing:** Bulk text request is being processed and will be sent shortly.
**Text Success:** Bulk text message request has been processed and text messages have been sent successfully.
> No
> No
=> [ADVAPP-749]: Update delivery notifications when sending out bulk emails and texts to students and prospects to provide clear status updates

app-modules/application/src/Actions/DuplicateApplication.php, app-modules/application/src/Filament/Resources/ApplicationResource/Pages/ListApplications.php
- https://canyongbs.atlassian.net/browse/ADVAPP-765
> Add a 'Duplicate' functionality for Admissions applications.
> No.
> No.
=> [ADVAPP-765]: Introduce the ability to duplicate admissions applications

app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/EditAiAssistantTest.php, app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/RequestFactories/EditAiAssistantRequestFactory.php, app-modules/application/src/Filament/Resources/ApplicationResource/Pages/ListApplications.php
- https://canyongbs.atlassian.net/browse/ADVAPP-774
Fixes the class naming of the EditAiAssistantRequestFactory file.
No
No
=> [ADVAPP-774]: Fix class naming of EditAiAssistantRequestFactory file

app-modules/engagement/resources/views/components/empty-state.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-780
Update instructions in message center to be more user friendly
No
No
=> [ADVAPP-780]: Update instructions in message center to be more user friendly

app-modules/ai/database/migrations/2024_07_31_181656_create_ai_integrated_assistant_settings.php, app-modules/ai/database/migrations/2024_07_31_185847_seed_permissions_add_ai_integrated_assistant_settings.php, app-modules/ai/database/migrations/2024_07_31_191352_data_activate_ai_integrated_assistant_settings_feature.php, app-modules/ai/src/Filament/Pages/ManageAiIntegratedAssistantSettings.php, app-modules/ai/src/Filament/Pages/ManageAiSettings.php, app-modules/ai/src/Settings/AiIntegratedAssistantSettings.php, app-modules/campaign/src/Filament/Blocks/Actions/DraftCampaignEngagementBlockWithAi.php, app-modules/consent/src/Filament/Resources/ConsentAgreementResource.php, app-modules/engagement/src/Filament/Actions/DraftWithAiAction.php, app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords/Actions/DraftWithAiAction.php, app-modules/engagement/src/Filament/Resources/Actions/DraftTemplateWithAiAction.php, app-modules/report/src/Filament/Pages/ManageReportAssistantSettings.php
- https://canyongbs.atlassian.net/browse/ADVAPP-740
Creates a new setting and settings management page for the Integrated Assistant. Uses this setting in all places the Integrated Assistant is instantiated.
No
`ai-integrated-assistant-settings`
=> [ADVAPP-740]: Update the experience for setting the default model for integrated AI actions in product administration

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentCareTeam.php
- https://canyongbs.atlassian.net/browse/ADVAPP-781
Enhance the Prospect and Student care team experience by allowing the ability to add more than one staff member at a time
No
No
=> [ADVAPP-781]: Enhance the Prospect and Student care team experience by allowing the ability to add more than one staff member at a time

app-modules/ai/database/migrations/2024_08_07_174418_add_ai_assistant_name_column_to_assistant_chat_message_logs_table.php, app-modules/ai/database/migrations/2024_08_07_175648_data_activate_ai_assistant_auditing_changes_feature.php, app-modules/ai/database/migrations/2024_08_07_182051_data_backfill_assistant_chat_message_logs_ai_assistant_name.php, app-modules/ai/src/Filament/Resources/LegacyAiMessageLogResource.php, app-modules/ai/src/Listeners/CreateAiMessageLog.php, app-modules/ai/src/Models/AiAssistant.php, app-modules/ai/src/Models/LegacyAiMessageLog.php, app-modules/audit/src/Filament/Resources/AuditResource/Pages/ListAudits.php
- https://canyongbs.atlassian.net/browse/ADVAPP-750
Updates auditing to make sure custom assistant is audited.
Enhances the AI Chat message audit record with details on the Assistant used.
Yes, after deployment AiAssistant will need to be manually turned on in Global Settings in order to triggered auditing for it.
Feature Flag: `ai_assistant_name`
Data migrations:
- `app-modules/ai/database/migrations/2024_08_07_182051_data_backfill_assistant_chat_message_logs_ai_assistant_name.php`
=> [ADVAPP-750]: Enhance AI user auditing to better support custom assistants

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php
- https://canyongbs.atlassian.net/browse/ADVAPP-772
> Update the student and prospect data model to better handle an alternate email address.
>No
> No
=> [ADVAPP-772]: Update the student and prospect data model to better handle an alternate email address

app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php
- https://canyongbs.atlassian.net/browse/ADVAPP-801
> Campaign action, type and executed at labels changed and changed ordering of the journey steps.
> No.
> No
=> [ADVAPP-801]: Enhance the experience of viewing a campaign by ordering journey steps chronologically

app-modules/audit/database/migrations/2024_08_12_155524_data_purge_change_agent_name_feature_flag.php, app-modules/audit/src/Filament/Exports/AuditExporter.php, app-modules/audit/src/Filament/Resources/AuditResource/Pages/ListAudits.php, app-modules/audit/src/Filament/Resources/AuditResource/Pages/ViewAudit.php
- https://canyongbs.atlassian.net/browse/ADVAPP-804
> (Cleanup) change-agent-name feature flag.
> No
> No
=> [ADVAPP-804]: [Cleanup]: change-agent-name feature flag

app-modules/interaction/resources/views/filament/actions/draft-with-ai-modal-content.blade.php, app-modules/interaction/src/Filament/Actions/DraftInteractionWithAiAction.php, app-modules/interaction/src/Filament/Actions/DraftWithInteractionAiAction.php, app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/CreateInteraction.php
- https://canyongbs.atlassian.net/browse/ADVAPP-783
> Added Draft with AI Action in the Interaction creation for student and prospect.
> No
> No
=> [ADVAPP-783]: Introduce Draft with AI for student and prospect interactions

Dockerfile, package-lock.json
- https://canyongbs.atlassian.net/browse/ADVAPP-806
Resolves https://github.com/canyongbs/advisingapp/security/dependabot/16 and https://github.com/canyongbs/advisingapp/security/code-scanning/3
No.
No.
=> [ADVAPP-806]: CVE-2024-39338

.github/workflows/ci.yml, app-modules/service-management/src/Models/ChangeRequest.php, phpstan.neon.dist, phpunit-ci.xml
- https://canyongbs.atlassian.net/browse/ADVAPP-808
Resolves CI issue where "fatal: No names found, cannot describe anything." is thrown due to CI pulling a shallow clone of the repository.
No.
No.
=> [ADVAPP-808]: Fix "fatal: No names found, cannot describe anything." during CI/CD

.github/CODEOWNERS
- https://canyongbs.atlassian.net/browse/ADVAPP-814
Sets up CODEOWNERS for the repository.
No.
No.
=> [ADVAPP-814]: Setup CODEOWNERS

.github/workflows/ci.yml, .github/workflows/pull_requests.yml
- https://canyongbs.atlassian.net/browse/ADVAPP-814
Adjusts CI to work for Merge Queues.
No.
No.
=> [ADVAPP-814]: Setup Merge Queues

_ide_helper_models.php, app-modules/student-data-model/database/migrations/2024_08_19_202551_create_student_information_system_settings.php, app-modules/student-data-model/database/migrations/2024_08_19_203311_data_activate__sis_integration_settings.php, app-modules/student-data-model/database/migrations/2024_08_19_204749_seed_permissions_add_manage_sis_settings.php, app-modules/student-data-model/resources/views/filament/resources/student-resource/sis-sync.blade.php, app-modules/student-data-model/src/Enums/SisSystem.php, app-modules/student-data-model/src/Filament/Pages/ManageStudentInformationSystemSettings.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php, app-modules/student-data-model/src/Models/Student.php, app-modules/student-data-model/src/Settings/StudentInformationSystemSettings.php, app/Enums/FeatureFlag.php, docker-compose.dev.yml
- https://canyongbs.atlassian.net/browse/ADVAPP-800
Adds integration settings for Student Information Systems, sets up Thesis Elements as the first option. Then displays sync data and a sync button on the Student view page.
No.
Feature Flags:
- `SisIntegrationSettings`
=> [ADVAPP-800]: Create new integration settings for Thesis Elements SIS integration

Dockerfile
- N/A
Ensures that Filament assets are available when the assets are compiled into the Dockerfile.
No
No
=> [Bugfix]: Resolve issues with missing Filament assets

app-modules/interaction/src/Filament/Resources/InteractionResource/RelationManagers/HasManyMorphedInteractionsRelationManager.php
- https://canyongbs.atlassian.net/browse/ADVAPP-824
> Label changed for the interaction view modal.
> No.
> No
=> [ADVAPP-824]: Update student and prospect interaction titles for improved clarity

app-modules/service-management/src/Filament/Concerns/ServiceRequestUpdateBreadcrumbs.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Pages/EditServiceRequestUpdate.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Pages/ListServiceRequestUpdates.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Pages/ViewServiceRequestUpdate.php, app-modules/service-management/tests/ServiceRequestUpdate/ListServiceRequestUpdatesTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-817
> Search in Service Request Updates throws an error & Update the breadcrumb
> No
> No
=> [ADVAPP-817]: Search in Service Request Updates throws an error

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php
- https://canyongbs.atlassian.net/browse/ADVAPP-773
> Update the Address Field labels within the contact information section to help users understand the intended purpose of these fields
>No
> No
=> [ADVAPP-773]: Label change in contact information

resources/views/vendor/filament-panels/components/logo.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-838
> Set static position for header logo.
> No.
> No.
=> [ADVAPP-838]: When uploading a partner logo of the PNG type the logo renders with distorted proportions.

app-modules/engagement/src/Actions/GenerateTipTapBodyJson.php, composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-832
> Resolve the security issue tracked under CVE-2024-45048, CVE-2024-45046
> No.
>No.
=> [ADVAPP-832] Resolve the security issue tracked under CVE-2024-45048

app-modules/ai/database/migrations/2023_09_13_160013_ai_settings.php, app-modules/ai/database/migrations/2024_09_06_182440_data_convert_ai_settings_max_tokens.php, app-modules/ai/resources/views/components/assistant.blade.php, app-modules/ai/src/Enums/AiMaxTokens.php, app-modules/ai/src/Filament/Pages/ManageAiSettings.php, app-modules/ai/src/Settings/AiSettings.php, app-modules/integration-open-ai/src/Services/BaseOpenAiService.php, app/Providers/AppServiceProvider.php
- https://canyongbs.atlassian.net/browse/ADVAPP-853
Updates the continue generating label and also converts the Max Tokens to an ENUM and increases the size.
No
`AiSettingsMaxTokensUpdate`
=> [ADVAPP-853]: Update the label on the continue generating

app-modules/ai/database/migrations/2023_09_13_160013_ai_settings.php, app-modules/ai/database/migrations/2024_09_06_182440_data_convert_ai_settings_max_tokens.php, app-modules/ai/resources/views/components/assistant.blade.php, app-modules/ai/src/Enums/AiMaxTokens.php, app-modules/ai/src/Filament/Pages/ManageAiSettings.php, app-modules/ai/src/Settings/AiSettings.php, app-modules/integration-open-ai/src/Services/BaseOpenAiService.php, app/Providers/AppServiceProvider.php
- N/A
Includes fixes that went out in hotfix `1.26.1`
No
No
=> [Hotfix]: 1.26.1

app-modules/authorization/composer.json, app-modules/authorization/database/migrations/2023_07_11_182500_create_permission_tables.php, app-modules/authorization/src/Models/Concerns/HasRolesWithPivot.php, app-modules/authorization/src/Models/Role.php, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-870
Solves major performance issues with wildcard permissions by upgrading Spatie Permissions to v6, to include https://github.com/spatie/laravel-permission/pull/2445.
No
No
=> [ADVAPP-870]: Fix performance issues with Roles

app-modules/ai/src/Rules/RestrictSuperAdmin.php, app-modules/ai/tests/Feature/Filament/Pages/AIAssistantPageTest.php, app-modules/authorization/database/migrations/2024_08_14_174150_data_change_authorization.super_admin_to_sass_global_admin_in_roles_table.php, app-modules/authorization/src/Console/Commands/SetupRoles.php, app-modules/authorization/src/Enums/LicenseType.php, app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ListRoles.php, app-modules/authorization/src/Models/Role.php, app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php, app-modules/authorization/tests/Unit/LicenceTypeTest.php, app-modules/notification/src/Notifications/Channels/EmailChannel.php, app-modules/notification/src/Notifications/Channels/SmsChannel.php, app-modules/notification/tests/Features/NotificationSendingTest.php, app-modules/team/src/Filament/Resources/TeamResource/RelationManagers/UsersRelationManager.php, app-modules/team/tests/Team/EditTeamTest.php, app/Filament/Resources/UserResource.php, app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php, app/Jobs/CreateTenantUser.php, app/Models/Authenticatable.php, app/Models/Scopes/WithoutSuperAdmin.php, app/Models/User.php, app/Providers/AuthServiceProvider.php, database/seeders/LocalDevelopmentSeeder.php, database/seeders/SampleSuperAdminUserSeeder.php, tests/Unit/LicenseSettingsEmailQuotaTracking.php, tests/Unit/LicenseSettingsSmsQuotaTracking.php
- https://canyongbs.atlassian.net/browse/ADVAPP-870
Optimizes checks for the Super Admin role.
No
No
=> [ADVAPP-870]: Fix performance issues with Roles - super admin checks

portals/knowledge-management/src/Pages/ViewArticle.vue
- https://canyongbs.atlassian.net/browse/ADVAPP-845
> Made the changes in the header file and added icon above the date time.
> No.
> No.
=> [ADVAPP-845]: Enhance the header in the support portal to better separate the article details from the article content

app-modules/report/src/Filament/Pages/ArtificialIntelligence.php, app-modules/report/src/Filament/Widgets/ExchangesByMonthLineChart.php, app-modules/report/src/Filament/Widgets/SavedConversationsLineChart.php, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-863
> Instead of AiThread it will show the data from the TrackedEvent based on the type : AiExchange
> No
> No
=> [ADVAPP-863] Enhance the AI Utilization report for institutions by tracking AI Assistant exchanges in the line chart

app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalCategoryController.php, portals/knowledge-management/src/App.vue, portals/knowledge-management/src/Pages/ViewCategory.vue
- https://canyongbs.atlassian.net/browse/ADVAPP-847
> When viewing a list of articles within a category, paginate the results
> No
> No
=> [ADVAPP-847]: When viewing a list of articles within a category, paginate the results

composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-855
Updates `canyongbs/filament-tiptap-editor` to include the changes done for security.
No
No
=> [ADVAPP-855]: Resolve the security issue tracked under CVE-2024-39338

app-modules/portal/database/migrations/2024_09_16_093804_add_gdpr_banner_to_settings_table.php, app-modules/portal/database/migrations/2024_09_16_104513_data_activate_gdpr_banner_feature_flag.php, app-modules/portal/src/Enums/GdprBannerButtonLabel.php, app-modules/portal/src/Filament/Pages/ManagePortalSettings.php, app-modules/portal/src/Settings/PortalSettings.php, app/Enums/FeatureFlag.php, app/Providers/FilamentServiceProvider.php, resources/views/vendor/cookie-consent/dialog.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-849
> Added GDPR Banner Notice Section in Portal Setting.
> No
> Yes. "GDPRBanner"
=> [ADVAPP-849]: Introduce the ability to insert hyperlinks in the GDPR compliant notice on the portal

app-modules/knowledge-base/database/migrations/2024_09_10_171824_add_portal_view_count_in_knowledge_base_articles_table.php, app-modules/knowledge-base/src/Models/KnowledgeBaseArticle.php, app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalArticleController.php, database/migrations/2024_09_12_142103_portal_view_count_feature_flag.php, portals/knowledge-management/src/Pages/ViewArticle.vue
- https://canyongbs.atlassian.net/browse/ADVAPP-844
>  Create new feature where every time the article is clicked for view it count increases and end user can see total number of view on that article in the view article page.
> No.
> `portal_view_count`
=> [ADVAPP-844]: Track portal views of articles and display them as article metadata

app-modules/engagement/resources/views/components/message-center-inbox.blade.php, app-modules/engagement/src/Filament/Pages/MessageCenter.php
- https://canyongbs.atlassian.net/browse/ADVAPP-881
> Show user type(Prospect or Student) in message center.
> No.
> No.
=> [ADVAPP-881]: Enhance message center by indicating whether a person is a student or a prospect

app-modules/engagement/resources/views/components/message-center-content.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-882
> Add a link icon beside name in message center content.
> No.
> No.
=> [ADVAPP-882]: Enhance message center by improving the way a linked record works

app/Providers/HealthServiceProvider.php
- https://canyongbs.atlassian.net/browse/ADVAPP-860
> Update the App URL in the PingCheck class instead of checking the IP address (1.1.1.1).
> No
> No
=> [ADVAPP-860]: Product Ping Health check is failing for all environments

resources/views/vendor/cookie-consent/dialog.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-913
Fix references to old FeatureFlag ENUM that was missed during removal.
No
No
=> [ADVAPP-913]: When navigating to view a form, or a response for a form, an exception is generated.

docker-compose.yml
- https://canyongbs.atlassian.net/browse/ADVAPP-916
Resolves issues in our Docker Compose setup by removing duplicate `extra_hosts` entries that are no longer allowed in recent Docker version.
No
No
=> [ADVAPP-916]: Resolve issues in our Docker Compose setup from Docker Updates

app-modules/prospect/database/migrations/2024_10_08_161832_data_ensure_system_default_prospect_statuses_exist.php
- N/A
Fixes the sort atomic query in the default data migration.
No
No
=> [Bugfix]: Fix issue with prospect status default data migration

resources/views/vendor/filament-panels/components/layout/login.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-933
> Improve the display of the login page with additional UI/UX enhancements
> No
> No
=> [ADVAPP-933]: Improve the display of the login page with additional UI/UX enhancements

app-modules/campaign/src/Actions/ExecuteCampaignAction.php
- https://canyongbs.atlassian.net/browse/ADVAPP-936
Increases timeout of the campaign execute jobs to not fail for large segments.
No
No
=> [ADVAPP-936]: When accessing email or texts for a specific record in the demo environment, it generates an error.

app-modules/theme/src/Settings/ThemeSettings.php, app/Providers/Filament/AdminPanelProvider.php
- https://canyongbs.atlassian.net/browse/ADVAPP-937
Enhance the partner branding capabilities by introducing a new support menu item in the profile drop down menu
No
No
=> [ADVAPP-937]: Enhance the partner branding capabilities by introducing a new support menu item in the profile drop down menu

app-modules/engagement/resources/views/components/empty-state.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-960
> Update text in message center to represent all aspect ratios including mobile.
> No.
> No.
=> [ADVAPP-960]: Update text in message center to represent all aspect ratios including mobile

app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/ListCampaigns.php
- https://canyongbs.atlassian.net/browse/ADVAPP-964
> Add enabled and complete as options to display in the list view of campaigns.
> No.
> No.
=> [ADVAPP-964]: Add enabled and complete as options to display in the list view of campaigns

app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentCareTeamRelationManager.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentFilesRelationManager.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentSubscriptionsRelationManager.php
- https://canyongbs.atlassian.net/browse/ADVAPP-971
Fixes issues in View Student page relation managers.
No
No
=> [ADVAPP-971]: View Student page Files, Care Team, and Subscriptions manager issues

app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
- https://canyongbs.atlassian.net/browse/ADVAPP-962
> Update the language used when there are no interactions on a student or prospect record
> No
> No
=> [ADVAPP-962]: Update the language used when there are no interactions on a student or prospect record

app-modules/campaign/database/factories/CampaignFactory.php, app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/ListCampaigns.php, app-modules/campaign/tests/Actions/ListCampaignsTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-965
> Add filters for the campaign list view for my campaigns, enabled, and has been executed.
> No.
> No.
=> [ADVAPP-965] : Add filters for the campaign list view for my campaigns, enabled, and has been executed

app-modules/campaign/src/Filament/Blocks/EngagementBatchEmailBlock.php, app-modules/campaign/src/Filament/Blocks/EngagementBatchSmsBlock.php, app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php, app-modules/engagement/src/Filament/Actions/SendEngagementAction.php, app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords.php, app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/CreateEmailTemplate.php, app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Fields/EngagementSmsBodyField.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php, app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/CreateSmsTemplate.php, app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/EditSmsTemplate.php, app-modules/engagement/src/Models/Engagement.php, app-modules/form/src/Filament/Resources/FormResource/Pages/ManageFormEmailAutoReply.php, app-modules/form/src/Models/FormEmailAutoReply.php, app-modules/prospect/src/Models/Prospect.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentEngagementRelationManager.php, app-modules/student-data-model/src/Models/Student.php
- https://canyongbs.atlassian.net/browse/ADVAPP-969
Add the ability to merge the value in for the preferred name of a student and prospect in engagement scenarios
No
No
=> [ADVAPP-969]: Add the ability to merge the value in for the preferred name of a student and prospect in engagement scenarios

app-modules/student-data-model/src/Filament/Tables/StudentsTable.php
- https://canyongbs.atlassian.net/browse/ADVAPP-990
> Update rule title for Programs to Number of Programs.
> No.
> No.
=> [ADVAPP-990]: Update rule title for Programs to Number of Programs

app-modules/prospect/src/Filament/Resources/ProspectResource/Actions/ConvertToStudent.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1006
> Disassociate results in a page not found error
> No
> No
=> [ADVAPP-1006]: Disassociate results in a page not found error

app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1002
> After creating an interaction, I am unable to delete it, even with the appropriate permissions..
> No.
> No.
=> [ADVAPP-1002]: After creating an interaction, I am unable to delete it, even with the appropriate permissions.

app-modules/prospect/src/Filament/Pages/ManageProspectConversionSettings.php, app-modules/prospect/src/Filament/Resources/ProspectSourceResource.php, app-modules/prospect/src/Filament/Resources/ProspectStatusResource.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1021
> Update the naming of constituent management settings in Product Administration..
> No.
> No.
=> [ADVAPP-1021]: Update the naming of constituent management settings in Product Administration.

app-modules/authorization/src/Http/Controllers/SocialiteController.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1027
This will add retries to the Azure PFP retrieval as well as prevent the entire login request from failing if it is not resolved.
No
No
=> [ADVAPP-1027]: Failure to retrieve Azure profile image causes issues with login

app-modules/prospect/src/Filament/Resources/ProspectResource.php, app-modules/student-data-model/src/Filament/Resources/StudentResource.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1003
>Enhance the abilities of global search by including preferred name in search results.
> No.
> No.
=> [ADVAPP-1003]: Enhance the abilities of global search by including preferred name in search results.

app/Filament/Resources/UserResource/Pages/ListUsers.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1004
> Add search functionality in product user page.
> No.
> No.
=> [ADVAPP-1004]: Enhance the user list experience by adding search

app-modules/student-data-model/resources/views/filament/resources/educatable-resource/view-educatable-activity-feed.blade.php, app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-activity-feed-widget.blade.php, app-modules/student-data-model/resources/views/filament/resources/student-resource/view-student.blade.php, app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/HasEducatableActivityFeed.php, app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableActivityFeedWidget.php, app-modules/student-data-model/src/Filament/Resources/StudentResource.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudentActivityFeed.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1036
Moves the full timeline to a new page and removes the previous modal.
No
No
=> [ADVAPP-1036]: Enhance timeline by switching from a modal to a page with a back button after clicking through the student detail page

composer.lock
- N/A
Merge back into `main` for hotfix `1.40.2`
No
No
=> [Hotfix]: 1.40.2

app-modules/alert/src/Filament/Resources/AlertStatusResource/Pages/ViewAlertStatus.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1049
Fixes component reference issue with ViewAlertStatus page.
No
No
=> [ADVAPP-1049]: When attempting to create a new alert status, it results in an error

app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php, app/Filament/Resources/UserResource/Pages/ListUsers.php
- https://canyongbs.atlassian.net/browse/ADVAPP-977
> Enhance the user list experience by introducing filters for each license type
> No
> No
=> [ADVAPP-977]: Enhance the user list experience by introducing filters for each license type

app-modules/ai/src/Filament/Resources/AiAssistantResource.php, app-modules/prospect/src/Filament/Resources/PipelineResource.php, app/Filament/Pages/ProductHealth.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1031
> Modify the iconography to be more consistent in the collapsed view of the navigation.
> No.
> No.
=> [ADVAPP-1031]: Modify the iconography to be more consistent in the collapsed view of the navigation

app-modules/ai/tests/Feature/Filament/Resources/PromptResource/ListPromptsTest.php, app-modules/ai/tests/Feature/Filament/Resources/PromptTypeResource/ListPromptTypesTest.php, app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php, app-modules/basic-needs/tests/BasicNeedsCategory/BasicNeedsCategoryTest.php, app-modules/basic-needs/tests/BasicNeedsProgram/BasicNeedsProgramTest.php, app-modules/case-management/tests/Case/ListCasesTest.php, app-modules/case-management/tests/CaseStatus/ListCaseStatusesTest.php, app-modules/case-management/tests/CaseType/ListCaseTypeTest.php, app-modules/case-management/tests/CaseUpdate/ListCaseUpdatesTest.php, app-modules/prospect/tests/Prospect/ListProspectTest.php, app-modules/prospect/tests/ProspectSource/ListProspectSourcesTest.php, app-modules/prospect/tests/ProspectStatus/ListProspectStatusesTest.php, app-modules/task/tests/ListTasksTest.php, app/Providers/AppServiceProvider.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1055
> Adjust the scope of table pagination options for all table views
> No
> No
=> [ADVAPP-1055]: Adjust the scope of table pagination options for all table views

app-modules/authorization/src/Filament/Forms/Components/PermissionsMatrix.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1071
No
No
=> [ADVAPP-1071]: Some permissions are not available in the permissions matrix and syncing of permissions is not available upon change

app-modules/campaign/src/Filament/Resources/CampaignResource.php, app-modules/resource-hub/src/Filament/Resources/ResourceHubArticleResource.php, app-modules/segment/src/Filament/Resources/SegmentResource.php, app-modules/task/src/Filament/Resources/TaskResource.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1056
> Move resource hub from Premium Features to Engagement Features
> No
> No
=> [ADVAPP-1056]: Move resource hub from Premium Features to Engagement Features

app-modules/student-data-model/src/Filament/Resources/ManageStudentResource/Pages/ListManageStudents.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1067
> Provide sample import files for the student model.
> No.
> No.
=> [ADVAPP-1067]: Provide sample import files for the student model

app-modules/authorization/composer.json, app-modules/authorization/resources/views/filament/forms/components/permissions-matrix.blade.php, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1068
> Adjust the opacity of the checkboxes on the role view page when using light mode
> No
> No
=> [ADVAPP-1068]: Adjust the opacity of the checkboxes on the role view page when using light mode

database/migrations/2024_12_19_201828_seed_permissions_give_proper_split_permissions_to_roles.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1063
Fix role access for permissions that split
No
No
=> [ADVAPP-1063]: Fix role access for permissions that split

database/migrations/2024_12_19_201828_seed_permissions_give_proper_split_permissions_to_roles.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1063
Fixes bad permission migration.
No
No
=> [ADVAPP-1063]: Fix broken migration

database/migrations/2024_12_19_165310_drop_sessions_table.php
- https://canyongbs.atlassian.net/browse/ADVAPP-674
Eliminate the legacy sessions management artifacts
No
No
=> [ADVAPP-674]: Eliminate the legacy sessions management artifacts

Dockerfile
- https://canyongbs.atlassian.net/browse/ADVAPP-1065
Updates RoadRunner.
No
No
=> [ADVAPP-1065]: Update RoadRunner Binary to v2024.3.0

app-modules/engagement/database/migrations/2024_12_27_002830_purge_timeline_items_related_to_enagements.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1097
Purges timeline records related to Engagement entities that were deleted.
No
Migration: `app-modules/engagement/database/migrations/2024_12_27_002830_purge_timeline_items_related_to_enagements.php`
=> [ADVAPP-1097]: Add migration to purge timeline items related to engagements

app-modules/engagement/database/migrations/2024_12_27_010201_purge_timeline_items_related_to_enagements_correctly.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1097
Ensure we are purging the records by specifying the correct type column.
No
Migration: `app-modules/engagement/database/migrations/2024_12_27_010201_purge_timeline_items_related_to_enagements_correctly.php`
=> [ADVAPP-1097]: Student and prospect activity logs are generating an error

app-modules/authorization/database/migrations/2024_12_30_142708_add_matching_property_to_azure_sso_settings.php, app-modules/authorization/database/migrations/2024_12_30_144224_data_activate_azure_matching_property_feature.php, app-modules/authorization/src/Enums/AzureMatchingProperty.php, app-modules/authorization/src/Enums/SocialiteProvider.php, app-modules/authorization/src/Exceptions/InvalidAzureMatchingProperty.php, app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php, app-modules/authorization/src/Http/Controllers/SocialiteController.php, app/Features/AzureMatchingPropertyFeature.php
- N/A
Merges in changes in hotfix 1.44.0.
No
No
=> [Hotfix]: 1.44.0

app-modules/ai/database/factories/PromptFactory.php, app-modules/ai/src/Filament/Resources/PromptResource/Pages/ListPrompts.php, app-modules/ai/tests/Feature/Filament/Resources/PromptResource/ListPromptsTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1078
> Introduce the ability to filter by Smart prompts in the Prompt Library
> No
> No
=> [ADVAPP-1078]: Introduce the ability to filter by Smart prompts in the Prompt Library

app-modules/authorization/database/migrations/2024_12_30_142107_data_seed_role_permissions.php, app-modules/authorization/src/Filament/Resources/RoleResource/Pages/EditRole.php, app-modules/authorization/src/Policies/RolePolicy.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1090
Seeds role permissions, adds delete action to Edit Role page. Removed role group permissions.
No
No
=> [ADVAPP-1090]: Users are unable to delete roles

app-modules/case-management/resources/views/filament/resources/case-resource/view-case/header.blade.php, app-modules/case-management/src/Filament/Resources/CaseResource/Pages/Concerns/HasCaseHeader.php, app-modules/case-management/src/Filament/Resources/CaseResource/Pages/CreateCase.php, app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ViewCase.php, app-modules/prospect/resources/views/filament/resources/prospect-resource/view-prospect.blade.php, app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/CasesRelationManager.php, app-modules/student-data-model/resources/views/filament/resources/student-resource/view-student.blade.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/CasesRelationManager.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1076
>  Include "Cases" in top menu bar after interactions for students and prospects.
> No.
> No.
=> [ADVAPP-1076] Include "Cases" in top menu bar after interactions for students and prospects

app-modules/campaign/src/Filament/Resources/CampaignResource.php, app-modules/segment/src/Filament/Resources/SegmentResource.php, app-modules/task/src/Filament/Resources/TaskResource.php, app/Filament/Clusters/CaseManagementAdministration.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1075
> Relocate Case Management from Premium Features to Engagement Features.
> No.
> No.
=> [ADVAPP-1075]: Relocate Case Management from Premium Features to Engagement Features

app-modules/student-data-model/database/migrations/2025_01_03_155805_seed_permissions_add_remaining_student_permissions.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1103
Seeds the missing Student permissions.
No
No
=> [ADVAPP-1103]: Users are unable to edit tags on student profiles

app/Filament/Clusters/CaseManagement.php, app/Filament/Clusters/CaseManagementAdministration.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1109
> The Case Management feature is currently listed in two locations within the product.
> No.
> No.
=> [ADVAPP-1109]: The Case Management feature is currently listed in two locations within the product

composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1127
Updates deps to resolve security vulnerability.
No
No
=> [ADVAPP-1127]: Resolve the security issue tracked under CVE-2025-22145

app-modules/report/tests/Unit/UniqueLogin/UserStatsTest.php, app/Filament/Resources/UserResource/Pages/EditUser.php, app/Filament/Resources/UserResource/Pages/ViewUser.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1135
> Add team assignment dropdown to the view and edit pages for managing users
> No
> No
=> [ADVAPP-1135]: Add team assignment to the view and edit pages for managing users

app-modules/report/src/Enums/ReportModel.php, app/Filament/Tables/UsersTable.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1132
> When attempting to create a custom report for Users an exception is generated
> No
> No
=> [ADVAPP-1132]: When attempting to create a custom report for Users an exception is generated

app/Providers/Filament/AdminPanelProvider.php, resources/js/admin.js, vite.config.js
- https://canyongbs.atlassian.net/browse/ADVAPP-1110
Appears to be an unresolved issue with Livewire (https://github.com/livewire/livewire/discussions/5923#discussioncomment-8670951)
Found a "temporary" fix here https://github.com/livewire/livewire/discussions/5923#discussioncomment-9202549
No
No
=> [ADVAPP-1110]: When loading the student detail page in browsers other than Chrome, Edge, or Firefox, I experience display issues

app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/ProgramsRelationManager.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1147
> Refactor form labels and change required validations in ProgramsRelationManager
> No.
> No.
=> [ADVAPP-1147]: Adjust display of fields for the program model

app-modules/student-data-model/database/factories/ProgramFactory.php, app-modules/student-data-model/database/migrations/2025_01_20_143750_drop_other_id_column_from_programs_table.php, app-modules/student-data-model/src/Enums/SisSystem.php, app-modules/student-data-model/src/Filament/Imports/ProgramImporter.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/ProgramsRelationManager.php, app-modules/student-data-model/src/Models/Program.php, database/migrations/2025_01_20_143750_drop_other_id_column_from_programs_table.php, database/seeders/StudentSeeder.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1146
> Remove Other ID as part of the program data model
> No
> No
=> [ADVAPP-1146]: Remove Other ID as part of the program data model

app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php, resources/views/filament/forms/components/campaigns/actions/proactive-alert.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1150
> Attempting to create a campaign journey step for a proactive alert generates an exception
> No
> No
=> [ADVAPP-1150]: Attempting to create a campaign journey step for a proactive alert generates an exception

app-modules/authorization/resources/views/filament/forms/components/permissions-matrix.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1102
Adds links to column headers as describes. Shows/hides links where appropriate.
No
No
=> [ADVAPP-1102]: Add bulk select and deselect features to the permission when editing a role for each column

resources/css/filament/admin/theme.css
- https://canyongbs.atlassian.net/browse/ADVAPP-1173
> Enhance the ability to distinguish the main navigation from the page itself
> No
> No
=> [ADVAPP-1173]: Enhance the ability to distinguish the main navigation from the page itself

app/Filament/Imports/UserImporter.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1161
> Enhance the user importer experience for user administrators
> No
> No
=> [ADVAPP-1161]: Enhance the user importer experience for user administrators

app-modules/student-data-model/src/Filament/Imports/EnrollmentImporter.php, app-modules/student-data-model/src/Filament/Imports/ProgramImporter.php, app-modules/student-data-model/src/Filament/Imports/StudentEnrollmentImporter.php, app-modules/student-data-model/src/Filament/Imports/StudentProgramImporter.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/Concerns/ImportColumns.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php, app-modules/student-data-model/tests/Student/ListStudentsTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1172
> Add import functionality for student programs and enrollments
> No
> No
=> [ADVAPP-1172]: Update the student importer to allow for switching between students, programs, and enrollment bulk imports

app-modules/ai/resources/js/chats.js, app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php, app-modules/ai/src/Jobs/CloneAiThread.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1183
> Implement thread parameter removal and clone notification in AI chat management
> No
> No
=> [ADVAPP-1183]: Add a notification to the receiving user of a AI clone chat

.gitignore
- https://canyongbs.atlassian.net/browse/ADVAPP-1189
> Add .psysh_history to the .gitignore
> No
> No
=> [ADVAPP-1189]: Add .psysh_history to the .gitignore

app-modules/prospect/src/Filament/Widgets/ProspectStats.php, app-modules/report/src/Filament/Widgets/ProspectReportStats.php, app-modules/report/src/Filament/Widgets/StudentsStats.php, app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1216
> Show the complete number of students in the student, prospect, and report when the number is 4 digits or longer.
> No
> No
=> [ADVAPP-1216]: Show the complete number of students in the student, prospect, and report

app-modules/prospect/src/Filament/Widgets/ProspectStats.php, app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1197
> Add URLs to Prospect and Student stats for better navigation.
> No.
> No.
=> [ADVAPP-1197]: Convert dashboard card headings into hyperlinks for quick access to list views

app-modules/integration-twilio/src/Http/Middleware/EnsureTwilioRequestIsValid.php, app-modules/integration-twilio/tests/Tenant/Feature/Http/Middleware/EnsureTwilioRequestIsValidTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1085
Changes based on Twilio docs to try and fix validation.
No
No
=> [ADVAPP-1085]: Update to try and fix Twilio validation

app-modules/integration-twilio/src/Http/Middleware/EnsureTwilioRequestIsValid.php, composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1085
Updates the Twilio SDK and adds additional logging if signature validation fails.
No
No
=> [ADVAPP-1085]: Twilio SDK Upgrade and Signature Validation logging

app-modules/ai/tests/Tenant/Feature/Actions/SendMessageTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1243
Refactor the test to resolve the flakiness issue.
No
No
=> [ADVAPP-1243]: Resolve flaky test in SendMessageTest

app-modules/ai/database/factories/AiThreadFolderFactory.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1177
Resolves flaky tests by preventing unique collisions with folder names.
No
No
=> [ADVAPP-1177]: Resolve flaky test in app-modules/ai/tests/Feature/Filament/Pages/AIAssistantPageTest.php:503

app-modules/form/database/migrations/2024_11_06_145142_add_generate_prospects_to_forms_table.php, app-modules/form/src/Filament/Resources/FormResource/Pages/Concerns/HasSharedFormConfiguration.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1013
> Form submission Prospect generation improvements
> No
> No
=> [ADVAPP-1013]: Form submission Prospect generation improvements

composer.json
- https://canyongbs.atlassian.net/browse/ADVAPP-1230
> Update license from MIT to Elastic-2.0 in composer.json
>No.
> No.
=> [ADVAPP-1230]: Update the license in the composer.json

app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1240
> Relocate Cognitive Services to Artificial Intelligence Navigation.
> No.
> No.
=> [ADVAPP-1240]: Relocate Cognitive Services to Artificial Intelligence Navigation

app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php, app-modules/authorization/src/Filament/Pages/ManageGoogleSsoSettings.php, app-modules/multifactor-authentication/src/Filament/Pages/ManageMultifactorSettings.php, app-modules/multifactor-authentication/src/Settings/MultifactorSettings.php, app/Filament/Clusters/Authentication.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1236
> This PR contains the work of all 3 tickets as they are related: ADVAPP-1236. ADVAPP-1235, ADVAPP-1239 
> Change multifactor navigation label to Authentication
> Make third level navigation for Authentication Navigation group:
1.  Local Authentication
-      Multifactor
2. Single Sign-On (SSO)
-     Azure
-     Google
> No
> No
=> [ADVAPP-1236]: Relocate Manage Multifactor Settings to Dedicated Multifactor Page

composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1217
Resolves the `CVE-2021-44906` security vulnerability in our container by patching `spatie/laravel-health` to the commit where the underlying dependencies are updated. This is a temporary fix until they make an official release making this change.
No
No
=> [ADVAPP-1217]: Resolve the security issue tracked under CVE-2021-44906

portals/resource-hub/vite.config.js, widgets/application/vite.config.js, widgets/case-feedback-form/vite.config.js, widgets/case-form/vite.config.js, widgets/event-registration/vite.config.js, widgets/form/vite.config.js, widgets/survey/vite.config.js
- https://canyongbs.atlassian.net/browse/ADVAPP-1246
Fixes issue with portal and widget stylesheet generation.
No
No
=> [ADVAPP-1246]: Portal and widget stylesheets not generating properly

app-modules/prospect/src/Imports/ProspectImporter.php, app-modules/student-data-model/src/Filament/Imports/StudentImporter.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1256
In preparation for ADVAPP-1152, start tracking the batch name for student and prospect imports.
No
No
=> [ADVAPP-1256]: Improve tracking of student and prospect import job batches

app/Models/User.php, app/Observers/UserObserver.php, database/migrations/2025_03_04_230535_data_remove_licenses_from_soft_deleted_users.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1215
Add Observer to User model to force delete license and detach roles upon User deletion. Add migration to delete any currently orphaned licenses.
No
database/migrations/2025_03_04_230535_data_remove_licenses_from_soft_deleted_users.php
=> [ADVAPP-1215] When a user is deleted, automatically remove any licenses activated and detach any roles assigned to that user

resources/lang/vendor/filament-actions/en/import.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1233
Standardize import button labels across student profile, prospects, tasks, and users
No
No
=> [ADVAPP-1233]: Standardize import button labels across student profile, prospects, tasks, and users

app-modules/prospect/src/Filament/Resources/ProspectResource/Schemas/ProspectProfileInfolist.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php, composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1268
Do not show button when editing is not disabled.
No
No
=> [ADVAPP-1268]: Fix issue with student and prospect edit button being displayed at the wrong time, which links to a forbidden page error

app/Filament/Pages/AmazonS3.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1264
> Improve display of core integration settings for file storage for global administrators.
>No.
>No.
=> [ADVAPP-1264]: Improve display of core integration settings for file storage for global administrators.

app/Http/Controllers/UtilizationMetricsApiController.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1271
> Add support for email and sms usage to Advising App Olympus stats API endpoint
> No
> No
=> [ADVAPP-1271]: Add support for email and sms usage to Advising App Olympus stats API endpoint

composer.json
- https://canyongbs.atlassian.net/browse/ADVAPP-921
Update prettier command to be enforced on files within `resources/views/vendor` directory.
No
No
=> [ADVAPP-921] Enforce our styling consistently in the underlying codebase

app-modules/engagement/src/Jobs/ProcessSesS3InboundEmail.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1285
Fixes inbound email matching to work with the changes to the storage of email addresses in a related Model.
No
No
=> [ADVAPP-1285]: Inbound emails will fail to match to a Student or Prospect due to the email storage changing

app-modules/engagement/src/Jobs/ProcessSesS3InboundEmail.php
- N/A
Merges hotfix `1.57.1` back into `main`
No
No
=> [Hotfix]: 1.57.1

app-modules/engagement/src/Filament/Actions/MessageCenterSendEngagementAction.php, app-modules/engagement/src/Filament/Actions/RelationManagerSendEngagementAction.php, app-modules/engagement/src/Models/Engagement.php, composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1279
Implement merge variables for the user's full name, job title, email, and phone across student and prospect engagements, and message center.
No
No
=> [ADVAPP-1279]: Enhance the email system by adding merge values, allowing users to insert their personal information into outgoing messages

app-modules/interaction/database/migrations/2025_03_17_170737_update_unique_key_in_interaction_outcomes_table.php, app-modules/interaction/database/migrations/2025_03_18_181259_update_unique_key_in_interaction_relations_table.php, app-modules/interaction/database/migrations/2025_03_18_181747_update_unique_key_in_interaction_statuses_table.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1263
When attempting to delete interaction in bulk, it generates an error.
As we decide in Software Development Office Hours meeting, I am giving here list of other table which has same unique key which i think also needs to update.
1) interaction_relations
2) interaction_statuses
No
No
=> [ADVAPP-1263]: When attempting to delete interaction in bulk, it generates an error

app/Features/EmailSignature.php, app/Filament/Pages/EditProfile.php, app/Models/User.php, config/filament-tiptap-editor.php, database/migrations/2025_03_17_072936_add_signature_columns_to_users_table.php, database/migrations/2025_03_17_112122_data_activate_feature_flag_email_signature.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1280
> Add email signature feature with migration and editor integration
> No
> Yes. `EmailSignature`
=> [ADVAPP-1280]: Enable creation and storage of customizable email signatures with text and image support for messaging

app-modules/authorization/src/Http/Controllers/SocialiteController.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1281
Only throw an HTTP call Exception if it fails and is not a 404. If it is a 404 then we know the image has just not been found at Azure. Which we can ignore.
No
No
=> [ADVAPP-1281]: Azure profile image retrieval failures are generating exceptions

_ide_helper_models.php, app-modules/notification/src/Models/StoredAnonymousNotifiable.php, app-modules/report/src/Filament/Pages/StudentDeliverabilityReport.php, app-modules/report/src/Filament/Widgets/MostEngagedProspectsTable.php, app-modules/report/src/Filament/Widgets/PieChartReportWidget.php, app-modules/report/src/Filament/Widgets/StudentDeliverableTable.php, app-modules/report/src/Filament/Widgets/StudentEmailOptInOptOutPieChart.php, app-modules/report/src/Filament/Widgets/StudentSmsOptInOptOutPieChart.php, app-modules/report/tests/Tenant/Unit/StudentDeliverabilityReport/StudentDeliverabilityReportTest.php, app-modules/student-data-model/src/Models/Student.php, resources/views/advising-report/filament/pages/student-deliverability-report.blade.php
…on preferences
- https://canyongbs.atlassian.net/browse/ADVAPP-1287
> Introduce a new messaging deliverability report for students.
> No.
> No.
=> [ADVAPP-1287]: Introduce a new messaging deliverability report for students

app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1301
> Selecting a conversation within message center throws error..
> No.
> No.
=> [ADVAPP-1301]: Selecting a conversation within message center throws error.

app-modules/student-data-model/src/Filament/Actions/ImportStudentDataAction.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1315
> CSV extract examples for record sync fail to download
> No
> No
=> [ADVAPP-1315]: CSV extract examples for record sync fail to download

app-modules/prospect/src/Filament/Resources/ProspectResource/Tables/ProspectsTable.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1306
> Enhance segmentation of prospects by targeting subscribed prospects
> No
> No
=> [ADVAPP-1306]: Enhance segmentation of prospects by targeting subscribed prospects

app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1307
> Enhance segmentation options for building prospect segments to include support for SMS output and Email bounce
> No
> No
=> [ADVAPP-1307]: Enhance segmentation options for buidling prospect segments to include support for targeting engagement deliverability

stubs/migration.create.stub, stubs/migration.stub, stubs/migration.update.stub
- https://canyongbs.atlassian.net/browse/ADVAPP-1295
> Overwrite the migration stub to use the tpetry/laravel-postgresql-enhanced classes
> No
> No
=> [ADVAPP-1295]: Overwrite the migration stub to use the tpetry/laravel-postgresql-enhanced classes

app-modules/engagement/src/Notifications/EngagementNotification.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1322
If demo mode and demo mode auto reply is turned on, this will now trigger the creation of an Engagement Response when Engagements are sent via the SMS channel.
It is created with a `sent_at` of a few seconds from the current time so that it shows up in the list / timeline after the sent message.
This is technically a bugfix since this was expected functionality that was accidentally removed during the Engagements refactor
No
No
=> [ADVAPP-1322]: Demo mode for text messages fails to simulate a text message reply

phpstan.neon.dist
- https://canyongbs.atlassian.net/browse/ADVAPP-1328
Until all linting is fixed we will ignore this for now.
No
No
=> [ADVAPP-1328]: Disable error report of unmatched ignored errors

app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1317
> Update the role search functionality to not be case-sensitive when typing to attach a role
> No.
> No.
=> [ADVAPP-1317]: Update the role search functionality to not be case-sensitive when typing to attach a role

composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1359
Update canyongbs/common to version 1.1.1
No
No
=> Update common package version to ^1.1.1 in composer files

Dockerfile
- https://canyongbs.atlassian.net/browse/ADVAPP-1358
Update RoadRunner binary
No
No
=> [ADVAPP-1358]: Update RoadRunner binary

app-modules/prospect/database/factories/PipelineStageFactory.php, app-modules/prospect/src/Console/Commands/PruneEducatablePipelineStages.php, app-modules/prospect/src/Jobs/PruneEducatablePipelineStagesForPipeline.php, app-modules/prospect/src/Models/EducatablePipelineStage.php, app-modules/prospect/src/Models/PipelineStage.php, app-modules/prospect/tests/Tenant/Jobs/PruneEducatablePipelineStagesForPipelineTest.php, app-modules/segment/src/Actions/TranslateSegmentFilters.php, app/Console/Kernel.php
- https://canyongbs.atlassian.net/browse/ADVAPP-999
Introduces command to dispatch jobs to delete irrelevant records outside of the current segment.
No
No
=> [ADVAPP-999]: Implement pruning for pipeline-educatable pivot records

app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ListCases.php, app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ViewCase.php, app-modules/case-management/src/Policies/CaseModelPolicy.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1302
> Certain development environments are generating an exception when navigating to cases
> No
> No
=> [ADVAPP-1302]: Certain development environments are generating an exception when navigating to cases

app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1384
Update the label used in the create and edit student forms to state High School Graduation Year
No
No
=> [ADVAPP-1384]: Update the label used in the create and edit student forms to state High School Graduation Year

package-lock.json, package.json
- https://canyongbs.atlassian.net/browse/ADVAPP-1383
Resolve the security issue tracked under CVE-2025-32395
No
No
=> [ADVAPP-1383]: Resolve the security issue tracked under CVE-2025-32395

Dockerfile
- https://canyongbs.atlassian.net/browse/ADVAPP-1387
> Upgrade for nodejs/node and fix ENV definition
> Need to rebuild docker images because i have updated the node version from `23.4.0` to `23.11.0`
> No
=> Upgrade for nodejs/node and fix ENV definition

app-modules/prospect/src/Filament/Pages/RecruitmentCrmDashboard.php, app-modules/student-data-model/src/Filament/Pages/RetentionCrmDashboard.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1394
Rename My Dashboard to Action Center in the Retention CRM and Recruitment CRM module navigation
No
No
=> [ADVAPP-1394]: Rename My Dashboard to Action Center in the Retention CRM and Recruitment CRM module navigation

app-modules/student-data-model/database/migrations/2025_04_22_173836_add_gender_column_in_students_table.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php, app-modules/student-data-model/src/Models/Student.php, app/Features/StudentGender.php, database/migrations/2025_04_23_133144_data_activate_feature_flag_student_gender.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1398
> Expand the data model for students to include gender
> No
> StudentGender
=> [ADVAPP-1398]: Expand the data model for students to include gender

docker/scheduler/s6-overlay/scripts/cron
- https://canyongbs.atlassian.net/browse/ADVAPP-1419
Adjusts the scheduler process to make sure needed ENV variables are loaded.
No
No
=> [ADVAPP-1419]: Scheduler throws a memory error due to ENV vars not properly being passed to cron

app/Providers/AppServiceProvider.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1423
> Remove 'all' option from `per page` dropdown in all pages.
> No
> No
=> [ADVAPP-1423]: Optimize per page display options for list views

app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1400
Add a filter for students by ethnicity.
No
No
=> [ADVAPP-1400]: Add a segmentation rule to allow institutions to select students by ethnicity

app-modules/engagement/resources/views/components/message-center-content.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1425
> Remove chain icon and make name into hyperlink in message center.
> No
> No
=> [ADVAPP-1425]: Improve consistency in the display of the student hyperlink

package-lock.json
- https://canyongbs.atlassian.net/browse/ADVAPP-1420
Updates `esbuild` to [v0.25.3](https://github.com/evanw/esbuild/releases/tag/v0.25.3) so that we get a patch for https://github.com/advisories/GHSA-g9pc-8g42-g6vq
No
No
=> [ADVAPP-1420]: Resolve the security issue tracked under CVE-2025-22871

app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EnrollmentsRelationManager.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1352
> Update enrollment view in the holistic student profile to show the course name, course, section, grade, and semester name.
> No.
> No.
=> [ADVAPP-1352]: Update enrollment view in the holistic student profile to show the course name, course, section, grade, and semester name

app/Providers/Filament/AdminPanelProvider.php, resources/views/components/about-modal.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1417
> Introduce an about link in the profile dropdown that displays the product's version information.
> No
> No
=> [ADVAPP-1417]: Introduce an about link in the profile dropdown that displays the product's version information

app-modules/ai/src/Enums/AiApplication.php, app-modules/ai/src/Filament/Resources/AiAssistantResource/Concerns/HandlesFileUploads.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1428
- Adds 4oMiniService to HandlesFileUploads.php
- No
- No
=> [ADVAPP-1428] : 4oMini support for file uploads

app-modules/resource-hub/src/Filament/Resources/ResourceHubArticleResource/Pages/ListResourceHubArticles.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1433
> Make articles in resource hub open in View mode to improve accessibility.
> No.
> No.
=> [ADVAPP-1433]: Make articles in resource hub open in View mode to improve accessibility.

app-modules/ai/src/Filament/Pages/ManageAiIntegratedAssistantSettings.php, app-modules/ai/src/Filament/Pages/ManageAiSettings.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1464
> Updated the navigation menu in Global Administration to reflect the updated naming for AI features
> No.
> No.
=> [ADVAPP-1464]: Update the navigation menu in Global Administration to reflect the updated naming for AI features

package-lock.json, package.json
- https://canyongbs.atlassian.net/browse/ADVAPP-1470
Update `vite` to [v6.3.4](https://github.com/vitejs/vite/releases/tag/v6.3.4)
No
No
=> [ADVAPP-1470]: Resolve the security issue tracked under CVE-2025-46565

app-modules/ai/database/migrations/2025_05_02_162717_add_ai_integration_settings_model_name_settings.php, app-modules/ai/src/Enums/AiModel.php, app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php, app-modules/ai/src/Settings/AiIntegrationsSettings.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1463
Add the ability to configure the Model Name that is displayed in various labels within cognitive services.
No
No
=> [ADVAPP-1463]: Introduce the ability to configure a large language model name throughout the application

_ide_helper_models.php, app-modules/campaign/database/migrations/2025_04_30_184241_add_cancelled_at_in_campaign_actions_table.php, app-modules/campaign/src/Actions/ExecuteCampaignAction.php, app-modules/campaign/src/Actions/ExecuteCampaignActions.php, app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php, app-modules/campaign/src/Models/CampaignAction.php, app-modules/campaign/src/Models/Scopes/CampaignActionNotCancelled.php, app/Features/CancelCampaignAction.php, app/Models/Scopes/CampaignActionNotCancelled.php, database/migrations/2025_05_02_125848_data_activate_cancel_campaign_action_feature_flag.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1431
> Allow cancelation of campaign journey steps that have not executed yet
> No
> CancelCampaignAction
=> [ADVAPP-1431]: Allow cancelation of campaign journey steps that have not executed yet

.env.example, app-modules/ai/database/migrations/2025_05_06_061948_add_open_ai_gpt_o4_mini_settings.php, app-modules/ai/database/migrations/2025_05_06_105028_data_activate_gpt_o4_mini_feature.php, app-modules/ai/src/Enums/AiApplication.php, app-modules/ai/src/Enums/AiModel.php, app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php, app-modules/ai/src/Filament/Resources/AiAssistantResource/Concerns/HandlesFileUploads.php, app-modules/ai/src/Settings/AiIntegrationsSettings.php, app-modules/integration-open-ai/config/integration-open-ai.php, app-modules/integration-open-ai/src/Services/OpenAiGptO4MiniService.php, app/Features/GPTO4MiniFeature.php
- https://canyongbs.atlassian.net/browse/ADVAPP-
> Introduce support for the latest reasoning large language model to extend the capabilities of our artificial intelligence features
> Add the following keys to the `.env.example` file:
```
OPEN_AI_GPT_O4_MINI_BASE_URI=
OPEN_AI_GPT_O4_MINI_API_KEY=
OPEN_AI_GPT_O4_MINI_API_VERSION=2025-04-16-preview
OPEN_AI_GPT_O4_MINI_MODEL=
```
> Yes, `GPTO4MiniFeature`
=> [ADVAPP-1449]: Introduce support for the latest reasoning large language model to extend the capabilities of our artificial intelligence features

app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableTasks.php, app-modules/task/src/Filament/RelationManagers/BaseTaskRelationManager.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1457
> Enhance the ability to sort tasks in action center, on the student and prospect record pages, and in the main tasks navigation.
> No.
> No.
=> [ADVAPP-1457]: Enhance the ability to sort tasks in action center, on the student and prospect record pages, and in the main tasks navigation

app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ListRoles.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1462
> Ensure that role duplication is not applied inappropriately to restricted roles.
> No.
> No.
=> [ADVAPP-1462]: Ensure that role duplication is not applied inappropriately to restricted roles.

Dockerfile
- N/A
Removes `--no-suggest` from composer commands and fixes permissions during Docker setup.
No
No
=> [Bugfix] Docker build fixes

app/Filament/Pages/EditProfile.php, resources/css/filament/admin/theme.css
- https://canyongbs.atlassian.net/browse/ADVAPP-1414
> Improve user experience by simplifying the process of setting up working hours in user profile by reducing repetitive typing and clicks
> No
> No
=> [ADVAPP-1414]: Improve user experience by simplifying the process of setting up working hours in user profile by reducing repetitive typing and clicks

app-modules/authorization/src/Console/Commands/SetupRoles.php, app/Listeners/InformOlympusOfDeploymentEvent.php, app/Providers/EventServiceProvider.php, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1495
Sends an API call to Olympus when a Tenant successfully deploys.
Works with https://github.com/canyongbs/olympus/pull/514
No
No
=> [ADVAPP-1495]: Inform Olympus of successful Tenant deployment

app-modules/report/src/Filament/Widgets/ProspectReportLineChart.php, app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1509
> Some users have reported that they are seeing unexpected cumulative visualizations in the student and prospect overview report
> No
> No
=> [ADVAPP-1509]: Some users have reported that they are seeing unexpected cumulative visualizations in the student and prospect overview report

app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php, app/Filament/Tables/Filters/QueryBuilder/Constraints/ExistingValuesSelectConstraint.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1504
> Add 'First Enrolled Semester' filter to StudentsTable and order existing values
> No.
> No.
=> [ADVAPP-1504]: Introduce the ability to create a segment based on the first enrolled semester for a student

app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1505
> Introduce the ability to create a segment based on the most recent enrolled semester or a student.
> No.
> No.
=> [ADVAPP-1505]: Introduce the ability to create a segment based on the most recent enrolled semester or a student

app-modules/ai/database/migrations/2025_05_19_214332_seed_permissions_add_research_advisor_permission.php, app-modules/research/src/Filament/Pages/ManageResearchRequests.php, app-modules/research/src/Filament/Pages/NewResearchRequest.php, app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php, app/Enums/Feature.php, app/Filament/Pages/ManageLicenseSettings.php, app/Http/Requests/Tenants/CreateTenantRequest.php, app/Http/Requests/Tenants/SyncTenantRequest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1473
- Add Research Advisor permissions
- Add a toggle for Research Advisor
- Add Research Advisor feature.
- No
- No 
=> [ADVAPP-1473] - Add Research Advisors Permissions

app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
- N/A
Merge of hotfix `1.68.1` back into `main`.
No
No
=> [Hotfix]: 1.68.1

app-modules/alert/src/Observers/AlertObserver.php, app-modules/application/src/Observers/ApplicationSubmissionObserver.php, app-modules/form/src/Filament/Resources/FormResource/Pages/ManageFormSubmissions.php, app-modules/form/src/Listeners/ClearAuthorFormSubmissionCountCache.php, app-modules/form/src/Listeners/ClearFormFormSubmissionCountCache.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php, app-modules/prospect/src/Observers/ProspectObserver.php, app-modules/report/src/Filament/Widgets/AiStats.php, app-modules/report/src/Filament/Widgets/ExchangesByMonthLineChart.php, app-modules/report/src/Filament/Widgets/PromptsByCategoryDoughnutChart.php, app-modules/report/src/Filament/Widgets/PromptsCreatedLineChart.php, app-modules/report/src/Filament/Widgets/ProspectEngagementLineChart.php, app-modules/report/src/Filament/Widgets/ProspectEngagementState.php, app-modules/report/src/Filament/Widgets/ProspectReportLineChart.php, app-modules/report/src/Filament/Widgets/ProspectReportStats.php, app-modules/report/src/Filament/Widgets/RefreshWidget.php, app-modules/report/src/Filament/Widgets/SpecialActionsDoughnutChart.php, app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php, app-modules/report/src/Filament/Widgets/StudentEmailOptInOptOutPieChart.php, app-modules/report/src/Filament/Widgets/StudentEngagementLineChart.php, app-modules/report/src/Filament/Widgets/StudentEngagementStats.php, app-modules/report/src/Filament/Widgets/StudentSmsOptInOptOutPieChart.php, app-modules/report/src/Filament/Widgets/StudentsStats.php, app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php, app-modules/report/src/Filament/Widgets/TaskStats.php, app-modules/report/src/Filament/Widgets/UserUniqueLoginCountLineChart.php, app-modules/report/src/Filament/Widgets/UsersStats.php, app/Filament/Widgets/ProspectGrowthChart.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1496
> Ensure all usage of Cache::tags apply Redis "hash tags" to the tag.
> No
> No
=> [ADVAPP-1496]: Ensure all usage of Cache::tags apply Redis "hash tags" to the tag

app-modules/ai/src/Filament/Pages/QnAAdvisors.php, app-modules/ai/src/Filament/Resources/AiAssistantResource.php, app-modules/research/src/Filament/Pages/ManageResearchRequests.php, app-modules/research/src/Filament/Pages/NewResearchRequest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1530
> Update the name and IA ordering for the Research Advisor in the primary navigation menu.
> No.
> No.
=> [ADVAPP-1530]: Update the name and IA ordering for the Research Advisor in the primary navigation menu

_ide_helper_models.php, app-modules/campaign/database/migrations/2025_05_29_121701_data_activate_campaign_email_images_feature.php, app-modules/campaign/src/Enums/CampaignActionType.php, app-modules/campaign/src/Filament/Blocks/CampaignActionBlock.php, app-modules/campaign/src/Filament/Blocks/EngagementBatchEmailBlock.php, app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php, app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php, app-modules/campaign/src/Jobs/EngagementCampaignActionJob.php, app-modules/campaign/src/Models/CampaignActionEducatableRelated.php, app-modules/engagement/database/migrations/2025_05_29_121621_add_campaign_action_id_column_to_engagements_table.php, app-modules/engagement/src/Actions/CreateEngagement.php, app-modules/engagement/src/DataTransferObjects/EngagementCreationData.php, app-modules/engagement/src/Models/Engagement.php, app/Features/CampaignEmailImages.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1516
Saves campaign action images to the action object, and saves a reference to the action to the engagement so it can be used to retrieve media when it is sent.
No
`CampaignEmailImages`
`app-modules/campaign/database/migrations/2025_05_29_121701_data_activate_campaign_email_images_feature.php`
=> [ADVAPP-1516]: Some users have reported that journey steps that include images may not always save or send properly

app-modules/engagement/src/Models/Engagement.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1561
Fixes an issue with Engagement subject and body generation.
No
No
=> [ADVAPP-1561]: Recent changes to Engagement subject and body generation throw errors

app-modules/care-team/src/Filament/Actions/AddCareTeamMemberAction.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1548
- Change label
- No
- No
=> [ADVAPP-1548]: Update Label from 'Add Care Team Member' to 'Manage Care Team'

app-modules/research/resources/js/results.js, app-modules/research/resources/views/filament/pages/manage-research-requests.blade.php, app-modules/research/resources/views/results.blade.php, bin/build.js, package-lock.json, package.json, resources/css/filament/admin/theme.css
- https://canyongbs.atlassian.net/browse/ADVAPP-1532
Adjusts the UI and rendered streaming of the Research Assistant.
No
No
=> [ADVAPP-1532]: Update the core UI/UX experience for the Research Advisor

app-modules/report/src/Filament/Widgets/ProspectReportLineChart.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1582
Improve the display of the prospect overview report in the report library
No
No
=> [ADVAPP-1582]: Improve the display of the prospect overview report in the report library

app-modules/report/src/Filament/Widgets/ProspectInteractionStats.php, app-modules/report/src/Filament/Widgets/StudentInteractionStats.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1580
> Improve the display of the cards on the interaction report.
> No.
> No.
=> [ADVAPP-1580]: Improve the display of the cards on the interaction report

app-modules/alert/src/Filament/Actions/BulkCreateAlertAction.php, app-modules/case-management/src/Filament/Actions/BulkCreateCaseAction.php, app-modules/interaction/src/Filament/Actions/BulkCreateInteractionAction.php, app-modules/notification/src/Filament/Actions/SubscribeBulkAction.php, app-modules/prospect/src/Filament/Actions/ProspectTagsBulkAction.php, app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php, app-modules/segment/src/Actions/BulkSegmentAction.php, app-modules/student-data-model/src/Filament/Actions/StudentTagsBulkAction.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1584
> Enhance the organization and naming of bulk actions in student and prospect list views.
> No.
> No.
=> [ADVAPP-1584]: Enhance the organization and naming of bulk actions in student and prospect list views.

package-lock.json
- https://canyongbs.atlassian.net/browse/ADVAPP-1586
Update `brace-expansion` in the package lock file to non-vulnerable versions.
No
No
=> [ADVAPP-1586]: Resolve the security issue tracked under CVE-2025-5889

app-modules/prospect/src/Models/Prospect.php, app-modules/student-data-model/src/Models/Contracts/Educatable.php, app-modules/student-data-model/src/Models/Student.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1518
Fix the relationship between Student/Prospect and EventAttendee.
No
No
=> [ADVAPP-1518]: Event Management was broken by the changing of Student and Prospect email storage

app-modules/engagement/resources/views/components/message-center-content.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1571
- Add `underline` Tailwind class to Display Name
- No
- No
=> [ADVAPP-1571] - Underline Display Name

app/Filament/Pages/ArtificialIntelligence.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1604
> Improve messaging location for profile setting information related to Artificial Intelligence
> No
> No
=> [ADVAPP-1604]: Improve messaging location for profile setting information related to Artificial Intelligence

_ide_helper_models.php, app/Features/ActionCenterUpdateFeatureFlag.php, app/Filament/Pages/ArtificialIntelligence.php, app/Models/User.php, database/migrations/2025_06_23_094150_add_is_action_center_update_enabled_column_in_users_table.php, database/migrations/2025_06_23_094150_add_is_action_center_updated_column_in_users_table.php, database/migrations/2025_06_23_095616_data_activate_action_center_update_feature_flag.php.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1605
> Introduce a new setting under /profile-settings/artificial-intelligence: Action Center Update
> No
> ActionCenterUpdateFeatureFlag
=> [ADVAPP-1605]: Provide a new setting for Action Center daily update for users by the institutional assistant

app-modules/ai/src/Models/Concerns/CanAddAssistantLicenseGlobalScope.php, app-modules/campaign/src/Jobs/EngagementCampaignActionJob.php, app-modules/campaign/src/Jobs/ExecuteCampaignAction.php, app-modules/campaign/src/Models/Campaign.php, app-modules/prospect/src/Models/Prospect.php, app-modules/segment/src/Models/Segment.php, app-modules/student-data-model/src/Models/Student.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1595
Fixes issues with different global scoping and error catches that could have caused this issue.
No
No
=> [ADVAPP-1595]: EngagementCampaignActionJob threw an Exception about the educatable not being the correct class

app-modules/report/src/Filament/Resources/ReportResource.php, app/Filament/Clusters/ReportLibrary.php, app/Filament/Clusters/UsageAuditing.php, app/Providers/Filament/AdminPanelProvider.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1674
> Rename reporting navigation to Analytics. 
> No
> No
=> [ADVAPP-1674]: Improve the naming of the analytics in the main navigation

app-modules/prospect/src/Filament/Resources/ProspectResource.php, app-modules/student-data-model/src/Filament/Pages/ManageStudentSyncs.php, app-modules/student-data-model/src/Filament/Resources/StudentResource.php, app/Providers/Filament/AdminPanelProvider.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1672
> Simplify the CRM navigation in the application by combining the main navigation group for retention and recruitment.
> No.
> No.
=> [ADVAPP-1672]: Simplify the CRM navigation in the application by combining the main navigation group for retention and recruitment

app-modules/prospect/src/Filament/Resources/ProspectResource.php, app-modules/student-data-model/src/Filament/Resources/StudentResource.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1708
> Relocate Prospects in the list below Students for a more natural flow in the main navigation menu.
> No.
> No.
=> [ADVAPP-1708]: Relocate Prospects in the list below Students for a more natural flow in the main navigation menu

app-modules/ai/resources/views/components/assistant.blade.php, app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php, app-modules/ai/src/Services/Contracts/AiServiceLifecycleHooks.php, app-modules/ai/tests/Tenant/Feature/Filament/Pages/AIAssistantPageTest.php, app-modules/integration-open-ai/src/Services/Concerns/UploadsFiles.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1696
> Improve the user experience when loading the institutional advisor
> No
> No
=> [ADVAPP-1696]: Improve the user experience when loading the institutional advisor

composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1715
Updates filament tiptap editor plugin where security vulnerability is resolved.
No
No
=> [ADVAPP-1715]: Update filament tiptap plugin

app-modules/case-management/src/Filament/Resources/CaseResource.php, app-modules/case-management/src/Filament/Resources/CaseResource/Pages/Concerns/HasCaseRecordHeader.php, app-modules/report/src/Abstract/Concerns/HasFiltersForm.php, app-modules/report/src/Filament/Pages/ProspectCaseReport.php, app-modules/report/src/Filament/Pages/StudentCaseReport.php, app-modules/report/src/Filament/Widgets/ProspectCaseStats.php, app-modules/report/src/Filament/Widgets/ProspectCaseTable.php, app-modules/report/src/Filament/Widgets/StudentCaseStats.php, app-modules/report/src/Filament/Widgets/StudentCaseTable.php, app-modules/report/tests/Tenant/Filament/Widgets/ProspectCaseStatsTest.php, app-modules/report/tests/Tenant/Filament/Widgets/ProspectCaseTableTest.php, app-modules/report/tests/Tenant/Filament/Widgets/StudentCaseStatsTest.php, app-modules/report/tests/Tenant/Filament/Widgets/StudentCaseTableTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1675
- https://canyongbs.atlassian.net/browse/ADVAPP-1676
> Introduce case management reports for students and prospects
> No
> No
=> [ADVAPP-1675][ADVAPP-1676]: Introduce case management reports for students and prospects

app-modules/ai/resources/js/qna-advisor-preview.js, app-modules/ai/resources/views/filament/resources/qna-advisors/pages/preview-qna-advisor.blade.php, app-modules/ai/routes/web.php, app-modules/ai/src/Filament/Resources/QnaAdvisorResource.php, app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/PreviewQnaAdvisor.php, app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/QnaAdvisorEmbed.php, app-modules/ai/src/Http/Controllers/QnaAdvisors/SendMessageController.php, app-modules/ai/src/Services/Contracts/AiService.php, app-modules/ai/src/Services/TestAiService.php, app-modules/integration-open-ai/src/Prism/AzureOpenAi/Handlers/Stream.php, app-modules/integration-open-ai/src/Services/BaseOpenAiResponsesService.php, app-modules/integration-open-ai/src/Services/BaseOpenAiService.php, vite.config.js
- https://canyongbs.atlassian.net/browse/ADVAPP-1698
Implements a new Preview page for the advisor, where you can interact with a temporary chat for that advisor, with all the knowledge.
No
No
=> [ADVAPP-1698]: Implement chat preview in the QnA advisor

app-modules/ai/src/Actions/SendMessage.php, app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManagePromptLibrary.php, app-modules/ai/tests/Tenant/Feature/Filament/Pages/AIAssistantPageTest.php, app-modules/research/src/Jobs/GenerateResearchRequestSection.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1722
Moves usage recording logic to send message controller, so any method of sending a prompt is captured.
No
No
=> [ADVAPP-1722]: New Smart Prompt tile interface usage does not record as a "use"

config/octane.php
- N/A
Merges changes from hotfix release `1.79.3` back into `main`.
No
No
=> [Hotfix]: 1.79.3

_ide_helper_models.php, app-modules/project/src/Models/Project.php, app-modules/student-data-model/database/factories/StudentFactory.php, app-modules/student-data-model/database/migrations/2025_08_08_063630_add_athletics_fields_to_students_table.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php, app-modules/student-data-model/src/Models/Student.php, app/Features/AthleticFieldsFeature.php, database/migrations/2025_08_08_082729_data_activate_athletic_fields_feature.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1798
> Enhance the data model for students by including a new field for athletics status and athletic details
> No
> Yes. Feature Flag: `AthleticFieldsFeature`
=> [ADVAPP-1798]: Enhance the data model for students by including a new field for athletics status and athletic details

app-modules/student-data-model/src/Actions/CompleteStudentDataImport.php, app-modules/student-data-model/src/Actions/CreateTemporaryStudentDataImportTables.php, app-modules/student-data-model/src/Filament/Imports/StudentImporter.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1804
Create a temporary table for care team assignments, insert them into the temporary table, then clear out any existing assignments and insert them in the same transaction.
No
No
=> [ADVAPP-1804]: Enhance the SIS sync records tool to allow care team assignments

_ide_helper_models.php, app-modules/student-data-model/database/factories/StudentFactory.php, app-modules/student-data-model/database/migrations/2025_08_11_153704_add_academic_standing_to_students_table.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php, app-modules/student-data-model/src/Models/Student.php, app/Features/AcademicStandingFeature.php, database/migrations/2025_08_11_155208_data_activate_academic_standing_feature.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1799
> Enhance the student data model with a value for academic standing
> No
> Yes. `AcademicStandingFeature`
=> [ADVAPP-1799]: Enhance the student data model with a value for academic standing

app-modules/meeting-center/src/Filament/Resources/CalendarEventResource.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1812
Relocate Schedule & Appointments to CRM navigation group
No
No
=> [ADVAPP-1812]: Relocate Schedule & Appointments from Premium Features to CRM at the end of the list

app-modules/basic-needs/src/Filament/Resources/BasicNeedsCategoryResource.php, app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1811
Relocate Programs to within Knowledge Management
No
No
=> [ADVAPP-1811]: Relocate Programs in Settings > Constituent Management > Programs to Knowledge Management > Support Programs

package-lock.json, package.json
- https://canyongbs.atlassian.net/browse/ADVAPP-1815
Update `esbuild` to resolve CVE-2025-47907.
No
No
=> [ADVAPP-1815]: Resolve the security issue tracked under CVE-2025-47907

_ide_helper_models.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/ProgramsRelationManager.php, app-modules/student-data-model/src/Models/Program.php, app/Features/CatalogYearFeature.php, database/migrations/2025_08_19_101757_add_catalog_year_in_programs_table.php, database/migrations/2025_08_19_114526_data_activate_catalog_year_feature_flag.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1800
> Enhance the programs data model by including the catalog year
> No
> CatalogYearFeature
=> [ADVAPP-1800]: Enhance the programs data model by including the catalog year

_ide_helper_models.php, app-modules/project/database/factories/ProjectMilestoneFactory.php, app-modules/project/database/factories/ProjectMilestoneStatusFactory.php, app-modules/project/database/migrations/2025_08_18_092846_create_project_milestone_statuses_table.php, app-modules/project/database/migrations/2025_08_18_101223_tmp_seed_data_project_milestone_statuses_seeder.php, app-modules/project/database/migrations/2025_08_18_122911_create_project_milestones_table.php, app-modules/project/database/migrations/2025_08_18_123212_data_activate_project_milestone_feature_flag.php, app-modules/project/database/seeders/ProjectMilestoneStatusSeeder.php, app-modules/project/src/Filament/Resources/ProjectMilestoneStatusResource.php, app-modules/project/src/Filament/Resources/ProjectMilestoneStatusResource/Pages/CreateProjectMilestoneStatus.php, app-modules/project/src/Filament/Resources/ProjectMilestoneStatusResource/Pages/EditProjectMilestoneStatus.php, app-modules/project/src/Filament/Resources/ProjectMilestoneStatusResource/Pages/ListProjectMilestoneStatuses.php, app-modules/project/src/Filament/Resources/ProjectMilestoneStatusResource/Pages/ViewProjectMilestoneStatus.php, app-modules/project/src/Filament/Resources/ProjectResource.php, app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageMilestones.php, app-modules/project/src/Models/Project.php, app-modules/project/src/Models/ProjectMilestone.php, app-modules/project/src/Models/ProjectMilestoneStatus.php, app-modules/project/src/Observers/ProjectMilestoneObserver.php, app-modules/project/src/Policies/ProjectMilestonePolicy.php, app-modules/project/src/Policies/ProjectMilestoneStatusPolicy.php, app-modules/project/src/Providers/ProjectServiceProvider.php, app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/ManageMilestonesTest.php, app/Features/ProjectMilestoneFeature.php, app/Filament/Clusters/ProjectManagement.php, database/seeders/NewTenantSeeder.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1756
> Introduce the concept of milestones inside of the project
> No
> ProjectMilestoneFeature
=> [ADVAPP-1756]: Introduce the concept of milestones inside of the project

app-modules/application/resources/views/preview.blade.php, app-modules/application/routes/api.php, app-modules/application/routes/web.php, app-modules/application/src/Filament/Resources/ApplicationResource/Pages/EditApplication.php, app-modules/application/src/Http/Controllers/ApplicationPreviewController.php, app-modules/application/src/Http/Controllers/ApplicationWidgetController.php, widgets/application/src/App.vue, widgets/application/src/widget.js
- https://canyongbs.atlassian.net/browse/ADVAPP-1826
> Add a preview mode for admissions applications
> No
> No
=> [ADVAPP-1826]: Add a preview mode for admissions applications

app-modules/project/src/Filament/Resources/ProjectResource.php, app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageTasks.php, app-modules/project/src/Models/Project.php, app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/ManageTasksTest.php, app-modules/task/database/migrations/2025_08_20_205946_add_project_id_to_tasks_table.php, app-modules/task/database/migrations/2025_08_20_210328_data_activate_associate_tasks_with_projects_feature_feature_flag.php, app-modules/task/src/Models/Task.php, app/Features/AssociateTasksWithProjectsFeature.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1757
Associate tasks with projects
No
AssociateTasksWithProjectsFeature feature flag
=> [ADVAPP-1757]: Introduce the ability to associate tasks with a project

app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php, app/Filament/Concerns/SemesterSelectForOperator.php, app/Filament/Tables/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/Concerns/SemesterSelectForOperator.php, app/Filament/Tables/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/EqualsOperatorWithEnrollmentSemester.php, app/Filament/Tables/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/HasMaxOperatorWithEnrollmentSemester.php, app/Filament/Tables/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/HasMinOperatorWithEnrollmentSemester.php, app/Filament/Tables/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/IsEmptyOperatorWithEnrollmentSemester.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1806
> Refactor Enrollment filter for segments to be Enrollment Count
> No
> No
=> [ADVAPP-1806]: Refactor Enrollment filter for segments to be Enrollment Count

app-modules/notification/src/Notifications/Channels/SmsChannel.php
- N/A
Fix the webhook for Telnyx status updates.
No
No
=> [Bugfix]: Fix Telnyx webhook

app-modules/notification/src/Notifications/Channels/SmsChannel.php
Fix Telnyx webhook
- N/A
Merges hotfix `1.85.1` changes into `main`.
No
No
=> [Hotfix]: 1.85.1

app-modules/campaign/src/Filament/Resources/CampaignResource.php, app-modules/engagement/src/Filament/Pages/MessageCenter.php, app-modules/meeting-center/src/Filament/Resources/CalendarEventResource.php, app-modules/report/src/Filament/Pages/TaskManagement.php, app-modules/report/src/Filament/Resources/ReportResource.php, app-modules/segment/src/Filament/Resources/SegmentResource.php, app-modules/student-data-model/src/Filament/Pages/ManageStudentSyncs.php, app/Filament/Clusters/ReportLibrary.php, app/Filament/Clusters/UsageAuditing.php, app/Providers/Filament/AdminPanelProvider.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1870
- Update AdminPanelServiceProvider to change the icons and order
- Update the various pages to reflect the new NavigationGroup and order
- No
- No
=> [ADVAPP-1870]: Update information architecture for primary navigation

app-modules/form/resources/views/blocks/submissions/upload.blade.php, app-modules/form/routes/api.php, app-modules/form/src/Actions/ProcessSubmissionField.php, app-modules/form/src/Filament/Blocks/FormFieldBlockRegistry.php, app-modules/form/src/Filament/Blocks/UploadFormFieldBlock.php, app-modules/form/src/Http/Controllers/FormWidgetController.php, app-modules/form/src/Models/FormFieldSubmission.php, app-modules/form/src/Providers/FormServiceProvider.php, package-lock.json, package.json, widgets/form/src/App.vue, widgets/form/src/FormKit/Inputs/Upload.vue, widgets/form/src/FormKit/Inputs/index.js
- https://canyongbs.atlassian.net/browse/ADVAPP-1825
> Introduce a file upload form field type
> No
> No
=> [ADVAPP-1825]: Introduce a file upload form field type

app-modules/ai/tests/Tenant/Feature/Filament/Pages/AIAssistantPageTest.php, app-modules/report/tests/Tenant/Filament/Widgets/ProspectReportStatsTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1899
Fix flaky test.
No
No
=> [ADVAPP-1899]: Fix flaky test that is blocking CI from passing in > 80% of runs

app-modules/case-management/src/Filament/Resources/CaseTypeResource/Pages/ManageCaseTypeEmailTemplate.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1760
> Some users are experiencing issues when configuring email templates for case types
> No
> No
=> [ADVAPP-1760]: Some users are experiencing issues when configuring email templates for case types

Dockerfile, app-modules/ai/resources/views/filament/resources/qna-advisors/pages/preview-qna-advisor.blade.php, app-modules/ai/src/Http/Middleware/EnsureQnaAdvisorEmbedIsEnabled.php, app-modules/ai/src/Http/Middleware/EnsureQnaAdvisorRequestComingFromAuthorizedDomain.php, app-modules/ai/src/Http/Middleware/QnaAdvisorAuthorization.php, app-modules/integration-open-ai/src/Services/BaseOpenAiService.php, composer.json, composer.lock
- N/A
Merge changes from hotfix `1.87.2` into `main`.
No
No
=> [Hotfix]: 1.87.2

app-modules/application/src/Filament/Resources/ApplicationResource/Pages/Concerns/HasSharedFormConfiguration.php, app-modules/application/src/Models/Application.php, app-modules/application/src/Models/ApplicationStep.php, app-modules/form/src/Actions/GenerateFormKitSchema.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1733
> Add the ability to insert images to the online admission application forms
> No
> No
=> [ADVAPP-1733]: Add the ability to insert images to the online admission application forms

app-modules/student-data-model/database/factories/EnrollmentSemesterFactory.php, app-modules/student-data-model/database/migrations/2025_09_17_120512_create_enrollment_semesters_table.php, app-modules/student-data-model/src/Filament/Resources/AdvisingApp/StudentDataModel/Models/EnrollmentSemesterResource.php, app-modules/student-data-model/src/Filament/Resources/AdvisingApp/StudentDataModel/Models/EnrollmentSemesterResource/Pages/ManageEnrollmentSemesters.php, app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EnrollmentsRelationManager.php, app-modules/student-data-model/src/Models/EnrollmentSemester.php, app-modules/student-data-model/src/Observers/EnrollmentSemesterObserver.php, app-modules/student-data-model/src/Policies/EnrollmentSemesterPolicy.php, app-modules/student-data-model/tests/Tenant/Filament/Resources/EnrollmentSemesterResource/Pages/ManageEnrollmentSemestersTest.php, app/Features/EnrollmentSemesterFeature.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1853
Introduces a new model & management interface for enrollment semesters. Orders the enrollments by the order of those semesters.
No
EnrollmentSemesterFeature
=> [ADVAPP-1853]: Enhance enrollment display in the student holistic profile by improving sorting

app-modules/ai/database/factories/AiAssistantConfidentialTeamFactory.php, app-modules/ai/database/factories/AiAssistantConfidentialUserFactory.php, app-modules/ai/database/migrations/2025_09_16_125400_create_ai_assistant_confidential_users_table.php, app-modules/ai/database/migrations/2025_09_16_125417_create_ai_assistant_confidential_teams_table.php, app-modules/ai/database/migrations/2025_09_17_130929_add_is_confidential_to_ai_assistants_table.php, app-modules/ai/database/migrations/2025_09_17_173300_data_activate_ai_assistant_confidential_feature.php, app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php, app-modules/ai/src/Models/AiAssistant.php, app-modules/ai/src/Models/AiAssistantConfidentialTeam.php, app-modules/ai/src/Models/AiAssistantConfidentialUser.php, app-modules/ai/src/Models/AiThread.php, app-modules/ai/src/Models/Scopes/AiAssistantConfidentialScope.php, app-modules/ai/src/Models/Scopes/AiAssistantScope.php, app-modules/ai/src/Models/Scopes/AiThreadScope.php, app-modules/ai/tests/Tenant/Models/Scopes/AiAssistantScopeTest.php, app/Features/AiAssistantConfidentialFeature.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1891
> Introduce the ability to configure confidential custom advisors
> No
> Yes, `AiAssistantConfidentialFeature`
=> [ADVAPP-1891]: Introduce the ability to configure confidential custom advisors

app-modules/ai/src/Models/AiAssistantConfidentialTeam.php, app-modules/ai/src/Models/AiAssistantConfidentialUser.php, app-modules/ai/src/Models/ConfidentialPromptTeam.php, app-modules/report/src/Abstract/ProjectManagementReport.php, app-modules/report/src/Filament/Pages/ArtificialIntelligence.php, app-modules/report/src/Filament/Pages/CustomAdvisorReport.php, app-modules/report/src/Filament/Pages/InstitutionalAdvisorReport.php, app-modules/report/src/Filament/Pages/ProjectReport.php, app-modules/report/src/Filament/Pages/ProspectCaseReport.php, app-modules/report/src/Filament/Pages/ProspectInteractionReport.php, app-modules/report/src/Filament/Pages/ProspectMessagesDetailReport.php, app-modules/report/src/Filament/Pages/ProspectMessagesOverviewReport.php, app-modules/report/src/Filament/Pages/ProspectReport.php, app-modules/report/src/Filament/Pages/QnaAdvisorReport.php, app-modules/report/src/Filament/Pages/ResearchAdvisorReport.php, app-modules/report/src/Filament/Pages/StudentCaseReport.php, app-modules/report/src/Filament/Pages/StudentDeliverabilityReport.php, app-modules/report/src/Filament/Pages/StudentInteractionReport.php, app-modules/report/src/Filament/Pages/StudentMessagesDetailReport.php, app-modules/report/src/Filament/Pages/StudentMessagesOverviewReport.php, app-modules/report/src/Filament/Pages/Students.php, app-modules/report/src/Filament/Pages/TaskManagement.php, app-modules/report/src/Filament/Pages/UserLoginActivity.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1945
> Introduce a Projects report placeholder under Project Management in the report library
> No
> No
=> [ADVAPP-1945]: Introduce a Projects report placeholder under Project Management in the report library

app-modules/ai/database/factories/AiAssistantUseFactory.php, app-modules/ai/database/migrations/2025_09_22_134900_add_user_tracking_columns_to_ai_assistants_table.php, app-modules/ai/database/migrations/2025_09_22_134901_create_ai_assistant_uses_table.php, app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php, app-modules/ai/src/Jobs/Advisors/SendAdvisorMessage.php, app-modules/ai/src/Models/AiAssistant.php, app-modules/ai/src/Models/AiAssistantUse.php, app-modules/ai/tests/Tenant/Models/Scopes/AiAssistantScopeTest.php, app-modules/report/src/Filament/Pages/CustomAdvisorReport.php, app-modules/report/src/Filament/Pages/InstitutionalAdvisorReport.php, app-modules/report/src/Filament/Widgets/CustomAdvisorLineChart.php, app-modules/report/src/Filament/Widgets/CustomAdvisorStats.php, app-modules/report/src/Filament/Widgets/CustomAdvisorTable.php, app-modules/report/src/Filament/Widgets/InstitutionalAdvisorLineChart.php, app-modules/report/src/Filament/Widgets/InstitutionalAdvisorStats.php, app-modules/report/tests/Tenant/Filament/Widgets/CustomAdvisorLineChartTest.php, app-modules/report/tests/Tenant/Filament/Widgets/CustomAdvisorStatsTest.php, app-modules/report/tests/Tenant/Filament/Widgets/InstitutionalAdvisorLineChartTest.php, app-modules/report/tests/Tenant/Filament/Widgets/InstitutionalAdvisorStatsTest.php, app/Features/AiAssistantUseFeature.php, composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1935
- https://canyongbs.atlassian.net/browse/ADVAPP-1946
- https://canyongbs.atlassian.net/browse/ADVAPP-1947
Add new reports as described, and a new system that tracks exchanges by assistant. Add tracking of AI assistant creator.
No
`AiAssistantUseFeature`
=> [ADVAPP-1935], [ADVAPP-1946] & [ADVAPP-1947]: Introduce a report for institutional and custom advisors in report library

app-modules/report/src/Filament/Exports/StudentCaseExporter.php, app-modules/report/src/Filament/Widgets/StudentCaseTable.php, app-modules/report/tests/Tenant/Filament/Widgets/StudentCaseTableTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1941
- Create Exporter
- Add the exporter to the table
- No
- No
=> [ADVAPP-1941]: Introduce the ability to export data from student cases report table as a csv

app-modules/ai/resources/views/components/assistant.blade.php, app-modules/ai/routes/web.php, app-modules/ai/src/Http/Requests/Advisors/DownloadImageRequest.php
- N/A
Merge in of hotfix `1.89.1` into `main`.
No
No
=> [Hotfix]: 1.89.1

app-modules/engagement/src/Filament/Pages/Inbox.php, app-modules/engagement/tests/Tenant/Filament/Pages/InboxTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1958
Add type column to inbox, filter, test
No
No
=> [ADVAPP-1958]: Improve unified inbox by adding a message type column to distinguish between texts and emails

app-modules/report/src/Filament/Exports/MostEngagedStudentTableExporter.php, app-modules/report/src/Filament/Widgets/MostEngagedStudentsTable.php, app-modules/report/tests/Tenant/Filament/Widgets/MostEngagedStudentsTableTest.php, composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-1939
> Introduce the ability to export data from student messages overview report table as a csv
> No
> No
=> [ADVAPP-1939]: Introduce the ability to export data from student messages overview report table as a csv

app-modules/ai/src/Http/Middleware/EnsureQnaAdvisorRequestComingFromAuthorizedDomain.php, app-modules/form/src/Http/Middleware/EnsureSubmissibleIsEmbeddableAndAuthorized.php, app-modules/meeting-center/src/Http/Middleware/EnsureEventRegistrationFormIsEmbeddableAndAuthorized.php, app-modules/portal/src/Http/Middleware/EnsureResourceHubPortalIsEmbeddableAndAuthorized.php
- N/A
Fixes an issue with widgets not loading correctly when embedded on the same domain as the app.
No
No
=> [Bugfix]: Check requesting URL headers if origin is missing

app-modules/engagement/resources/views/filament/pages/view-engagement-response.blade.php, app-modules/engagement/src/Filament/Pages/ViewEngagementResponse.php
- https://canyongbs.atlassian.net/browse/ADVAPP-1961
- Update the view
- Update the Livewire class:
- - Add a method for getting the inverted status
- - Add a method for toggling the inverted method
- No
- No
=> [ADVAPP-1961]: Improve unified inbox by adding a status toggle to mark messages as Actioned or New

app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-alerts-widget.blade.php, app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-care-team-widget.blade.php, app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-subscriptions-widget.blade.php, app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-tasks-widget.blade.php, composer.json, composer.lock
- N/A
Fixes V4 deployment bugs:
- Issue with links in rendered tip tap content
- Missing buttons in Holistic profile
No
No
=> V4 bugfixes

app-modules/ai/database/factories/QnaAdvisorCategoryFactory.php, app-modules/case-management/src/Notifications/Concerns/HandlesCaseTemplateContent.php, app-modules/case-management/src/Notifications/EducatableCaseAssignedNotification.php, app-modules/case-management/src/Notifications/EducatableCaseStatusChangeNotification.php, app-modules/case-management/src/Notifications/EducatableCaseUpdatedNotification.php, app-modules/engagement/src/Models/Engagement.php, app-modules/report/src/Filament/Widgets/ProspectMessagesDetailTable.php, app-modules/report/src/Filament/Widgets/QnaAdvisorReportStats.php, app-modules/report/src/Filament/Widgets/StudentMessagesDetailTable.php
- N/A
Merge changes from hotfix `1.90.2` into `main`.
No
No
=> [Hotfix]: 1.90.2

app-modules/audit/src/Filament/Resources/Audits/AuditResource.php, app-modules/audit/src/Filament/Resources/Audits/Pages/ListAudits.php, app-modules/audit/src/Filament/Resources/Audits/Pages/ViewAudit.php, app-modules/audit/tests/Tenant/Audit/ListAuditsTest.php, app-modules/audit/tests/Tenant/Audit/ViewAuditTest.php
- https://canyongbs.atlassian.net/browse/ADVAPP-2009
> Update Filament resource structure: audit module
> No
> No
=> [ADVAPP-2009]: Update Filament resource structure: audit module

app-modules/campaign/src/Filament/Blocks/CareTeamBlock.php, app-modules/campaign/src/Filament/Blocks/TagsBlock.php, app-modules/campaign/src/Filament/Resources/Campaigns/CampaignResource.php, app-modules/campaign/src/Filament/Resources/Campaigns/Pages/CreateCampaign.php, app-modules/campaign/src/Filament/Resources/Campaigns/Pages/EditCampaign.php, app-modules/campaign/src/Filament/Resources/Campaigns/Pages/ListCampaigns.php, app-modules/campaign/src/Filament/Resources/Campaigns/Pages/ViewCampaign.php, app-modules/campaign/src/Filament/Resources/Campaigns/RelationManagers/CampaignActionsRelationManager.php, app-modules/campaign/src/Notifications/CampaignActionFinished.php, app-modules/campaign/tests/Tenant/Actions/ListCampaignsTest.php, app-modules/report/src/Filament/Widgets/ProspectMessagesDetailTable.php, app-modules/report/src/Filament/Widgets/StudentMessagesDetailTable.php, phpstan-baseline.php
- https://canyongbs.atlassian.net/browse/ADVAPP-2012
> Update Filament resource structure: campaign module
> No
> No
=> [ADVAPP-2012]: Update Filament resource structure: campaign module
