app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ViewKnowledgeBaseItem.php
resources/views/filament/infolists/entries/html.blade.php

This PR adds the ability to render HTML via a `ViewEntry` in our Filament infolists. This uses a Blade view under the hood which still provides the field label and provides some degree of separation from other fields.

[Feature] Knowledge Base HTML Output

---

app-modules/assist-data-model/src/Models/Student.php
app-modules/audit/database/migrations/2023_08_16_025823_create_audit_settings.php
app-modules/audit/src/Console/Commands/PurgePastRetentionAuditRecordsCommand.php
app-modules/audit/src/Filament/Pages/ManageAuditSettings.php
app-modules/audit/src/Overrides/Concerns/AttachOverrides.php
app-modules/audit/src/Providers/AuditServiceProvider.php
app-modules/audit/src/Settings/AuditSettings.php
app-modules/audit/tests/PurgePastRetentionAuditRecordsCommandTest.php
app-modules/engagement/src/Models/EngagementFile.php
app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php

Add automated Audit purging based on admin configurable retention period

[Feature] Audit Purging

---

composer.json
composer.lock

Because our changes were merged into the package, we can now move back to the upstream and no longer point at the fork.

[Hotfix] Update awcodes/filament-tiptap-editor back to upstream

---

_ide_helper_models.php
app-modules/form/src/Models/Form.php
app-modules/form/src/Models/FormField.php
app-modules/form/src/Models/FormSubmission.php
app-modules/team/src/Models/TeamUser.php
app-modules/theme/src/Filament/Pages/ManageBrandConfigurationSettings.php
app/Models/SettingsProperty.php
resources/views/vendor/filament-panels/components/logo.blade.php

Also, both the `Active` and `Dark logo` fields have been hidden when the logo has not been uploaded yet, to clear things up visually.

[ASSIST-555]: Add dark logo option to Brand Configuration

---

app-modules/engagement/database/factories/EngagementDeliverableFactory.php
app-modules/engagement/resources/views/components/filters.blade.php
app-modules/engagement/resources/views/components/message-center-content.blade.php
app-modules/engagement/resources/views/components/message-center-inbox.blade.php
app-modules/engagement/resources/views/components/pagination.blade.php
app-modules/engagement/resources/views/filament/pages/message-center.blade.php
app-modules/engagement/src/Filament/Concerns/EngagementInfolist.php

This PR makes sure that the Message Center content is static and overflows with a scroll when appropriate. Also fixes an issue with the html datepicker, cohesiveness in design styles.

[ASSIST-603] Ensure Message Center is static height

---

.github/pull_request_template.md

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/361/
This adds the first version of a PR template for this repository. I can evolve over time as the project grows, but this should paint a clear picture of what we are already doing here.
@danharrin, @dgoetzit, @mxm1070, and @joelicatajr I think it would be best for everyone to review and approve if they are happy with this first pass.

[ASSIST-361]: Add PR templates to GitHub

---

resources/css/filament/admin/theme.css
tailwind.config.js

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/617/
This PR sets the background color on the login screen for light mode to `trout-700`.

[ASSIST-617]: Set background color on login

---

app-modules/engagement/resources/views/components/message-center-content.blade.php
app-modules/engagement/resources/views/components/message-center-inbox.blade.php
app-modules/engagement/resources/views/components/page-link.blade.php
app-modules/engagement/resources/views/components/pagination.blade.php
app-modules/engagement/resources/views/filament/pages/message-center.blade.php

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/607/
This PR introduces changes to the Message Center inbox pagination in order to resolve an overflow issue when there are a lot of pagination links. I am open to other ideas here, as this solution is not foolproof and will potentially still result in issues when page numbers (literal page numbers, not number of pages) are extremely large.

[ASSIST-607] Message Center overflow pagination

---

app-modules/audit/src/Filament/Pages/ManageAuditSettings.php
app-modules/integration-google-analytics/src/Filament/Pages/ManageGoogleAnalyticsSettings.php
app-modules/integration-microsoft-clarity/src/Filament/Pages/ManageMicrosoftClaritySettings.php
app-modules/theme/src/Filament/Pages/ManageBrandConfigurationSettings.php
app/Models/SettingsProperty.php

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/631/
Previously, all logos were converted to JPG when uploaded. Now, the original format is preserved, so PNG transparency is not lost.
This also fixes an issue introduced in #162, where the `mount()` method of pages was not being overridden correctly, which caused all settings forms to not be filled with the correct data on load.
I think the fact that all the settings forms were broken in the last release is a pretty bad regression that probably warrants a new release when this PR is merged @Orrison …

[ASSIST-631]: Research dark mode logo display transparency issue (presenting with white background)

---

app/Filament/Resources/UserResource/RelationManagers/RoleGroupsRelationManager.php

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/653/
Adjusts wording in Role Group Manager for User to display as Profile for Users.

[ASSIST-653]: Bug: Adjust display of Role Group to Profile in RBAC interface. 

---

app-modules/engagement/src/Filament/Pages/MessageCenter.php

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/693/
This PR fixes an issue with a reference to the student table when ADM materialized views are enabled.

[ASSIST-693]: Message Center references non-existent table

---

app-modules/assist-data-model/src/Filament/Resources/StudentResource.php
app-modules/assist-data-model/src/Filament/Resources/StudentResource/Pages/StudentEngagementTimeline.php
app-modules/prospect/src/Filament/Resources/ProspectResource.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ProspectEngagementTimeline.php

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/755/
This PR renames the "Engagement Timeline" in the Student/Prospect view to "Timeline".

[ASSIST-755] Rename "Engagement Timeline" to Timeline in Student/Prospect View

---

app-modules/authorization/src/Filament/Resources/RoleGroupResource/RelationManagers/RolesRelationManager.php
app-modules/authorization/src/Filament/Resources/RoleGroupResource/RelationManagers/UsersRelationManager.php
app/Filament/Resources/UserResource/RelationManagers/RoleGroupsRelationManager.php

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/787/
Changes the verbiage of the detach for Roles for both Profiles and Users -> Profiles.

[ASSIST-787]: Simplify Detach Operation in Users and Profiles

---

app-modules/assist-data-model/database/migrations/2023_08_11_235451_create_implicit_varchar_as_uuid_cast.php
app-modules/prospect/database/migrations/2023_07_26_000003_create_prospects_table.php

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/765/
Switches Prospects back to uuid for the primary key. I could not reproduce an issue with the filter even after switching prospects back to a UUID column.
The filter works, and I get back the results I would expect.
If y'all have any specific details so I can reproduce an error to debug, let me know.

[ASSIST-765]: Spike: Resolve issue with implicit uuid casting (30 Minutes)

---

app-modules/prospect/database/seeders/ProspectStatusSeeder.php
app-modules/prospect/src/Enums/SystemProspectClassification.php

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/699/
Change the Prospect Status "Dead" status to be "Not Interested"

[ASSIST-699]: Change the default status of Prospect Statuses from Dead to Not Available.

---

app/Filament/Resources/PronounsResource.php

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/697/
Changes Pronouns menu item and page context to be User Profile Pronouns

[ASSIST-697]: Rename Pronouns on Product Settings to "User Profile Pronouns"

---

_ide_helper_models.php
app-modules/alert/src/Models/Alert.php
app-modules/campaign/src/Enums/CampaignActionType.php
app-modules/campaign/src/Filament/Blocks/InteractionBlock.php
app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php
app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php
app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php
app-modules/campaign/src/Models/CampaignAction.php
app-modules/campaign/tests/Actions/ProactiveAlertsCampaignTest.php
app-modules/care-team/src/Models/CareTeam.php
app-modules/caseload-management/src/Models/Caseload.php
app-modules/caseload-management/src/Models/CaseloadSubject.php
app-modules/interaction/src/Models/Interaction.php
resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php
resources/views/filament/forms/components/campaigns/actions/interaction.blade.php
resources/views/filament/forms/components/campaigns/actions/proactive-alert.blade.php
resources/views/filament/forms/components/campaigns/actions/service-request.blade.php
resources/views/filament/forms/components/campaigns/step-summary.blade.php

https://engage.canyongbs.com/company/personal/user/15/tasks/task/view/721/
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/803/
This PR covers adding campaign types for both the `Alert` and `Interaction` models.

[ASSIST-721] Add a new campaign type for proactive alerts

---

app-modules/assist-data-model/src/Models/Contracts/Educatable.php
app-modules/campaign/src/Enums/CampaignActionType.php
app-modules/campaign/src/Filament/Blocks/CareTeamBlock.php
app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php
app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php
app-modules/campaign/src/Models/CampaignAction.php
app-modules/campaign/tests/Actions/CareTeamCampaignTest.php
app-modules/care-team/src/Models/CareTeam.php
resources/views/filament/forms/components/campaigns/actions/care-team.blade.php
resources/views/filament/forms/components/campaigns/step-summary.blade.php

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/805/
Adds a Campaign Action to add or reset the CareTeam of Educatables in a CaseLoad.

[ASSIST-805]: Add a new campaign type for Care Team

---

app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/329/
Enable confirmation when cancelling bulk engagement.

[ASSIST-329]: Enable confirmation when cancelling bulk engagement

---

app-modules/assist-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
app-modules/engagement/database/factories/EngagementFactory.php
app-modules/engagement/database/migrations/2023_08_17_161256_create_engagements_table.php
app-modules/engagement/src/Actions/DeliverEngagements.php
app-modules/engagement/src/Filament/Actions/Concerns/ImplementsHasBulkEngagementAction.php
app-modules/engagement/src/Filament/Actions/Contracts/HasBulkEngagementAction.php
app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php
app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/EditEngagement.php
app-modules/engagement/src/Models/Engagement.php
app-modules/engagement/tests/Feature/Actions/DeliverEngagementsTest.php
app-modules/form/src/Events/FormSubmissionCreated.php
app-modules/form/src/Listeners/NotifySubscribersOfFormSubmission.php
app-modules/form/src/Notifications/AuthorLinkedFormSubmissionCreatedNotification.php
app-modules/form/src/Observers/FormSubmissionObserver.php
app-modules/form/tests/FormSubmissionCreatedTest.php
app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementsRelationManager.php

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/601/
This PR adds a `scheduled` boolean column to the `engagements` table in order to make it easier to determine if an Engagement should be picked up in the "DeliverEngagements" job running in the Kernel.

[ASSIST-601]: Add "scheduled" column to Engagements

---

_ide_helper_models.php
app-modules/campaign/src/Filament/Blocks/ServiceRequestBlock.php
app-modules/service-management/config/roles/web/service_management.php
app-modules/service-management/config/roles/web/service_request_assignment_management.php
app-modules/service-management/database/factories/ServiceRequestAssignmentFactory.php
app-modules/service-management/database/migrations/2023_09_05_144251_create_service_requests_table.php
app-modules/service-management/database/migrations/2023_12_01_015036_create_service_request_assignments_table.php
app-modules/service-management/database/seeders/ServiceRequestSeeder.php
app-modules/service-management/database/seeders/ServiceRequestUpdateSeeder.php
app-modules/service-management/resources/views/components/service-request-assignment-timeline-item.blade.php
app-modules/service-management/src/Enums/ServiceRequestAssignmentStatus.php
app-modules/service-management/src/Filament/Concerns/ServiceRequestAssignmentInfolist.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ManageServiceRequestAssignment.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ServiceRequestTimeline.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/AssignedToRelationManager.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/CreatedByRelationManager.php
app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Components/ServiceRequestAssignmentViewAction.php
app-modules/service-management/src/Models/ServiceRequest.php
app-modules/service-management/src/Models/ServiceRequestAssignment.php
app-modules/service-management/src/Observers/ServiceRequestAssignmentObserver.php
app-modules/service-management/src/Policies/ServiceRequestAssignmentPolicy.php
app-modules/service-management/src/Providers/ServiceManagementServiceProvider.php
app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
app-modules/timeline/src/Timelines/ServiceRequestAssignmentTimeline.php
app/Filament/Widgets/MyServiceRequests.php
app/Models/User.php

https://engage.canyongbs.com/company/personal/user/15/tasks/task/view/945/
This PR adds the ability to track Service Request assignment/reassignment history over time. In order to facilitate this, the ServiceRequestAssignment model has been introduced to serve as an intermediary between the service request itself and the assigned user. Though this convention is currently only set up to allow for one `active` assignment at any given point in time, the architecture can support a world in which multiple users are assigned to a service request at the same time.

[ADVISING-945]: Track and display assignment/reassignments of service requests in the timeline 

---

app-modules/assist-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
app-modules/engagement/database/factories/EngagementDeliverableFactory.php
app-modules/engagement/src/Filament/Concerns/EngagementInfolist.php
app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementsRelationManager.php

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1077/
This PR updates the display/text of Engagement Deliverable response content. It also hides the "Delivered At" field if the deliverable was not delivered.

[ADVISING-1077]: Rename Response with Error Details in Delivery Information for Text Messages 

---

app-modules/knowledge-base/src/Policies/KnowledgeBaseCategoryPolicy.php
app-modules/knowledge-base/src/Policies/KnowledgeBaseItemPolicy.php
app-modules/knowledge-base/src/Policies/KnowledgeBaseQualityPolicy.php
app-modules/knowledge-base/src/Policies/KnowledgeBaseStatusPolicy.php
app-modules/knowledge-base/src/Providers/KnowledgeBaseServiceProvider.php
app-modules/knowledge-base/tests/KnowledgeBaseCategory/CreateKnowledgeBaseCategoryTest.php
app-modules/knowledge-base/tests/KnowledgeBaseCategory/EditKnowledgeBaseCategoryTest.php
app-modules/knowledge-base/tests/KnowledgeBaseCategory/ListKnowledgeBaseCategoryTest.php
app-modules/knowledge-base/tests/KnowledgeBaseCategory/ViewKnowledgeBaseCategoryTest.php
app-modules/knowledge-base/tests/KnowledgeBaseItem/CreateKnowledgeBaseCategoryTest.php
app-modules/knowledge-base/tests/KnowledgeBaseItem/EditKnowledgeBaseItemTest.php
app-modules/knowledge-base/tests/KnowledgeBaseItem/ListKnowledgeBaseItemsTest.php
app-modules/knowledge-base/tests/KnowledgeBaseItem/ViewKnowledgeBaseItemTest.php
app-modules/knowledge-base/tests/KnowledgeBaseQuality/CreateKnowledgeBaseQualityTest.php
app-modules/knowledge-base/tests/KnowledgeBaseQuality/EditKnowledgeBaseCategoryTest.php
app-modules/knowledge-base/tests/KnowledgeBaseQuality/ListKnowledgeBaseQualityTest.php
app-modules/knowledge-base/tests/KnowledgeBaseQuality/ViewKnowledgeBaseQualityTest.php
app-modules/knowledge-base/tests/KnowledgeBaseStatus/CreateKnowledgeBaseStatusTest.php
app-modules/knowledge-base/tests/KnowledgeBaseStatus/EditKnowledgeBaseStatusTest.php
app-modules/knowledge-base/tests/KnowledgeBaseStatus/ListKnowledgeBaseStatusesTest.php
app-modules/knowledge-base/tests/KnowledgeBaseStatus/ViewKnowledgeBaseStatusTest.php
app/Concerns/FeatureAccessEnforcedPolicyBefore.php
app/DataTransferObjects/LicenseManagement/LicenseLimitsData.php
app/Enums/Feature.php
app/Filament/Pages/ManageLicenseSettings.php
app/Policies/Contracts/FeatureAccessEnforcedPolicy.php
app/Providers/AuthServiceProvider.php
app/Support/FeatureAccessResponse.php

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1011/
Creates Feature enforcement protected by re-usable Gates. Implements on the KB items.

[ADVISING-1011]: Enforce Subscription Rules for Knowledge Management

---

app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php
app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/EditEngagement.php
app-modules/team/database/factories/TeamFactory.php
database/migrations/2023_03_06_000004_create_users_table.php

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1067/
This PR adds a "My Team" checkbox filter to the email template selection modal for engagements. It also resolves [an issue](https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1091/) with attaching users because of a newly introduced `json` column to the users table. See the following for reference: https://github.com/filamentphp/filament/issues/8698, https://www.postgresql.org/docs/current/datatype-json.html
We may want to use `jsonb` as the column type in other situations as well, to avoid this issue elsewhere in the future.

[ADVISING-1067]: Introduce My Team filter for selecting email or text message templates

---

app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/CreateEmailTemplate.php
app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/CreateSmsTemplate.php

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1063/
Changes the Email Template and SMS Template redirects after create to bring the User back to the respective index page.

[ADVISING-1063]: Return to list view after create of Text Message and Email template

---

app-modules/division/src/Filament/Resources/DivisionResource/Pages/CreateDivision.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/EditDivision.php
app-modules/engagement/src/Actions/GenerateEmailMarkdownContent.php
app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/CreateEmailTemplate.php
app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php
app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php
app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/EditEngagement.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/CreateKnowledgeBaseItem.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
config/filament-tiptap-editor.php
config/filesystems.php
docs/local-setup.md

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1071/
Adds the ability to add and render images in Email Templates and email content.
In order to facilitate access to the media, any media uploaded is now stored in a public path in our storage. Docs have been updated on what to change locally within Minio to replicate this locally.

[ADVISING-1071]: Add Rich Text Capabilities to Email Templates

---

.gitignore
app-modules/notifications/graphql/subscription.graphql
composer.json
composer.lock
config/app.php

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1145/
Add API Capabilities for Subscriptions.

[ADVISING-1145]: Add API Capabilities for Subscriptions

---

app-modules/portal/composer.json
app-modules/portal/config/permissions/api/custom.php
app-modules/portal/config/permissions/web/custom.php
app-modules/portal/config/roles/api/portal_roles.php
app-modules/portal/config/roles/web/portal_roles.php
app-modules/portal/config/roles/web/portal_settings_management.php
app-modules/portal/database/migrations/2023_08_16_025823_create_portal_settings.php
app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
app-modules/portal/src/PortalPlugin.php
app-modules/portal/src/Providers/PortalServiceProvider.php
app-modules/portal/src/Settings/PortalSettings.php
composer.json
composer.lock

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/1103/
Using the Spatie settings package.

[ADVISING-1103]: Introduce Portal Settings

---

app-modules/alert/graphql/alert.graphql
app-modules/care-team/graphql/care-team.graphql
app-modules/division/graphql/division.graphql
app-modules/interaction/graphql/interaction-campaign.graphql
app-modules/interaction/graphql/interaction-driver.graphql
app-modules/interaction/graphql/interaction-outcome.graphql
app-modules/interaction/graphql/interaction-relation.graphql
app-modules/interaction/graphql/interaction-status.graphql
app-modules/interaction/graphql/interaction-type.graphql
app-modules/interaction/graphql/interaction.graphql
app-modules/knowledge-base/graphql/knowledge-base-item.graphql
app-modules/notifications/graphql/subscription.graphql
app-modules/prospect/graphql/prospect.graphql
app-modules/service-management/graphql/service-management.graphql
app/GraphQL/Scalars/EducatableId.php
app/GraphQL/Scalars/InteractableId.php
app/GraphQL/Scalars/UUID.php
graphql/schema.graphql
graphql/user.graphql

- https://canyongbs.atlassian.net/browse/ADVAPP-19
Adds the UUID scalar and some other ID combination scalars and applies them where appropriate throughout our Schema files.

[ADVAPP-19]: Create a UUID Scalar

---

app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php
app-modules/engagement/resources/views/filament/pages/message-center.blade.php
app-modules/in-app-communication/resources/views/filament/pages/user-chat.blade.php

https://canyongbs.atlassian.net/browse/ADVAPP-98
This PR resolves an issue with the footer overlap on custom pages.

[ADVAPP-98]: Resolve display of footer on mobile viewport size for custom pages.

---

spectaql.yml

- https://canyongbs.atlassian.net/browse/ADVAPP-115
There is no fix for this issue. It comes from our usage of Union types that share the same field names but no the same type definition for that field. There is currently no way around this, and it is much discussed in the GraphQL community. https://github.com/graphql/graphql-js/issues/53
Technically, the specification is not hard on this limitation being required. So, I have opened an issue in the underlying PHP GraphQL package to see if it can be fixed. https://github.com/webonyx/graphql-php/issues/1500
But I have added some documentation for now for the workaround.
A deployment step could be a command that needs to be executed or an ENV key that …

Add documentation for GraphQL Union field bug

---

app-modules/form/src/Filament/Blocks/EducatableEmailFormFieldBlock.php

- https://canyongbs.atlassian.net/browse/ADVAPP-153
Renames the `EducatableEmailFormFieldBlock` block label to "Filler email address

[ADVAPP-153]: Rename "student email address" in Forms, Surveys, and Admissions to "Filler email address"

---

app-modules/meeting-center/database/factories/CalendarEventFactory.php
app-modules/meeting-center/database/factories/CalendarFactory.php
app-modules/meeting-center/database/factories/EventFactory.php
app-modules/meeting-center/database/migrations/2023_10_16_134402_create_calendar_events_table.php
app-modules/meeting-center/database/migrations/2023_12_22_211834_create_events_table.php
app-modules/meeting-center/database/seeders/CalendarEventSeeder.php
app-modules/meeting-center/database/seeders/CalendarSeeder.php
app-modules/meeting-center/database/seeders/EventSeeder.php
app-modules/meeting-center/resources/views/filament/pages/list-calendar-events.blade.php
app-modules/meeting-center/src/Filament/Resources/CalendarEventResource/Pages/ListCalendarEvents.php
app-modules/meeting-center/src/Filament/Resources/EventResource.php
app-modules/meeting-center/src/Filament/Resources/EventResource/Pages/CreateEvent.php
app-modules/meeting-center/src/Filament/Resources/EventResource/Pages/EditEvent.php
app-modules/meeting-center/src/Filament/Resources/EventResource/Pages/ListEvents.php
app-modules/meeting-center/src/Filament/Resources/EventResource/Pages/ViewEvent.php
app-modules/meeting-center/src/Filament/Widgets/CalendarEventWidget.php
app-modules/meeting-center/src/Filament/Widgets/CalendarWidget.php
app-modules/meeting-center/src/Models/Event.php
app-modules/meeting-center/src/Providers/MeetingCenterServiceProvider.php
database/seeders/DatabaseSeeder.php

https://canyongbs.atlassian.net/browse/ADVAPP-124
Creating and Scheduling Events.

[ADVAPP-124]: Creating and Scheduling Events

---

.env.example
app-modules/webhook/tests/Unit/Http/Middleware/HandleAwsSnsRequestTest.php
app/Providers/AppServiceProvider.php
config/app.php
docker-compose.yml

- N/A
This will now set up our local machines to automatically create a custom domain and apply SSL for `https://advising.local`. Orbstack is required in order for this to work.
If you would like to still use `localhost` and/or do not have Orbstack locally set up then keeping the following `.env` variables will allow for that:
```bash
APP_URL=http://localhost
APP_FORCE_HTTPS=false
```

Local Domains

---

app-modules/prospect/src/Filament/Pages/RecruitmentCrmDashboard.php
app-modules/student-data-model/src/Filament/Pages/RetentionCrmDashboard.php

- https://canyongbs.atlassian.net/browse/ADVAPP-199
- https://canyongbs.atlassian.net/browse/ADVAPP-200
As per ticket.

[ADVAPP-199] & [ADVAPP-200]: Retention / Recuitment CRM navigation group and dashboard should not be visible when unlicensed.

---

app-modules/application/src/Filament/Resources/ApplicationSubmissionStateResource.php
app-modules/prospect/src/Filament/Resources/ProspectSourceResource.php
app-modules/prospect/src/Filament/Resources/ProspectStatusResource.php
app/Filament/Clusters/ProspectManagement.php

https://canyongbs.atlassian.net/browse/ADVAPP-230
Rename Product Administration > `Recruitment Crm` to `Prospect Management`.
Rename Product Administration > Online Admissions > `Application Submission States` to `Submission States`.

[ADVAPP-230]: Enhance naming within Product Administration navigation items

---

.github/pull_request_template.md

I don't think we lose any clarity that a GitHub issue may also be pasted here, but we do save a couple of seconds by not needing to visit Jira to copy the ticket URL each time 😁

Add Jira URL to template

---

app-modules/caseload-management/src/Filament/Resources/CaseloadResource.php
app-modules/in-app-communication/database/migrations/2023_11_14_161146_create_twilio_conversations_table.php
app-modules/in-app-communication/resources/js/userToUserChat.js
app-modules/in-app-communication/resources/views/filament/pages/user-chat.blade.php
app-modules/in-app-communication/src/Actions/AddUserToConversation.php
app-modules/in-app-communication/src/Actions/CreateTwilioConversation.php
app-modules/in-app-communication/src/Actions/RemoveUserFromConversation.php
app-modules/in-app-communication/src/Enums/ConversationType.php
app-modules/in-app-communication/src/Filament/Pages/UserChat.php
app-modules/in-app-communication/src/Models/TwilioConversation.php
app-modules/meeting-center/src/Managers/GoogleCalendarManager.php
app-modules/meeting-center/src/Managers/OutlookCalendarManager.php
app-modules/service-management/tests/ServiceRequest/CreateServiceRequestTest.php
app-modules/service-management/tests/ServiceRequest/EditServiceRequestTest.php
app-modules/service-management/tests/ServiceRequestStatus/CreateServiceRequestStatusTest.php
app-modules/service-management/tests/ServiceRequestType/CreateServiceRequestTypeTest.php
app-modules/service-management/tests/ServiceRequestUpdate/CreateServiceRequestUpdateTest.php
app/Filament/Pages/ManageLicenseSettings.php
config/filament.php

- https://canyongbs.atlassian.net/browse/ADVAPP-227
Thanks to an excellent foundation, I was able to implement this with minimal changes to the existing system. However, I made a few cleanups and improvements where I noticed things.
I also updated the message UI to fix some sizing and show the author name and message time. This is not visible in the screen recording as it was implemented after:
https://github.com/canyongbs/advisingapp/assets/41773797/3d1260fc-39a1-4e31-b8f4-11ac2009d4bb

[ADVAPP-227]: Introduce Channels for Realtime Chat

---

_ide_helper_models.php
app-modules/form/database/migrations/2023_09_26_194215_create_forms_table.php
app-modules/form/src/Filament/Resources/FormResource.php
app-modules/form/src/Filament/Resources/FormResource/Pages/SubmissionOnScreenResponse.php
app-modules/form/src/Http/Controllers/FormWidgetController.php
app-modules/service-management/src/Models/ChangeRequestResponse.php
package-lock.json
package.json
widgets/form/src/App.vue

- https://canyongbs.atlassian.net/browse/ADVAPP-244
Adds a configurable successfully submission message to forms and outputs it on the Form submitted. Markdown formatted.

[ADVAPP-244]: Introduce configuration of successful submission message for forms.

---

.gitignore
app-modules/application/src/Filament/Resources/ApplicationResource/Pages/Concerns/HasSharedFormConfiguration.php
app-modules/form/src/Filament/Resources/FormResource/Pages/Concerns/HasSharedFormConfiguration.php
app-modules/form/src/Filament/Resources/FormResource/Pages/SubmissionOnScreenResponse.php
app-modules/meeting-center/src/Filament/Resources/EventResource/Pages/Concerns/HasSharedEventFormConfiguration.php
app-modules/service-management/src/Filament/Resources/ServiceRequestFormResource/Pages/Concerns/HasSharedFormConfiguration.php
app-modules/survey/src/Filament/Resources/SurveyResource/Pages/Concerns/HasSharedFormConfiguration.php

- https://canyongbs.atlassian.net/browse/ADVAPP-239
Fix creating events (and all the other forms) without form fields.

[ADVAPP-239]: Correct issue for event creation when form is empty

---

app-modules/interaction/database/factories/InteractionFactory.php
app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/EditInteraction.php
app-modules/interaction/src/Filament/Resources/InteractionResource/RelationManagers/HasManyMorphedInteractionsRelationManager.php
app-modules/interaction/src/Models/Concerns/HasManyMorphedInteractions.php
app-modules/interaction/src/Models/Interaction.php
app-modules/interaction/src/Policies/InteractionPolicy.php
app-modules/service-management/database/factories/ServiceRequestFactory.php
app-modules/service-management/src/Models/ServiceRequest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-253
This PR fixes a query scoping issue that was resulting in a test intermittently failing when a ServiceRequest was picked at random as the interactable type of an Interaction. 

[ADVAPP-253]: EditInteractionTest.php fails when a ServiceRequest is used

---

app-modules/service-management/database/migrations/2023_09_01_143524_create_service_request_types_table.php
app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/CreateServiceRequestType.php
app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestType.php
app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ViewServiceRequestType.php
app-modules/service-management/src/Models/ServiceRequestType.php

- https://canyongbs.atlassian.net/browse/ADVAPP-274
Placeholder toggles.

[ADVAPP-274]: Introduce configuration for tracking service quality in service management

---

app-modules/in-app-communication/database/migrations/2023_11_14_161146_create_twilio_conversations_table.php
app-modules/in-app-communication/resources/views/filament/pages/user-chat.blade.php
app-modules/in-app-communication/src/Actions/CreateTwilioConversation.php
app-modules/in-app-communication/src/Actions/DeleteTwilioConversation.php
app-modules/in-app-communication/src/Actions/PromoteUserToChannelManager.php
app-modules/in-app-communication/src/Actions/RemoveUserFromConversation.php
app-modules/in-app-communication/src/Filament/Pages/UserChat.php
app-modules/in-app-communication/src/Models/TwilioConversation.php

- https://canyongbs.atlassian.net/browse/ADVAPP-282
Created the ability for channel managers to delete a channel.

[ADVAPP-282]: Introduce ability to delete a realtime chat channel as the channel manager

---

app-modules/service-management/src/Enums/SlaComplianceStatus.php
app-modules/service-management/src/Models/ServiceRequest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-269
Added new No Response status to handle initial SLA compliance state confusion.

[ADVAPP-269]: Correct SLA response trigger dependency

---

app/Filament/Pages/ProductHealth.php
app/Providers/HealthServiceProvider.php

Skipped the 3 failing health checks on local. Because we now have a constant scheduler it keeps trying to send the failing health check notification every hour.
Removed `UsedDiskSpaceCheck` because originally it was configured to work on the `local` disk, and when I tried to make it use `s3` it failed.
Enabled the previously disabled `RedisCheck` because we now have a constant redis connection also configured.

Skip unnecessary health checks on local

---

app-modules/in-app-communication/resources/js/userToUserChat.js
app-modules/in-app-communication/resources/views/filament/pages/user-chat.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-305
https://github.com/canyongbs/advisingapp/assets/41773797/39b08d6d-9fbb-4d2c-98cd-42774ca33025

[ADVAPP-305]: Introduce insert emoji to realtime chat.

---

app/Filament/Pages/Dashboard.php
app/Filament/Widgets/Features.php
app/Filament/Widgets/Notifications.php
resources/views/filament/widgets/features.blade.php
resources/views/filament/widgets/notifications.blade.php
resources/views/filament/widgets/welcome-widget.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-302

[ADVAPP-302]: Update the home screen to include notifications and product awareness

---

app/Multitenancy/Http/Middleware/NeedsTenant.php

- https://canyongbs.atlassian.net/browse/ADVAPP-295
Stops reporting the NoCurrentTenant Exception during the `NeedsTenant` check. Now, we just redirect to the landlord's main URL. There is no need or benefit to reporting this; it just pollutes the logs.

[ADVAPP-295]: Prevent ALB Target Group tenant log pollution

---

docker/s6-overlay/s6-rc.d/nginx/data/check

Small hotfix to accept a `302` alone as a valid response to start nginx.

Also accept just a 302

---

_ide_helper.macros.php
app/Filament/Pages/EditProfile.php
app/Providers/FilamentServiceProvider.php

- https://canyongbs.atlassian.net/browse/ADVAPP-301
This PR adds license checks for the authenticated user into public profile based settings.

[ADVAPP-301]: Align the experience for public profile features depending on assigned license

---

app-modules/in-app-communication/resources/js/TipTap/Extentions/SafeLink.js
app-modules/in-app-communication/resources/js/userToUserChat.js
app-modules/in-app-communication/resources/views/filament/pages/user-chat.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-309
This PR adds "link protection" in Realtime chat via a new SafeLink extension. 

[ADVAPP-309]: Link protection enhancement for realtime chat

---

app-modules/audit/composer.json
app-modules/audit/config/audit.php
composer.json
composer.lock

- https://canyongbs.atlassian.net/browse/ADVAPP-328
Switch back to the upstream `owen-it/laravel-auditing` package.

[ADVAPP-328]: Switch back to upstream laravel auditing package

---

app-modules/care-team/graphql/care-team.graphql
app-modules/interaction/graphql/interaction.graphql
app-modules/notification/graphql/subscription.graphql
app-modules/service-management/graphql/service-management.graphql
app/GraphQL/Directives/CanUseInQueryDirective.php
app/Models/User.php
app/Overrides/LastDragon_ru/LaraASP/GraphQL/SearchBy/Definitions/SearchByDirective.php
app/Overrides/LastDragon_ru/LaraASP/GraphQL/SearchBy/Types/Condition.php
app/Policies/UserPolicy.php
app/Providers/AppServiceProvider.php
config/roles/api/admin.php
graphql/user.graphql

- https://canyongbs.atlassian.net/browse/ADVAPP-23
You are now no longer able to see user relationships unless you have the view permission for that user.
You are now no longer able to view email addresses in responses (inc nested relation responses) unless you have the `user.view-email` permission.
You are now no longer able to query email addresses in requests (inc nested relation queries) unless you have the `user.view-email` permission.

[ADVAPP-23]: Implement authorization methodology for querying particular fields

---

app-modules/form/src/Actions/GenerateSubmissibleEmbedCode.php
app-modules/portal/src/Actions/GeneratePortalEmbedCode.php

- https://canyongbs.atlassian.net/browse/ADVAPP-333
This fixes an issue stemming from widget/portal related signed URLs being relative, and therefore inaccessible when trying to embed.

[ADVAPP-333]: Error Loading Portal using embed code on wordpress site

---

portals/knowledge-management/src/Components/DesktopSidebar.vue

- https://canyongbs.atlassian.net/browse/ADVAPP-334
> This PR adjusts navbar styling so that it is appropriately rendered when embedded inside of another app
Before:
After:
> No 

[ADVAPP-334]: Embed issue with navigation bar

---

app-modules/alert/src/Observers/AlertObserver.php
app-modules/application/src/Observers/ApplicationSubmissionObserver.php
app-modules/form/src/Observers/FormSubmissionObserver.php
app-modules/notification/src/Observers/SubscriptionObserver.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectApplicationSubmissions.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectFormSubmissions.php
app-modules/prospect/src/Filament/Widgets/ProspectStats.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentAlerts.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentApplicationSubmissions.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentFormSubmissions.php
app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
app-modules/timeline/tests/Listeners/AddRecordToTimelineTest.php
app-modules/timeline/tests/Listeners/RemoveRecordFromTimelineTest.php
app/Filament/Widgets/ProspectGrowthChart.php
docker/s6-overlay/s6-rc.d/clear-cache/dependencies
docker/s6-overlay/s6-rc.d/clear-cache/type
docker/s6-overlay/s6-rc.d/clear-cache/up
docker/s6-overlay/scripts/clear-cache

- https://canyongbs.atlassian.net/browse/ADVAPP-358
>
>

[ADVAPP-358]

---

app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
app-modules/integration-ai/src/Client/BaseAIChatClient.php
app-modules/integration-ai/src/DataTransferObjects/DynamicContext.php
app-modules/integration-ai/src/Models/Concerns/ProvidesDynamicContext.php
app/Filament/Resources/UserResource.php
app/Models/User.php
database/migrations/2023_03_06_000004_create_users_table.php

- https://canyongbs.atlassian.net/browse/ADVAPP-361
- https://canyongbs.atlassian.net/browse/ADVAPP-360
>
Added job title to User and configured the Assistant chat dynamic context to use this information if available.
>

[ADVAPP-361]: Extend user model with job title, [ADVAPP-360]: Enhance AI to be dynamically aware of the user creating prompts

---

app-modules/service-management/database/seeders/ChangeRequestTypeSeeder.php
app/Console/Commands/CreateSuperAdmin.php
app/Console/Commands/CreateTenantCommand.php
app/Jobs/SeedTenantDatabase.php
app/Observers/TenantObserver.php
config/app.php
config/multitenancy.php
database/seeders/DatabaseSeeder.php
database/seeders/InternalAdminUsersSeeder.php
database/seeders/NewTenantSeeder.php
database/seeders/SampleSuperAdminUserSeeder.php

- https://canyongbs.atlassian.net/browse/ADVAPP-350
Adjusted the seeding process to only seed the needed data when a new tenant is created. Added a process to generate a super admin user to be used temporarily for new tenants.
We will need to wipe the DBs as well as set `ALLOW_SUPER_ADMIN_CREATION` to `true` to create a new tenant.

[ADVAPP-350]: Improve seeding process for demo/dev data

---

app-modules/in-app-communication/resources/js/userToUserChat.js
app-modules/in-app-communication/resources/views/filament/pages/user-chat.blade.php
app-modules/in-app-communication/src/Filament/Pages/UserChat.php
app/Models/User.php
database/migrations/2024_03_04_165304_add_last_chat_ping_at_column_to_users_table.php

- https://canyongbs.atlassian.net/browse/ADVAPP-49
Every 60 seconds, the chat will send an HTTP request. This request will inform the server that the user is currently viewing *a* chat. The server will respond by informing the client which users in the current chat are also active. The chat app frontend can use that list of active users to display the status dots. When a new conversation is loaded, the same process happens.

[ADVAPP-49]: Display whether or not a User is currently active in chat

---

app-modules/portal/routes/api.php
app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalLogoutController.php

- https://canyongbs.atlassian.net/browse/ADVAPP-398
> This PR ensures that an application user must be properly authenticated through the student or prospect guards in order to use the Knowledge Management portal, regardless of session authentication via the web guard.
> No

[ADVAPP-398]: Ensure that portal login only uses student and prospect guards

---

app-modules/campaign/src/Filament/Blocks/EngagementBatchBlock.php
app-modules/caseload-management/src/Filament/Resources/CaseloadResource/Pages/GetCaseloadQuery.php
app-modules/caseload-management/src/Filament/Resources/CaseloadResourceForProcesses.php
app-modules/engagement/src/Models/EngagementBatch.php
database/seeders/NewTenantSeeder.php
resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-407
- https://canyongbs.atlassian.net/browse/ADVAPP-408
- https://canyongbs.atlassian.net/browse/ADVAPP-423
> This PR adds the ability to utilize templates and the rich text editor within a campaign journey step for emails/texts. This also resolves an issue with campaign execution that stemmed from the implementation of proper permissions for resources.
> No

[ADVAPP-407] && [ADVAPP-408] && [ADVAPP-423]: Implement Rich Text Editing and Templates in Campaign Journey Step

---

app/Multitenancy/Tasks/SwitchSessionDriver.php

- https://canyongbs.atlassian.net/browse/ADVAPP-434
- https://canyongbs.atlassian.net/browse/ADVAPP-373
Fixes the session tenancy switch task to ensure that the session singletons are flushes so that the app will use the session driver changes. It also sets the session domain to be the tenant domain so that sessions are not shared between tenant URLs.
>

[ADVAPP-434]: Currently some subdomains present a 401 error when accessing & [ADVAPP-373]: Tenant connections not using DB for sessions

---

resources/views/vendor/mail/html/header.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-426
> Prepend the app url to the asset so the file can be referenced in the email header.
> No

[ADVAPP-426]: Emailed chats include broken link to logo

---

docker/s6-overlay/scripts/build-assets

- N/A
Fixes issues in deployment by ensuring only vite build is run during container startup.
>

[HOTFIX] Only run vite build in s6-overlay

---

docker/s6-overlay/scripts/build-assets

- N/A
Ensures Filament assets are published on container startup.
>

[Hotfix] Ensure we run filament:assets on startup

---

resources/views/vendor/mail/html/message.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-427
`<br />` had to be used instead of line breaks otherwise Markdown treated the indentation as a code block.

[ADVAPP-427]: Update email copyright template

---

app-modules/application/src/Filament/Resources/ApplicationResource/Pages/EditApplication.php
app-modules/form/src/Actions/GenerateSubmissibleEmbedCode.php
app-modules/form/src/Filament/Resources/FormResource/Pages/EditForm.php
app-modules/service-management/src/Filament/Resources/ServiceRequestFormResource/Pages/EditServiceRequestForm.php
app-modules/survey/src/Filament/Resources/SurveyResource/Pages/EditSurvey.php

- https://canyongbs.atlassian.net/browse/ADVAPP-462
Fixes the issue with the embed snippet display in the UI. It seems there was some change in the Filament that now results in the HTML being sanitized. So, I removed marking it as `markdown` and formatted it manually.
@danharrin, can you confirm this is the best approach or at least a good enough one?
>

[ADVAPP-462]: Resolve embed snippet for forms

---

app-modules/portal/routes/api.php
app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalCategoryController.php
app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalController.php
portals/knowledge-management/src/App.vue

- https://canyongbs.atlassian.net/browse/ADVAPP-383
A new API endpoint has been introduced to return categories, and they have been removed from the existing one. If authentication is required and has not been performed, the request to fetch categories is delayed until it happens successfully.

[ADVAPP-383]: Delay loading of portal contents until after authentication

---

package.json
spectaql.yml

- https://canyongbs.atlassian.net/browse/ADVAPP-466
This should fix the errors when generating the API docs in dev and production.
We don't have a `.env` in dev and production, so this removes the need for it and sets a dummy URL for the docs URL.
I'm leaving the package we used to install this for now, though. We will need to make some changes to generate API docs per client, it will be needed then.
>

[ADVAPP-466]: API docs link produces an error

---

app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-435
> Add a loading indicator when the AI is generating a respinse.
> No

[ADVAPP-435]: Implement loader presentation when sending messages to the AI assistant.

---

app/Filament/Imports/UserImporter.php
app/Filament/Resources/UserResource/Pages/ListUsers.php
app/Models/User.php
app/Policies/UserPolicy.php

- https://canyongbs.atlassian.net/browse/ADVAPP-482
> This PR introduces the ability to import a list of users via Filament import functionality.
> Yes - we will need to ensure that we run the Roles and Permissions sync process so that the `user.import` permission is added and available. 

[ADVAPP-482]: Introduce ability to import a list of users

---

app/Filament/Pages/ManageLicenseSettings.php

- https://canyongbs.atlassian.net/browse/ADVAPP-474
`disabled()` gets inherited from the form setting so I simplified those calls. The fields should not be dehydrated as they should not be mutable via JavaScript.

[ADVAPP-474]: Ensure license settings are only configurable from Olympus

---

app-modules/assistant/src/Notifications/SendAssistantTranscriptNotification.php

- https://canyongbs.atlassian.net/browse/ADVAPP-506
`->line()` only allows plain text out of the box, not Markdown or HTML. You can pass an Htmlable object to allow HTML. We can convert the message from Markdown to HTML and put it in an HtmlString for preservation. It needs to be sanitised for XSS safety. We convert new lines to `<br>` so that a singular line takes effect and a new paragraph is not required.

[ADVAPP-506]: Enhance emailed chats by including formatting

---

app/Jobs/ImportCsv.php
app/Overrides/Filament/Actions/Imports/Jobs/ImportCsvOverride.php
app/Providers/AppServiceProvider.php

- https://canyongbs.atlassian.net/browse/ADVAPP-501
This removes the default `retryUntil()` behaviour from the job, and replaces it with a maximum of 2 tries for import jobs.

[ADVAPP-501]: Failed Import doesn't stop processing

---

app/Multitenancy/Tasks/SwitchSessionDriver.php

n/a
> Reverts the session driver in the tenant switch task to "database".
> No

[Hotfix] Revert session driver

---

app-modules/engagement/src/Notifications/EngagementFailedNotification.php
app-modules/engagement/src/Notifications/EngagementSmsNotification.php
app-modules/notification/src/Notifications/BaseNotification.php
app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementsRelationManager.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php

- https://canyongbs.atlassian.net/browse/ADVAPP-453
> Ensures we only retry failed notification jobs 3 times, and alerts the engagement sender when their engagement failed to send.
> No

[ADVAPP-453]: Engagement sending failures retry indefinitely

---

app-modules/engagement/graphql/engagement.graphql
app-modules/engagement/src/Actions/GenerateTipTapBodyJson.php
app-modules/engagement/src/Actions/HandleEngagementEmailNotificationSent.php
app-modules/engagement/src/GraphQL/Mutations/SendEmail.php
app-modules/engagement/src/GraphQL/Mutations/SendSMS.php
app-modules/engagement/src/GraphQL/Mutations/UpdateEmail.php
app-modules/engagement/src/Models/Engagement.php
app-modules/engagement/src/Notifications/EngagementEmailNotification.php

- https://canyongbs.atlassian.net/browse/ADVAPP-464
>
Allows the sending of email engagements from the GraphQL api.
>

[ADVAPP-464]: Add support for transactional email via API call

---

app-modules/task/src/Filament/RelationManagers/BaseTaskRelationManager.php

- https://canyongbs.atlassian.net/browse/ADVAPP-507
> For morphMany relation Detach action is used which is not compatible with that relation, Dissociate action is used for this. So replaced Detach with Dissociate and added using() function to customize functionality. 

[ADVAPP-507] Cannot detach a task from Student/Prospect

---

app/Multitenancy/Http/Middleware/NeedsTenant.php
app/Providers/Filament/AdminPanelProvider.php
app/Providers/Filament/LandlordPanelProvider.php
app/Providers/RouteServiceProvider.php
docker/s6-overlay/s6-rc.d/nginx/data/check
resources/views/errors/404.blade.php
tests/Feature/Multitenancy/Http/Middleware/NeedsTenantTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-523
This should fix the exception we are seeing in Sentry and also better handle our routing. Added a new `ping` route accessible from all tenants and the landlord to work better for healthchecks.
Healthchecks will need to be updated in the ALB to check the /ping route for a `200`

[ADVAPP-523]: Illuminate\View\ViewException

---

app-modules/assistant/src/Filament/Pages/PersonalAssistant.php

- https://canyongbs.atlassian.net/browse/ADVAPP-530
If saved chats exist, do not assume that AI assistant records also exist and fall back to the stored default assistant ID.

[ADVAPP-530]: AI Assistant default Assistant is not created when Custom Assistant setting is turned off

---

app-modules/meeting-center/src/Filament/Resources/EventResource/Pages/Concerns/HasSharedEventFormConfiguration.php

- https://canyongbs.atlassian.net/browse/ADVAPP-550

[ADVAPP-550]: Remove seconds from start and end time picker fields for creation of events

---

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php

… the prospect list.
- https://canyongbs.atlassian.net/browse/ADVAPP-532
> Source and Created column in Prospects list now default will checked and can be togglable.

[ADVAPP-532] Add ability to hide source, status and created fields in the prospect list.

---

app-modules/team/src/Filament/Resources/TeamResource/RelationManagers/UsersRelationManager.php

- N/A
Adjusts the Team User relation manager to be able to search via name and email and to display via name.
>

[Hotfix]: Adjust how users are searched and selected in Team User manager

---

app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php
app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/EditSmsTemplate.php

- https://canyongbs.atlassian.net/browse/ADVAPP-565
> Fixes a double encoding issue on editing email/sms templates
> No

[ADVAPP-565]: Email templates content breaks when you save them on the edit page 

---

Dockerfile

- N/A
Hotfix to reduce the default amount of workers started.
>

[Hotfix] Reduce default queue workers started

---

app/Filament/Resources/UserResource/Pages/CreateUser.php
app/Filament/Resources/UserResource/Pages/EditUser.php

- https://canyongbs.atlassian.net/browse/ADVAPP-581
> In Global settings when either of the one Google SSO or Azure SSO is enabled, then while creating a new user SSO login should be switched on by default and if user wants to switch it off then a popup will appear which will ask for confirmation.

Keep toggle on when SSO settings are on

---

app-modules/ai/resources/views/components/assistant.blade.php
app-modules/ai/src/Http/Requests/SendMessageRequest.php

- N/A
Changes the AI max length to 25000, also prevents a User from adding more than 25000 chars to the textarea.
>

[Bugfix] Increase AI Max Length to 25000

---

app-modules/team/src/Filament/Resources/TeamResource/RelationManagers/UsersRelationManager.php
app-modules/team/tests/Team/EditTeamTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-596
> Added code for restrict super admin from being placed in "teams". 
There is below three test cases.
1. Non Super Admin Users can be added to a team via the UsersRelationManager for Teams.
2. Super Admin Users cannot be added to a team via the UsersRelationManager for Teams.
3. Super Admin Users do not show up in UsersRelationManager for Teams search results.
so first two test cases working perfectly. but 3rd one is not working. I have tried with @mxm1070 @Orrison. 
> Please ensure that at least one correct change type label is added to the PR. For example, if you are adding a new feature, please add the `Change Type | …

Features/advapp 596 Restrict super admins from being placed in "Teams"

---

app-modules/notification/src/Notifications/BaseNotification.php
app-modules/notification/src/Notifications/Channels/EmailChannel.php
app-modules/notification/src/Notifications/Channels/SmsChannel.php
app-modules/notification/tests/Features/NotificationSendingTest.php
app/Models/User.php
database/factories/UserFactory.php
tests/Unit/LicenseSettingsEmailQuotaTracking.php
tests/Unit/LicenseSettingsSmsQuotaTracking.php

- https://canyongbs.atlassian.net/browse/ADVAPP-594
> This PR adds handling to ensure we don't count emails/sms sent to Users with the `authorization.super_admin` against organizational quota usage.
> No

[ADVAPP-594]: Prevent super admin email and text messaging from counting towards customer limits

---

app-modules/ai/database/migrations/2024_06_04_144637_seed_ai_integration_settings_permission.php
app-modules/ai/database/migrations/2024_06_04_150112_create_ai_integrations_settings.php
app-modules/ai/src/Actions/ResetAiServiceIds.php
app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
app-modules/ai/src/Jobs/ReInitializeAiAssistant.php
app-modules/ai/src/Jobs/ReInitializeAiService.php
app-modules/ai/src/Jobs/ReInitializeAiThread.php
app-modules/ai/src/Settings/AiIntegrationsSettings.php
app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
app-modules/integration-open-ai/src/Services/OpenAiGpt4Service.php
database/migrations/Concerns/CanModifyPermissions.php

- https://canyongbs.atlassian.net/browse/ADVAPP-601
On deployment, the default credentials are copied into the settings tables of all tenants. This also happens during the tenant creation process since migrations are run.
The Open AI clients will respect the settings table.
A warning message is displayed when updating integration settings. The user has the option to either just save the settings, or to also sync all the threads and assistants to the new account as well as saving.
If the user chooses to sync the threads and assistants, all IDs are removed from affected records before the settings are saved. After the settings are saved, a job batch is kicked off to repopulate the IDs from the new service.
If the assistants or threads are interacted with before their IDs have been reissued, …

[ADVAPP-601]: Enhance the AI assistant so that the LLM credentials are isolated per tenant

---

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseArticleResource/Pages/CreateKnowledgeBaseArticle.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseArticleResource/Pages/EditKnowledgeBaseArticleMetadata.php

- https://canyongbs.atlassian.net/browse/ADVAPP-630
Resolves the bug triggered when you try and set a Division for a KnowledgeBaseArticle. The relationship is a `belongsToMany` and we were using a simple select, so it would throw errors when trying to save.
>

[ADVAPP-630]: Setting division when creating a knowledge article produces an error

---

app-modules/prospect/src/Filament/Resources/ProspectResource.php

…edit route
- https://canyongbs.atlassian.net/browse/ADVAPP-636
> When you click on a prospect name from global search it takes you to the view route.

[ADVAPP-636]: Clicking on a prospect from global search takes you to edit route

---

app-modules/form/src/Actions/GenerateSubmissibleValidator.php
app-modules/form/src/Actions/ProcessSubmissionField.php
app-modules/form/src/Http/Controllers/FormWidgetController.php

- https://canyongbs.atlassian.net/browse/ADVAPP-589
So this one was a bit weird. It turns out that in a FormKit form, if you never enter a value for an input that input isn't included in the form and never submitted. But, if you enter a value and remove it the key is left in the form with an empty string as it's value. 
Then the Laravel `ConvertEmptyStringsToNull` middleware makes it null. Then the validator fails because it expects the `text_input` to be a string. Originally I was adding the `nullable` validation rule to the input, but that doesn't matter because the `form_field_submission` doesn't allow null values. So instead I just filter out the inputs that are null. 
It also turns out that the only validation error message displayed on the frontend that comes from FormKit is the …

[ADVAPP-579]: Form validation issue for certain input types

---

app/Console/Commands/BuildAssets.php

- N/A
Fixes issues with the `app:build-assets` by increasing the timeout. Also displays the output so that you can see the command actually is processing.
>

[Bugfix]: Increase the timeout of the build command and display output

---

app-modules/ai/database/migrations/2024_06_05_192746_add_locked_at_column_to_ai_threads_table.php
app-modules/ai/resources/js/chat.js
app-modules/ai/resources/views/components/assistant.blade.php
app-modules/ai/src/Actions/RetryMessage.php
app-modules/ai/src/Actions/SendMessage.php
app-modules/ai/src/Exceptions/AiThreadLockedException.php
app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php
app-modules/ai/src/Http/Controllers/RetryMessageController.php
app-modules/ai/src/Http/Controllers/SendMessageController.php
app-modules/ai/src/Jobs/CloneAiThread.php
app-modules/ai/src/Jobs/ReInitializeAiThread.php
app-modules/ai/src/Models/AiThread.php
app-modules/ai/tests/Feature/Actions/RetryMessageTest.php
app-modules/ai/tests/Feature/Actions/SendMessageTest.php
app-modules/ai/tests/Feature/Filament/Pages/AIAssistantPageTest.php
app-modules/ai/tests/Feature/Http/Controllers/RetryMessageControllerTest.php
app-modules/ai/tests/Feature/Http/Controllers/SendMessageControllerTest.php
app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
app-modules/integration-open-ai/tests/Feature/Services/OpenAiGptTestServiceTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-635
A thread can be locked, when it has a `locked_at` set to a timestamp. When reinitialising a thread, it becomes locked. When a user sends or retries a message with a locked thread, they get an error message immediately that automatically updates when the thread becomes unlocked, allowing them to retry their message. The locked status of a thread gets checked every 10 seconds while the error message is present.
From my investigation we don't need to send test messages or runs when reinitialising a thread.  When a thread has over 32 messages, we send the first 32 as part of the thread creation request and then send messages individually after that.

[ADVAPP-635]: Update AI chat cloning to resolve message limitation

---

app/Listeners/ClearSentryUser.php
app/Listeners/SetSentryUser.php
app/Multitenancy/Listeners/RemoveSentryTenantTag.php
app/Multitenancy/Listeners/SetSentryTenantTag.php
app/Providers/AppServiceProvider.php
app/Providers/EventServiceProvider.php
config/octane.php

- https://canyongbs.atlassian.net/browse/ADVAPP-648
Sets the Tenant ID and User ID in Sentry context when appropriate and clears these values when the requests end or in other pertinent events like when a User logs out.
>

[ADVAPP-648]: Populate Tenant ID and User ID into Sentry reports

---

app/Filament/Pages/EditProfile.php

- https://canyongbs.atlassian.net/browse/ADVAPP-307
> Based on CRM settings set for a user, he/she will have access to some of the profile  settings features.

[ADVAPP-307]: Restrict the display of available public profile features depending on whether the user has access to a CRM product

---

app-modules/engagement/resources/views/components/message-center-inbox.blade.php
app-modules/engagement/src/Filament/Pages/MessageCenter.php

- https://canyongbs.atlassian.net/browse/ADVAPP-637
> Based on timezone selected by use show the times and date when logged in, in that timezone and if not selected any timezone the default will be used.

[ADVAPP - 637] - Message center not respecting user timezone

---

docker-compose.dev.yml

- N/A
Changes the default amount of queue workers to just 1 in local development.
>

[BUGFIX]: Change the default amount of queue workers to 1 in local development

---

app-modules/task/src/Enums/TaskStatus.php
app-modules/task/tests/ListTasksTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-641
> Update state management to allow tasks status from Cancelled to In Progress. Also, Added test cases for each allowed transition test cases: 
1. Pending to In Progress
2. Pending to Canceled
3. In Progress to Completed
4. In Progress to Canceled
5. Canceled to In Progress

[ADVAPP-641]: Update state management to allow tasks to go from Cancelled back to In Progress

---

app-modules/engagement/resources/views/components/message-center-content.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-655
> Add links on the name of student/prospect in the message center which on click redirects the to view page of respective student/prospect.

[ADVAPP-655]: Link Students and Prospects in Message Center to holistic record view

---

app/Http/Middleware/CheckOlympusKey.php
routes/api.php

- https://canyongbs.atlassian.net/browse/ADVAPP-664
Added `/health` route to the api to return health results.

[ADVAPP-664]: Introduce the ability to receive the product health check data at the tenant level available via API call

---

app-modules/engagement/src/Actions/EngagementEmailChannelDelivery.php
app-modules/engagement/src/Actions/EngagementSmsChannelDelivery.php

- https://canyongbs.atlassian.net/browse/ADVAPP-676
This will make it now so that the `EngagementEmailChannelDelivery` and `EngagementSmsChannelDelivery` jobs dispach the `EngagementEmailNotification` and `EngagementSmsChannelDelivery` Notifications synchronously.
I believe what was happening was that the delivery job would process, and all it did was dispatch a second job for the notification. Both this delivery job and the notification have a uniqueId defined as `Tenant::current()->id . ':' . $this->deliverable->id`. But Laravel creates the key in the background by appending the job class name to this uniqueId definition to make the cache key. Because of this, the notification does not have the same atomic lock as the delivery job. So if a Notification was waiting to process, it was …

[ADVAPP-676]: Prevent Engagements from putting jobs onto the email queue if it's on the queue but hasn't been processed

---

app-modules/authorization/tests/Feature/Filament/Resources/User/ViewUserTest.php
app-modules/multifactor-authentication/src/Traits/MultifactorAuthenticatable.php
app/Filament/Resources/UserResource/Pages/ViewUser.php
app/Policies/UserPolicy.php
database/factories/UserFactory.php

- https://canyongbs.atlassian.net/browse/ADVAPP-588
This adds the ability for Admins to see a user's MFA status on the User View page. It also allows Users with the User Update permission to reset a user's MFA status via a header Action.
>

[ADVAPP-588]: Introduce administrator recovery and support for MFA issues for local accounts

---

app-modules/authorization/resources/views/login.blade.php
app-modules/authorization/src/Filament/Pages/Auth/Login.php

- https://canyongbs.atlassian.net/browse/ADVAPP-672
Fixes issue with MFA setup and sets up the ability to use recovery codes during login.
>

[ADVAPP-672]: Add local MFA recovery code usage

---

.env.example
Dockerfile
docker-compose.dev.yml
docker/generate-queues.sh

- https://canyongbs.atlassian.net/browse/ADVAPP-678
Reduces the amount of queues run locally to just the single default queue locally by default.
A new `MULTIPLE_DEVELOPMENT_QUEUES` `.env` variable can be set to true if it is desired that multiple queues be running locally.
>

[ADVAPP-678]: Reduce local queues and workers to only run a single instance

---

composer.json
composer.lock
config/queue.php

- https://canyongbs.atlassian.net/browse/ADVAPP-644
Sets up the usage of the SQS Disk Driver for our queue management process when using SQS. When the driver determines the payload would be too large for SQS Payload limitations, it will store the payload in S3 and re-hydrate it when the queue worker picks up the job.
>

[ADVAPP-644]: Resolve SQS large payload errors

---

app-modules/integration-open-ai/src/Services/BaseOpenAiService.php

- N/A
Even if the Assistant does not have `file_search` turned on force the run to enable it if files are attached.
>

[Bugfix] Force using file_search if files are attached to AI chat

---

docker/generate-queues.sh

- https://canyongbs.atlassian.net/browse/ADVAPP-701
Updates all workers to sleep for 3 seconds if there are no jobs to process to help with wasted resource usage. Leaving commented code in for now to revert back quickly if we need to change back to the old strategy in prod.
>

[ADVAPP-701]: Change all workers to sleep for 3 seconds

---

docker-compose.dev.yml
docker-compose.prod.yml
docker-compose.yml
docs/local-setup.md

- https://canyongbs.atlassian.net/browse/ADVAPP-492
The documentation has been updated to specify the version number of Docker and Docker Compose needed for the project. We have also removed the deprecated `version` parameter from all Docker Compose Yaml files.
>

[ADVAPP-492]: Update all docs to instruct users to update to the most recent version of Docker

---

app-modules/ai/src/Filament/Resources/AiAssistantResource/Pages/EditAiAssistant.php
app-modules/ai/src/Filament/Resources/AiAssistantResource/Pages/ListAiAssistants.php
app-modules/ai/tests/Feature/Filament/Pages/ManageAiSettingsPageTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-690
> Restrict the ability to modify the settings for the Institutional Assistant to the appropriate administrative sections Advising App.
According to the screenshot below default AI Assistant is not showing in the list.
As shown in the screenshot below, If trying to access the default assistant page, it gives the forbidden error.

[ADVAPP-690]: Restrict the ability to modify the settings for the Institutional Assistant to the appropriate administrative sections Advising App

---

app/Filament/Clusters/ReportLibrary.php

…ing group has regressed to a prior state
- https://canyongbs.atlassian.net/browse/ADVAPP-715
Fix the primary navigation reporting group.
No
No

[ADVAPP-715]: The order of the primary navigation for the reporting group has regressed to a prior state

---

app-modules/report/src/Filament/Widgets/ChartReportWidget.php
app-modules/report/src/Filament/Widgets/StatsOverviewReportWidget.php

- https://canyongbs.atlassian.net/browse/ADVAPP-730
Locks the `$cacheTag` property to prevent frontend manipulation.
N/A
No.
No.

[ADVAPP-730]: Modify the cacheTag property for reports to be locked

---

app-modules/ai/src/Enums/AiModel.php

- https://canyongbs.atlassian.net/browse/ADVAPP-741
Renames the models. Also implements a small fix to ensure that the GPT test model is not an option to select for the default model.
No
No

[ADVAPP-741]: Update the model names used throughout artificial intelligence features

---

app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
app/Filament/Resources/UserResource/Pages/ListUsers.php

- https://canyongbs.atlassian.net/browse/ADVAPP-721
> Add a Teams Filter in the User Listing Page. 
> No
> No

[ADVAPP-721]: Introduce the ability to filter the user list by team

---

app-modules/ai/resources/views/components/assistant.blade.php
app-modules/ai/src/Models/AiAssistant.php

- https://canyongbs.atlassian.net/browse/ADVAPP-713
> Added a thumbnail (32*32 px) in AI Assistant.
> Yes. We will need to run the Spatie Media command to regenerate conversions for the AiAssistants Model after this is merged and deployed
> No

[ADVAPP-713]: Add a media conversion to AI Assistant avatar images

---

app-modules/authorization/src/Filament/Resources/PermissionResource.php

- https://canyongbs.atlassian.net/browse/ADVAPP-723
>Make group name column in permission group default sort in ascending
>No.
> No.

[ADVAPP-723]: Enable default sort of Permissions Group ascending

---

docker/s6-overlay/scripts/fix-permissions

- https://canyongbs.atlassian.net/browse/ADVAPP-757
Fixes a bug that is thrown when setting up the project for the first time and the `rr` file is not present.
No
No.

[ADVAPP-757]: Fix bug caused by missing rr file

---

app-modules/alert/database/migrations/2024_07_17_101206_add_user_id_foreign_key_in_alerts_table.php
app-modules/alert/database/migrations/2024_07_22_095019_created_by_feature_flag.php
app-modules/alert/src/Models/Alert.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentAlerts.php

- https://canyongbs.atlassian.net/browse/ADVAPP-727
> Add user_id for alerts, which saves the user_id who created the alert. And the name of the user can be seen in view modal of alert for both prospect and students.
> No.
> No.

[ADVAPP-727]: Enhance the contextual information provided in alerts by including who created the alert

---

app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManagePromptLibrary.php

- https://canyongbs.atlassian.net/browse/ADVAPP-747
> Added a new "My team's prompts only" in prompt library in Personal assistant upon click it will show the same team member prompt as well in list.
> No
> No

[ADVAPP-747] Enhance the prompt insertion experience for the Prompt Library feature so that users can filter prompts by their team.

---

app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
app-modules/ai/src/Models/AiAssistant.php

- https://canyongbs.atlassian.net/browse/ADVAPP-756
> Add validations in custom assistant avatar to only allow png, jpeg and gif files.
> No.
> No.

[ADVAPP-756]: Enhance validation on the file type for Custom Assistant to svg, png, gif, jpg, for the avatar feature.

---

app-modules/ai/src/Filament/Resources/LegacyAiMessageLogResource.php
app-modules/ai/src/Filament/Resources/LegacyAiMessageLogResource/Pages/ManageLegacyAiMessageLogs.php
app-modules/audit/config/audit.php
app-modules/audit/database/migrations/2024_07_22_090701_add_change_agent_name_column_to_audits_table.php
app-modules/audit/database/migrations/2024_07_22_091520_data_activate_change_agent_name.php
app-modules/audit/database/migrations/2024_07_22_092622_data_migration_agent_name.php
app-modules/audit/src/Filament/Exports/AuditExporter.php
app-modules/audit/src/Filament/Resources/AuditResource.php
app-modules/audit/src/Filament/Resources/AuditResource/Pages/ListAudits.php
app-modules/audit/src/Filament/Resources/AuditResource/Pages/ViewAudit.php
app/AuditResolvers/ChangeAgentNameResolver.php

- https://canyongbs.atlassian.net/browse/ADVAPP-751
> Change the label for audit categories from "Personal Assistant" to "Assistant Utilization" and from "Other Records" to "System Administration."
> In the View System Administration section, set "System" in the Change Agent (User) field if it is empty.
> Two new columns, Change Agent (User) and Change Agent (ID), have been added for file exports in System Administration.
> A filter to exclude system users has been added.
> The export button label has been updated from "Export audits" to "Export Records" and from "Export legacy AI message logs" to "Export Records."
> We developed a custom resolver called ChangeAgentNameResolver. Therefore, it may be necessary to restart the queue on the server using the command: php artisan queue:restart. …

[ADVAPP-751]: Enhance the user experience for usage auditing by administrators

---

app-modules/integration-aws-ses-event-handling/routes/landlord.php
app-modules/integration-aws-ses-event-handling/src/Http/Controllers/AwsSesInboundWebhookController.php
app-modules/integration-aws-ses-event-handling/tests/Feature/Http/AwsSesInboundWebhookControllerTest.php
app-modules/integration-aws-ses-event-handling/tests/Feature/Listeners/HandleSesEventTest.php
app-modules/integration-aws-ses-event-handling/tests/Fixtures/Bounce.json
app-modules/integration-aws-ses-event-handling/tests/Fixtures/Click.json
app-modules/integration-aws-ses-event-handling/tests/Fixtures/Complaint.json
app-modules/integration-aws-ses-event-handling/tests/Fixtures/Delivery.json
app-modules/integration-aws-ses-event-handling/tests/Fixtures/DeliveryDelay.json
app-modules/integration-aws-ses-event-handling/tests/Fixtures/Open.json
app-modules/integration-aws-ses-event-handling/tests/Fixtures/Reject.json
app-modules/integration-aws-ses-event-handling/tests/Fixtures/RenderingFailure.json
app-modules/integration-aws-ses-event-handling/tests/Fixtures/Send.json
app-modules/integration-aws-ses-event-handling/tests/Unit/SesConfigurationSetTest.php
app-modules/notification/src/Notifications/BaseNotification.php
app-modules/notification/src/Notifications/Concerns/EmailChannelTrait.php

- https://canyongbs.atlassian.net/browse/ADVAPP-603
Fixes the delivery tracking of emails sent out of the system by attaching a `tenant_id` to them and then tracking that on the inbound webhook receiving from SES then directing the job to be executed as that Tenant.
No
No

[ADVAPP-603]: Unable to receive engagement updates on delivered emails as expected

---

.env.example
docker-compose.dev.yml
docker/s6-overlay/scripts/startup-caching

- https://canyongbs.atlassian.net/browse/ADVAPP-768
Adds module caching during application startup.
Must wait to merge in until https://github.com/canyongbs/devops/pull/36 is merged into `main` and this repos submodule is updated to point to that new commit.
No
No

[ADVAPP-768]: Add module caching to startup-caching

---

app-modules/task/src/Filament/Widgets/TasksWidget.php

- https://canyongbs.atlassian.net/browse/ADVAPP-779
Sorting Tasks by Due Date on My Dashboard in the Recruitment CRM does not appropriately reorder the list
No
No

[ADVAPP-779]: Sorting Tasks by Due Date on My Dashboard in the Recruitment CRM does not appropriately reorder the list

---

app-modules/campaign/src/Filament/Blocks/Actions/DraftCampaignEngagementBlockWithAi.php
app-modules/engagement/src/Filament/Actions/DraftWithAiAction.php
app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords/Actions/DraftWithAiAction.php
app-modules/engagement/src/Filament/Resources/Actions/DraftTemplateWithAiAction.php
app-modules/integration-open-ai/src/Services/BaseOpenAiService.php

- https://canyongbs.atlassian.net/browse/ADVAPP-746
When a connection error occurs, or when the API returns an unsuccessful status code, or where the JSON does not contain the correct key, an exception is thrown from the service. This is caught in the action implementation to send a notification to the user informing them of the error. The modal remains open for easy retries in case the service or connection is being flaky, there is no data loss from the prompt.
No
No

[ADVAPP-746]: Add error handling to AI Chat Completions

---

resources/views/landlord.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-803
> Replace reference to resources/svg/flowbite-500.svg with resources/svg/canyongbs-500.svg in resources/views/landlord.blade.php
> No
> No

[ADVAPP-803]: Old flowbite svg is still referenced in Landlord page

---

app/Console/Commands/ConnectOlympus.php

- https://canyongbs.atlassian.net/browse/OLYMPUS-88
Support for [OLYMPUS-88]. Because Brand settings will now no longer be tied to an Application we should not and cannot sync Brand info during the first connection to Olympus.
No.
No.
[OLYMPUS-88]: https://canyongbs.atlassian.net/browse/OLYMPUS-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OLYMPUS-88]: Ensure Olympus connect to other products works locally

---

app-modules/ai/database/migrations/2024_08_13_193433_add_feature_column_to_assistant_chat_message_logs_table.php
app-modules/ai/database/migrations/2024_08_13_195739_data_activate_ai_log_features.php
app-modules/ai/database/migrations/2024_08_13_210121_data_backfill_assistant_chat_message_logs_feature_column.php
app-modules/ai/database/migrations/2024_08_13_210631_make_feature_column_in_assistant_chat_message_logs_table_nullable.php
app-modules/ai/src/Actions/CompletePrompt.php
app-modules/ai/src/Enums/AiFeature.php
app-modules/ai/src/Filament/Resources/LegacyAiMessageLogResource.php
app-modules/ai/src/Listeners/CreateAiMessageLog.php
app-modules/ai/src/Models/LegacyAiMessageLog.php
app-modules/ai/tests/Feature/Actions/CompletePromptTest.php
app-modules/campaign/src/Filament/Blocks/Actions/DraftCampaignEngagementBlockWithAi.php
app-modules/engagement/src/Filament/Actions/DraftWithAiAction.php
app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords/Actions/DraftWithAiAction.php
app-modules/engagement/src/Filament/Resources/Actions/DraftTemplateWithAiAction.php
app-modules/interaction/src/Filament/Actions/DraftInteractionWithAiAction.php
app-modules/knowledge-base/src/Filament/Actions/DraftKnowledgeBaseArticleWithAiAction.php

- https://canyongbs.atlassian.net/browse/ADVAPP-752
Creates a central Action Class to trigger completions. Within the class, we now register an AI Message Log. Adds a new `feature` column to the AI Message logs table and backfill it.
No
Feature Flag: `ai-log-features`
Data Migration: app-modules/ai/database/migrations/2024_08_13_210121_data_backfill_assistant_chat_message_logs_feature_column.php

[ADVAPP-752]: Enhance Assistant Utilization logging and auditing to include new "Draft with AI" features

---

app-modules/interaction/src/Filament/Actions/DraftInteractionWithAiAction.php

- https://canyongbs.atlassian.net/browse/ADVAPP-809
Fixes bug with Draft Interaction with AI caused by naming the `$model` variable passed to `CompletePrompt` the same as a variable also used in the prompt for something else.
No.
No.

[ADVAPP-809]: Draft with AI for student and prospect interactions generates an exception

---

app-modules/ai/src/Listeners/DeleteExternalAiMessageFile.php
app-modules/ai/src/Listeners/DeleteExternalAiThread.php

- https://canyongbs.atlassian.net/browse/ADVAPP-778
Captures the `No thread found with id` Exception, reports it, and continues on.
No
No.

[ADVAPP-778]: An exception is sometimes thrown during the thread pruning process

---

composer.lock

- https://canyongbs.atlassian.net/browse/ADVAPP-767
A bug in FilePond prevented errors from displaying within circular upload fields. Now, errors are displayed below the input. https://github.com/filamentphp/filament/pull/13952
No
No

[ADVAPP-767]: Mimetype validation errors do not display for rounded upload inputs

---

resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-798
> When an email is created in campaign, the format of the email body was not shown in proper format. Therefore the format of the email body has been solved.
> No.
> No.

[ADVAPP-798]: When draft with AI is used in campaigns, formatting is not preserved from the AI output

---

app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
app-modules/integration-twilio/src/Providers/IntegrationTwilioServiceProvider.php
app-modules/integration-twilio/src/Settings/TwilioSettings.php
app-modules/notification/src/Notifications/Channels/EmailChannel.php
app-modules/notification/src/Notifications/Channels/SmsChannel.php
app/Console/Commands/CreateTenant.php
app/Http/Controllers/Tenants/CreateTenantController.php
app/Multitenancy/DataTransferObjects/TenantMailConfig.php
app/Multitenancy/Tasks/SwitchMailTask.php
database/factories/TenantFactory.php
tests/TestCase.php

- https://canyongbs.atlassian.net/browse/ADVAPP-797
It adds new settings for SES and Twilio demo mode that prevent email or text from actually being sent but mark engagements as having been delivered.
No
No.

[ADVAPP-797]: Introduce "demo mode" for email and text messaging

---

app-modules/audit/database/migrations/2024_08_28_131810_data_remove_audited_models_and_add_audited_models_exclude_to_audit_settings.php
app-modules/audit/src/Filament/Pages/ManageAuditSettings.php
app-modules/audit/src/Listeners/AuditingListener.php
app-modules/audit/src/Settings/AuditSettings.php
app-modules/audit/tests/AuditListenerTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-794
Swapes the audited models setting to be models that are excluded from auditing.
No
No

[ADVAPP-794]: Introduce automatic auditing on newly created data models

---

app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php
app-modules/ai/src/Jobs/CloneAiThread.php
app-modules/ai/src/Jobs/PrepareAiThreadCloning.php
app-modules/ai/tests/Feature/Filament/Pages/AIAssistantPageTest.php
app-modules/basic-needs/database/factories/BasicNeedsProgramFactory.php

- https://canyongbs.atlassian.net/browse/ADVAPP-823
Fixes bug with the CloneAIThread job as well as adjusts the prepare job before to be more uniform and inform the User of any failures.
Also fixes flakiness in BasicNeedsProgram tests as it failed during CI of this PR.
No.
No.

[ADVAPP-823]: When a conversation is cloned via the Enterprise AI Assistant, it generates an error.

---

app-modules/engagement/src/Filament/Concerns/EngagementResponseInfolist.php
app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords.php
app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/ViewEngagement.php
app-modules/engagement/src/Filament/Resources/EngagementResource/RelationManagers/EngagementDeliverablesRelationManager.php
app-modules/engagement/src/Filament/Resources/EngagementResponseResource/Pages/ListEngagementResponses.php
app-modules/engagement/src/Filament/Resources/EngagementResponseResource/Pages/ViewEngagementResponse.php
app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/CreateInteraction.php
app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/EditInteraction.php
app-modules/interaction/src/Filament/Resources/InteractionStatusResource.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseArticleResource/Pages/ListKnowledgeBaseArticles.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseQualityResource/Pages/ViewKnowledgeBaseQuality.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseStatusResource/Pages/ViewKnowledgeBaseStatus.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectApplicationSubmissions.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php
app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementResponsesRelationManager.php
app-modules/prospect/src/Filament/Resources/ProspectSourceResource/Pages/CreateProspectSource.php
app-modules/prospect/src/Filament/Resources/ProspectSourceResource/Pages/EditProspectSource.php
app-modules/prospect/src/Filament/Resources/ProspectSourceResource/Pages/ViewProspectSource.php
app-modules/prospect/src/Filament/Resources/ProspectStatusResource/Pages/ViewProspectStatus.php
app-modules/service-management/src/Filament/Concerns/ServiceRequestAssignmentInfolist.php
app-modules/service-management/src/Filament/Concerns/ServiceRequestHistoryInfolist.php
app-modules/service-management/src/Filament/Concerns/ServiceRequestUpdateInfolist.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/ServiceRequestUpdatesRelationManager.php
app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource/Pages/ViewServiceRequestStatus.php
app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource.php
app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Pages/ViewServiceRequestUpdate.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentApplicationSubmissions.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementResponsesRelationManager.php
app-modules/webhook/src/Filament/Resources/InboundWebhookResource/Pages/ViewInboundWebhook.php

- https://canyongbs.atlassian.net/browse/ADVAPP-80
> Removed the translateLabel() from the app except AdminPanelProvider.php.
> No.
> No.

[ADVAPP-80]: Remove usage of translateLabel()

---

.github/workflows/ci.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/update_yearly_copyright.yml

- https://canyongbs.atlassian.net/browse/ADVAPP-828
Updates all GitHub Action versions and locks some to a particular commit with a SHA.
No
No

[ADVAPP-828]: Update GitHub Action step versions

---

docker-compose.dev.yml

- https://canyongbs.atlassian.net/browse/ADVAPP-840
Adds needed configuration to work with changes to the `traefik` repo, allowing the app containers to communicate via subdomain.
No
No

[ADVAPP-840]: Modify local configuration to allow containers to reach each other via subdomain

---

app-modules/notification/src/Notifications/Messages/TwilioMessage.php

- https://canyongbs.atlassian.net/browse/ADVAPP-833
This defaults the Twilio from number to a dummy number if demo mode is enabled to exceptions are not thrown.
No
No

[ADVAPP-833]: Twilio configuration throwing errors due to change done for demo mode

---

resources/views/vendor/filament-panels/components/layout/index.blade.php
resources/views/vendor/filament-panels/components/sidebar/index.blade.php
resources/views/vendor/filament-panels/components/topbar/index.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-820
Publishes the Filament layout views to make the necessary adjustments to the topbar positioning so that the full-width branding bar can live below it.
No
No

[ADVAPP-820]: Introduce a "branding bar" for institutions to integrate their brand name and brand color into the product experience for end users.

---

app-modules/report/src/Filament/Widgets/PromptsByCategoryDoughnutChart.php
app-modules/report/src/Filament/Widgets/SpecialActionsDoughnutChart.php
resources/views/livewire/no-widget-data.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-872
Replaces the CSS classes used to make this section full height, with a centered message of muted styling.
See screenshots in ticket.
No
No

[ADVAPP-872]: Fix the noWidgetData view which has broken height

---

app-modules/notification/database/factories/SubscriptionFactory.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
app-modules/prospect/tests/Prospect/ListProspectTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-888
> Ability to filter "subscribed" prospects on Prospect List Page.
> No
> No

[ADVAPP-888] Introduce the ability to filter prospects by subscriptions from the prospect list

---

app-modules/ai/src/Filament/Resources/PromptTypeResource/Pages/ListPromptTypes.php
app-modules/ai/src/Policies/PromptTypePolicy.php

- https://canyongbs.atlassian.net/browse/ADVAPP-871
> Prevent the deletion of a prompt-type that has an active relationship to a prompt.
> No
> No

[ADVAPP-871]: Prevent the deletion of a prompt-type that has an active relationship to a prompt.

---

app-modules/portal/src/Settings/PortalSettings.php

- https://canyongbs.atlassian.net/browse/ADVAPP-852
Fixes `gdpr_banner_text` property of the GDPR text settings to match the new data type for being a TipTapEditor.
No
No

[ADVAPP-852]: Cleanup GDPR Tiptap editor

---

stubs/feature.stub

- https://canyongbs.atlassian.net/browse/ADVAPP-910
Fix path defined in stub for Feature Flags.
No
No

[ADVAPP-910]: Fix path in FeatureFlag stub

---

app-modules/ai/src/Models/AiThread.php

- https://canyongbs.atlassian.net/browse/ADVAPP-896
This is not a fix for the performance issue, just a very slight code enhancement that solves an N+1 in specific conditions where threads do not have a message.
No
No

[ADVAPP-896]: Improve processing speed for chat in the Enterprise AI Assistant

---

_ide_helper_models.php
app-modules/prospect/database/factories/ProspectStatusFactory.php
app-modules/prospect/database/migrations/2024_10_08_153706_add_is_system_protected_column_to_prospect_statuses_table.php
app-modules/prospect/database/migrations/2024_10_08_161832_data_ensure_system_default_prospect_statuses_exist.php
app-modules/prospect/database/migrations/2024_10_08_173948_create_trigger_to_apply_modification_prevention_for_system_protected_prospect_statuses.php
app-modules/prospect/database/migrations/2024_10_08_174319_data_activate_feature_flag_prospect_status_system_protection_and_auto_assignment.php
app-modules/prospect/database/seeders/ProspectStatusSeeder.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Actions/ConvertToStudent.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Actions/DisassociateStudent.php
app-modules/prospect/src/Filament/Resources/ProspectStatusResource/Pages/EditProspectStatus.php
app-modules/prospect/src/Filament/Resources/ProspectStatusResource/Pages/ListProspectStatuses.php
app-modules/prospect/src/Filament/Resources/ProspectStatusResource/Pages/ViewProspectStatus.php
app-modules/prospect/src/Models/ProspectStatus.php
app-modules/prospect/src/Policies/ProspectStatusPolicy.php
app-modules/prospect/tests/Prospect/EditProspectTest.php
app-modules/prospect/tests/Prospect/ViewProspectTest.php
app-modules/prospect/tests/ProspectStatus/EditProspectStatusTest.php
app-modules/prospect/tests/ProspectStatus/ViewProspectStatusTest.php
app/Features/ProspectStatusSystemProtectionAndAutoAssignment.php
database/migrations/2024_10_08_173120_create_function_to_prevent_modification_of_system_protected_rows.php
resources/views/components/page-header-action-lock-icon.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-827
Enforces the concept of system protected rows and places that on particular Prospect Statuses.
No
Feature Flags:
- `ProspectStatusSystemProtectionAndAutoAssignment`
Data Migrations:
- `app-modules/prospect/database/migrations/2024_10_08_174319_data_activate_feature_flag_prospect_status_system_protection_and_auto_assignment.php`
- `app-modules/prospect/database/migrations/2024_10_08_161832_data_ensure_system_default_prospect_statuses_exist.php`

[ADVAPP-827]: After a prospect is converted to a student, place them in a converted status

---

app-modules/portal/src/Settings/PortalSettings.php

- https://canyongbs.atlassian.net/browse/ADVAPP-859
Fixes typing error with `PortalSettings` `$footer_copyright_statement`.
No
No

[ADVAPP-859]: Trying to update the Portal copyright statement throws an error

---

app-modules/authorization/src/Filament/Pages/Auth/Login.php

…changelog instead of GitHub
- https://canyongbs.atlassian.net/browse/ADVAPP-925
Update changelog path for login to point to the Advising App website changelog instead of GitHub
No 
No

[ADVAPP-925]: Update changelog path for login to point to the Advising App website changelog instead of GitHub

---

app-modules/engagement/resources/views/components/filters.blade.php
app-modules/engagement/src/Filament/Pages/MessageCenter.php

- https://canyongbs.atlassian.net/browse/ADVAPP-935
> Add the ability to filter the list of Message Center engagement by constituents where you are a member of their care team
> No.
> No.

[ADVAPP-935]: Add the ability to filter the list of Message Center engagement by constituents where you are a member of their care team

---

resources/views/vendor/filament-panels/components/layout/login.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-950
> Login page fails to preserve the padding in the top header when responding to screen size changes
> No
> No

[ADVAPP-950]: Login page fails to preserve the padding in the top header when responding to screen size changes

---

resources/views/components/footer.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-947
> Update the copyright text for the footer in Advising App
> No
> No

[ADVAPP-947]: Update the copyright text for the footer in Advising App

---

.github/actions/composer-dependency-setup/action.yml
Dockerfile

- https://canyongbs.atlassian.net/browse/ADVAPP-956
Fixes a bug with dependency auto-loading in production/staging.
No
No

[ADVAPP-956]: Fix bug with dependency auto loading

---

app-modules/student-data-model/resources/views/components/header/index.blade.php
app-modules/student-data-model/resources/views/filament/resources/student-resource/sis-last-updated.blade.php
app-modules/student-data-model/resources/views/filament/resources/student-resource/sis-sync.blade.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php

- https://canyongbs.atlassian.net/browse/ADVAPP-972
> The text displayed on the student profile page related to data sync is displaying in an unexpected screen location.
> No
> No

[ADVAPP-972]: The text displayed on the student profile page related to data sync is displaying in an unexpected screen location.

---

app-modules/task/src/Notifications/TaskAssignedToUserNotification.php

- https://canyongbs.atlassian.net/browse/ADVAPP-988
Indicate student or prospect's name when that task is related to a student or prospect in the resulting notification.
Need to restart queue. 
No

[ADVAPP-988]: Indicate student or prospect's name when that task is related to a student or prospect in the resulting notification.

---

app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
app-modules/engagement/src/Filament/Actions/SendEngagementAction.php
app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords.php
app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php
app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/EditEngagement.php
app-modules/engagement/src/Models/EngagementBatch.php
app-modules/prospect/src/Models/Prospect.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentEngagementRelationManager.php
app-modules/student-data-model/src/Models/Contracts/Educatable.php
app-modules/student-data-model/src/Models/Student.php

- https://canyongbs.atlassian.net/browse/ADVAPP-854
> Prevent sending SMS messages to Prospects or Students with no Mobile number set
> No
> No

[ADVAPP-854]: Prevent sending SMS messages to Prospects or Students with no Mobile number set

---

app-modules/campaign/src/Filament/Blocks/EngagementBatchSmsBlock.php
app-modules/engagement/src/Filament/Resources/EngagementResource/Fields/EngagementSmsBodyField.php

- https://canyongbs.atlassian.net/browse/ADVAPP-991
Personally I think this `$fieldPrefix` approach needs refactoring everywhere to be removed and replaced with a solution using `statePath()` if that is required. This PR represents the minimal changes required to fix the issue.
No
No

[ADVAPP-991]: Text message body content does not appear when a text campaign action is opened using its associated edit link.

---

app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords/Actions/DraftWithAiAction.php

- https://canyongbs.atlassian.net/browse/ADVAPP-982
This originated from the student profile refactor, now the action is able to deal with either type of Livewire component that uses it.
No
No

[ADVAPP-982]: When attempting to create a draft with the AI assistant on the student profile page to create a new email or text, an error is generated

---

app-modules/form/src/Filament/Actions/RequestFormSubmission.php

- https://canyongbs.atlassian.net/browse/ADVAPP-983
The student profile refactor broke this feature as the action was still expecting a relation page instead of a relation manager.
No
No

[ADVAPP-983]: When attempting to request a form in the student profile, an error is generated

---

app-modules/prospect/resources/views/filament/pages/manage-pipeline-educatables.blade.php
app-modules/prospect/src/Filament/Resources/PipelineResource/Pages/ManageEductables.php

…not practical
- https://canyongbs.atlassian.net/browse/ADVAPP-951
> Enhance the pipeline management experience to limit kanban view when not practical.
> No.
> No.

[AIDAPP-951]: Enhance the pipeline management experience to limit Kanban view when not practical

---

app-modules/engagement/src/Actions/EngagementSmsChannelDelivery.php
app-modules/student-data-model/src/Models/Contracts/Educatable.php

- https://canyongbs.atlassian.net/browse/ADVAPP-955
Fixes issues caused by the system trying to send text messages to Educatables that do not have mobile number set. Will mark the delivery as dispatch failed.
No
No

[ADVAPP-955]: Some campaign actions are generating an exception

---

app-modules/case-management/database/migrations/2024_11_26_223109_data_fix_audit_polymorphic_types_for_service_request_rename.php
app-modules/resource-hub/database/migrations/2024_11_26_221634_data_fix_audit_polymorphic_types_for_knowledge_base_rename.php
app-modules/resource-hub/database/migrations/2024_11_26_222012_data_fix_media_polymorphic_types_for_knowledge_base_rename.php

- https://canyongbs.atlassian.net/browse/ADVAPP-941
- https://canyongbs.atlassian.net/browse/ADVAPP-973
Provides a data fix for some tables where the polymorphic type values changed.
No
Data migrations:
- `app-modules/resource-hub/database/migrations/2024_11_26_221634_data_fix_audit_polymorphic_types_for_knowledge_base_rename.php`
- `app-modules/resource-hub/database/migrations/2024_11_26_222012_data_fix_media_polymorphic_types_for_knowledge_base_rename.php`
- `app-modules/case-management/database/migrations/2024_11_26_223109_data_fix_audit_polymorphic_types_for_service_request_rename.php`

[ADVAPP-941] & [ADVAPP-973]: Fix polymorphic relationship saved values

---

app/Console/Commands/ConnectOlympus.php

- https://canyongbs.atlassian.net/browse/OLYMPUS-196
When connecting, the protocol is forced as HTTPS when sending app data back to Olympus.
No
No

[OLYMPUS-196]: Ensure all requests between Olympus and the other application are done over HTTPS

---

app-modules/engagement/src/Actions/EngagementSmsChannelDelivery.php
app-modules/engagement/src/Drivers/EngagementSmsDriver.php
app-modules/integration-twilio/database/migrations/2024_11_28_151611_add_is_demo_auto_reply_mode_enabled_setting_to_twilio_settings.php
app-modules/integration-twilio/database/migrations/2024_11_28_151640_data_activate_twilio_demo_auto_reply_mode_feature.php
app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
app/Features/TwilioDemoAutoReplyModeFeature.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1032
If the setting is enabled, a response is created from the SMS driver using the same action that is used by the Twilio web hook controller.
No
`TwilioDemoAutoReplyModeFeature`

[ADVAPP-1032]: Simulate an inbound text message response when demo mode is enabled.

---

app-modules/alert/graphql/alert-status.graphql
app-modules/alert/graphql/alert.graphql
app-modules/alert/src/Providers/AlertServiceProvider.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1047
Fixes an issue in API docs generation caused by changing Alert Status to a Model.
No
No

[ADVAPP-1047]: API documentation fails to generate after introducing flexible statuses on alerts

---

composer.lock

- N/A
Updates the package `canyongbs/filament-tiptap-editor` to contain needed updates for the new clear-formatting tool.
No
No

[Bugfix]: Update canyongbs/filament-tiptap-editor

---

app-modules/engagement/resources/views/components/message-center-inbox.blade.php
app-modules/engagement/src/Filament/Pages/MessageCenter.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1011
Introduces count of currently active filters. Count method needs to be updated when new filters are added.
Adds loading indicator to the filter button to improve percieved performance of the page. Also needs to be kept up to date when new filters are added.
No
No

[ADVAPP-1011]: Add count to filter icon for message center

---

app-modules/audit/src/Filament/Resources/AuditResource/Pages/ListAudits.php
app-modules/audit/src/Filament/Resources/AuditResource/Pages/ViewAudit.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1051
> Add event date to user auditing list view and detail view
> No
> No

[ADVAPP-1051]: Add event date to user auditing list view and detail view

---

app-modules/audit/src/Filament/Resources/AuditResource/Pages/ListAudits.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1052
> Add start date and end date optional filters for the event date to the user auditing list view
> No
> No

[ADVAPP-1052]: Add start date and end date optional filters for the event date to the user auditing list view

---

app-modules/authorization/src/Http/Controllers/SocialiteController.php
app-modules/resource-hub/database/migrations/2024_12_09_174712_data_change_knowledge_management_to_resource_hub_in_license_group_in_settings_table.php
app/Exceptions/InvalidUserAvatarMimeType.php
database/migrations/2024_12_11_221606_data_remove_all_media_user_avatars_that_saved_as_json.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1061
- Fixes an issue with license addon data migration
- Fixes a bug with the Azure Socialite login avatar retrieval
- Data fixes removing all User Avatars that saved as JSON due to the previous bug
- I am aware that I am breaking our rule to not use Model classes like Media. But I would like to propose an exception since this will be short lived and is the fastest way to ensure the media Model is deleted and the media itself is purged from storage.
No
Data Migration: `database/migrations/2024_12_11_221606_data_remove_all_media_user_avatars_that_saved_as_json.php`

[ADVAPP-1061]: Users who do not have a profile image set via SSO present a broken image as their avatar.

---

app-modules/segment/src/Filament/Resources/SegmentResource/Pages/ListSegments.php
app-modules/segment/src/Policies/SegmentPolicy.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1041
> Prevent the removal of a population segment that is associated with an active campaign.
> No.
> No.

[ADVAPP-1041]: Prevent the removal of a population segment that is associated with an active campaign

---

app-modules/task/database/migrations/2024_12_18_104302_delete_task_individual_update_permissions.php
app-modules/task/src/Observers/TaskObserver.php
app-modules/task/src/Policies/TaskPolicy.php
app-modules/task/tests/EditTaskTest.php
app-modules/task/tests/TaskAssignmentTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1064
> Refactor Task access to not use individual permissions to manage access
> No
Data Migrations:
-`app-modules/task/database/migrations/2024_12_18_104302_delete_task_individual_update_permissions.php`

[ADVAPP-1064]: Refactor Task access to not use individual permissions to manage access

---

app-modules/authorization/database/migrations/2024_12_30_142708_add_matching_property_to_azure_sso_settings.php
app-modules/authorization/database/migrations/2024_12_30_144224_data_activate_azure_matching_property_feature.php
app-modules/authorization/src/Enums/AzureMatchingProperty.php
app-modules/authorization/src/Enums/SocialiteProvider.php
app-modules/authorization/src/Exceptions/InvalidAzureMatchingProperty.php
app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php
app-modules/authorization/src/Http/Controllers/SocialiteController.php
app/Features/AzureMatchingPropertyFeature.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1094
Allows admins to define which Azure User property to match the User email to for Azure SSO login.
No
Feature Flag:
- AzureMatchingPropertyFeature

[ADVAPP-1094]: Introduce additional configuration in the SSO settings for Microsoft Azure AD

---

app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/Concerns/HasStudentHeader.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1087
Replace HS Grad Year in the header for a student with the Student ID
No
No

[ADVAPP-1087]: Replace HS Grad Year in the header for a student with the Student ID

---

app-modules/resource-hub/database/migrations/2024_12_30_153854_data_rename_knowledge_base_article_permission_group_to_resource_hub_article.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1088
Renames the permission group to match the permissions.
No
No

[ADVAPP-1088]: Rename permission group in permissions for Resource Hub

---

app-modules/authorization/src/Exceptions/NonUuidPermissionIdFound.php
app-modules/authorization/src/Filament/Forms/Components/PermissionsMatrix.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1106
Prevents the User from seeing errors if non-uuid permissions are attempted to be synced. Syncs those that are UUIDs and reports a custom exception.
No
No

[ADVAPP-1106]: Prevent an error from being thrown for a User if a non-UUID value is passed into the permission sync

---

app-modules/authorization/src/Filament/Resources/PermissionResource.php
app-modules/authorization/src/Filament/Resources/RoleResource.php
app-modules/division/src/Filament/Resources/DivisionResource.php
app-modules/team/src/Filament/Resources/TeamResource.php
app/Filament/Resources/SystemUserResource.php
app/Filament/Resources/UserResource.php
app/Providers/Filament/AdminPanelProvider.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1107
> Update the label used for the navigation group People Management to User Management.
> No.
> No.

[ADVAPP-1107]: Update the label used for the navigation group People Management to User Management

---

app-modules/authorization/src/Filament/Forms/Components/PermissionsMatrix.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1129
> Merge values do not show up when sending a message from the holistic student profile.
> No
> No

[ADVAPP-1129]: Merge values do not show up when sending a message from the holistic student profile

---

database/migrations/2025_01_14_165537_data_fix_not_normalized_permissions.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1123
Removes unused permissions and ensures permissions belong to the correct group.
No
This data migration can technically be removed since the correct permissions are already being seeded for new tenants.

[ADVAPP-1123]: Permission normalization errors

---

app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1128
> The filter for In Progress displays as a typo in Tasks.
> No.
> No.

[ADVAPP-1128]: The filter for In Progress displays as a typo in Tasks

---

app-modules/campaign/src/Filament/Blocks/CareTeamBlock.php
app-modules/campaign/src/Filament/Blocks/EventBlock.php
app-modules/campaign/src/Filament/Blocks/InteractionBlock.php
app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php
app-modules/campaign/src/Filament/Blocks/SubscriptionBlock.php
app-modules/campaign/src/Filament/Blocks/TaskBlock.php
composer.lock
package-lock.json
resources/views/filament/forms/components/campaigns/actions/task.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1131
> When creating a campaign task, due dates are being automatically added even if not populated when configuring the journey step
> No
> No

[ADVAPP-1131]: When creating a campaign task due dates are being automatically added even if not populated when configuring the journey step

---

app-modules/student-data-model/src/Filament/Imports/StudentImporter.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/Actions/EditStudentAction.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1145
> Correct typo in spelling for new and edit forms for manually created students.
> No.
> No.

[ADVAPP-1145]: Correct typo in spelling for new and edit forms for manually created students

---

app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1159
> Fixing the  Error thrown by interactions without an end date set.
> No.
> No.

[ADVAPP-1159]: Error thrown by interactions without an end date set

---

app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php
app/Models/Tenant.php
app/Multitenancy/Tasks/SwitchMailTask.php
tests/TestCase.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1160
Fixes issues with mail sending by clearing out all currently found bindings where mail config could be stored. Also overrides the Tenant `makeCurrent` to make sure that it is always refreshed so that old config values are to persisted if changed.
No
No

[ADVAPP-1160]: Sometimes emails fail to send and also sometimes send while demo mode is turned on

---

app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/CreateInteraction.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1169
Fixes an issue caused by Carbon updates by ensuring that `$duration` is cast to an `int` before being used by Carbon.
No
No

[ADVAPP-1169]: Interaction duration calculation throws errors

---

config/health.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1171
Turns off the Spatie Health failure email as we currently don't have it set to send to anyone real anyways. And it throws errors due to the way OutboundDeliverables are made.
No
No

[ADVAPP-1171]: Spatie Health package throws errors when trying to email about failures

---

app/Console/Kernel.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1176
Sets up Model pruning for `HealthCheckResultHistoryItem`.
No
No

[ADVAPP-1176]: Setup pruning for HealthCheckResultHistoryItem

---

app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanUploadFiles.php
app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1175
> Increase the files size for AI file upload limits per file for threads and custom assistants from 256kb to 20mb
> No.
> No.

[ADVAPP-1175]: Increase the files size for AI file upload limits per file for threads and custom assistants from 256kb to 20MB

---

app-modules/integration-twilio/tests/Feature/Jobs/CheckSmsOutboundDeliverableStatusTest.php
app-modules/integration-twilio/tests/Fixtures/ClientMock.php
app-modules/notification/database/factories/OutboundDeliverableFactory.php
app-modules/notification/src/Notifications/Channels/MailChannel.php
app-modules/notification/src/Notifications/Channels/SmsChannel.php
app-modules/notification/tests/Feature/LicenseSettingsEmailQuotaTrackingTest.php
app-modules/notification/tests/Feature/LicenseSettingsSmsQuotaTrackingTest.php
app-modules/notification/tests/Feature/NotificationFromNameTest.php
app-modules/notification/tests/Feature/NotificationSendingTest.php
app-modules/notification/tests/Fixtures/TestEmailNotification.php
app-modules/notification/tests/Fixtures/TestEmailSettingFromNameNotification.php
app-modules/notification/tests/Fixtures/TestSmsNotification.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1083
Changes the super admin check to just check if a user exists, and if so do not count the notification towards the quota.
Remove duplicate test from `NotificationSendingTest`.
No
No

[ADVAPP-1083]: Allow per notification quota manipulation

---

Dockerfile

- https://canyongbs.atlassian.net/browse/ADVAPP-1165
> Update Roadrunner to 2024.3.2.
> No.
> No.

[ADVAPP-1165]: Update Roadrunner to 2024.3.2

---

app-modules/division/database/migrations/2025_02_19_220017_remove_header_footer_columns_from_divisions_table.php
app-modules/division/database/seeders/DivisionSeeder.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/CreateDivision.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/EditDivision.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/ViewDivision.php
app-modules/division/src/Models/Division.php

- https://canyongbs.atlassian.net/browse/ADVAPP-
Remove header and footer fields from Division pages, related files, and database.
No
No

[ADVAPP-1207] Remove obsolete header and footer configuration options for Division configuration

---

app-modules/integration-twilio/routes/web.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1085
Disables the `TrimStrings` middleware from Twilio inbound webhook route. As described in their docs.
No
No

[ADVAPP-1085]: Remove TrimStrings middleware from Twilio inbound webhook route

---

app-modules/integration-twilio/src/Http/Middleware/EnsureTwilioRequestIsValid.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1085
Updates the Twilio signature validation to ensure that the validated URL is `https`
No
No

[ADVAPP-1085]: Update Twilio request validation to use HTTPS URL

---

app-modules/campaign/tests/Tenant/Actions/SubscriptionCampaignTest.php
app/Jobs/MigrateTenantDatabase.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1242
Fixes an issue overall with tests where subsequent runs would have issues by making sure we refresh the database when we migrate a new Tenant.
Also fixes the flaky test in `SubscriptionCampaignTest`
No
No

[ADVAPP-1242]: Resolve flaky test in SubscriptionCampaignTest

---

app-modules/integration-open-ai/tests/Tenant/Feature/Services/OpenAiGptTestServiceTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1204
Resolves a flaky test by ensuring that the temperature is set as a float so that the request matches properly.
No
No

[ADVAPP-1204]: Resolve flaky test in OpenAiGptTestServiceTest

---

app-modules/authorization/tests/Tenant/Feature/Filament/Resources/User/EditUserTest.php
app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php
app/Rules/ExcludeSuperAdmin.php
tests/Tenant/Feature/Filament/UserResource/RelationManagers/RolesRelationManagerTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1210
> Add validation rule to exclude super admin role assignment and update roles relation manager.
> No.
> No.

[ADVAPP-1210]: Add validation to User Role attach Action to prevent a non-admin from attaching Super Admin as a Role

---

app-modules/alert/src/Filament/Resources/AlertResource/Pages/ListAlerts.php
app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableAlerts.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1219
Alert creation for students or prospects fails when status is not manually set
No
No

[ADVAPP-1219]: Alert creation for students or prospects fails when status is not manually set

---

app-modules/authorization/src/Http/Controllers/SocialiteController.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1124
> Exceptions are thrown when login Azure profile image cannot be found.
> No.
> No.

[ADVAPP-1124]: Exceptions are thrown when login Azure profile image cannot be found

---

app-modules/alert/src/Models/Alert.php
app-modules/campaign/tests/Tenant/Actions/ProactiveAlertsCampaignTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1220
> Fixed: When attempting to add a proactive alert campaign journey step, an error is generated.
> No.
> No.

[ADVAPP-1220]: When attempting to add a proactive alert campaign journey step, an error is generated

---

app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1259
> Remove unnecessary information about the delivery channel from the display of email messages sent to students and prospects
> No
> No

[ADVAPP-1259]: Remove unnecessary information about the delivery channel from the display of email messages sent to students or prospects

---

app-modules/integration-twilio/routes/web.php
app-modules/integration-twilio/src/Http/Middleware/LogTwilioRequest.php
app-modules/integration-twilio/tests/Tenant/Feature/Http/Controllers/TwilioInboundWebhookControllerTest.php
app-modules/integration-twilio/tests/Tenant/Feature/Http/Middleware/LogTwilioRequestTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1248
Changes the logging of Twilio messages to happen before the Controller in middleware so that it is always logged as long as it is valid.
No
No

[ADVAPP-1248]: Maintain a complete history of incoming requests for SMS messages from the provider

---

app-modules/engagement/src/Filament/Actions/MessageCenterSendEngagementAction.php
app-modules/engagement/src/Filament/Actions/RelationManagerSendEngagementAction.php
app/Filament/Pages/EditProfile.php
app/Models/User.php
docker-compose.dev.yml

- https://canyongbs.atlassian.net/browse/ADVAPP-1284
Allows the signature to be included in the email content, and copies images from the signature collection on the user record to the engagement record for longevity.
No
No

[ADVAPP-1284]: Enable the usage of stored customizable signatures in sending of Engagements

---

app-modules/in-app-communication/database/migrations/2025_03_20_125908_data_remove_realtime_chat_api_permission.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1275
Removes unused API permission and duplicate group.
No
No

[ADVAPP-1275]: Normalize permissions related to realtime chat for the role matrix

---

composer.json
composer.lock

- https://canyongbs.atlassian.net/browse/ADVAPP-1325
> Update Larave Octane to version 2.8.3
> No
> No

[ADVAPP-1325]: Update Laravel Octane to version 2.8.3

---

composer.lock

- https://canyongbs.atlassian.net/browse/OLYMPUS-441
Updates package
No
No

[OLYMPUS-441]: Tiptap merge tags type ahead is currently limited to only 5 items and typeahead search does not seem to be working

---

app-modules/report/src/Filament/Widgets/StudentDeliverableTable.php
app-modules/report/src/Filament/Widgets/StudentEmailOptInOptOutPieChart.php
app-modules/report/src/Filament/Widgets/StudentSmsOptInOptOutPieChart.php
app-modules/report/tests/Tenant/Unit/StudentDeliverabilityReport/StudentDeliverabilityReportTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1333
> The pie chart and tabular data in the deliverability report is not correctly identifying email and SMS eligibility.
> No.
> No.

[ADVAPP-1333]: The pie chart and tabular data in the deliverability report is not correctly identifying email and SMS eligibility

---

app-modules/authorization/src/Filament/Pages/Auth/Login.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1223
Call parent `mount()` when overriding a class to ensure original logic is retained.
No
No

[ADVAPP-1223]: When a logged in user visits the login page, it does not automatically redirect them to the appropriate target

---

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1385
> Update the label used in the create and edit prospect forms to state High School Graduation Year.
> No.
> No.

[ADVAPP-1385]: Update the label used in the create and edit prospect forms to state High School Graduation Year

---

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/Concerns/HasProspectHeader.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php
app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectTasks.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1375
> When clicking hyperlinked tasks or alerts boxes in prospect profile, the page layout differs from the student profile
> No
> No

[ADVAPP-1375]: When clicking hyperlinked tasks or alerts boxes in prospect profile, the page layout differs from the student profile

---

app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableTasks.php
app-modules/task/src/Filament/RelationManagers/BaseTaskRelationManager.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1354
> Change default sort on interactions and tasks to be most recent first
> No
> No

[ADVAPP-1354]: Change default sort on interactions and tasks to be most recent first

---

app-modules/ai/database/migrations/2025_04_16_090001_data_update_default_personal_assistant_name_to_institutional_advisor.php
app-modules/ai/resources/views/components/assistant.blade.php
app-modules/ai/src/Actions/CompletePrompt.php
app-modules/ai/src/Actions/CreateThread.php
app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php
app-modules/ai/tests/Tenant/Feature/Actions/CompletePromptTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1357
> Improve the remaining "Assistant" terminology in Artificial Intelligence to match "Advisor" labeling
> No
> No

[ADVAPP-1357]: Improve the remaining "Assistant" terminology in Artificial Intelligence to match "Advisor" labeling

---

app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1403
> When attempting to view a text message scheduled to Send Later, an error is thrown.
> No.
> No.

[ADVAPP-1403]: When attempting to view a text message scheduled to Send Later, an error is thrown

---

app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php
app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableCareTeam.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1389
Exclude users who are already on an educatable's care team from being selected
No
No

[ADVAPP-1389]: When adding a new care team member, users already in the care team are still listed and selectable

---

app-modules/case-management/src/Models/CaseModel.php
composer.json
composer.lock

- https://canyongbs.atlassian.net/browse/ADVAPP-1435
Upgrades Power Joins to remove deprecation warnings. Removes trait from model since it is no longer required.
No
No

[ADVAPP-1435]: Upgrade Eloquent Power Joins package to fix PHP warnings being reported in production

---

app-modules/engagement/src/Jobs/ProcessSesS3InboundEmail.php
app-modules/engagement/src/Notifications/EngagementNotification.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1412
Ensure jobs with a `failed` method send the exception to Sentry, per https://docs.sentry.io/platforms/php/guides/laravel/usage/#queue-jobs
No
No

[ADVAPP-1412]: Some jobs that fail to suceed are not being reported to centralized error reporting system

---

app-modules/campaign/src/Filament/Blocks/TagsBlock.php
app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
app-modules/engagement/src/Models/Engagement.php
app/Filament/Tables/Filters/QueryBuilder/Constraints/ExistingValuesSelectConstraint.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1467
- https://canyongbs.atlassian.net/browse/ADVAPP-1468
- https://canyongbs.atlassian.net/browse/ADVAPP-1469
Resolves 3 different bugs in the system related to campaigns, segments, and Engagements where the User has been deleted.
No
No

[ADVAPP-1467] & [ADVAPP-1468] & [ADVAPP-1469]

---

app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1448
> Show a modal before creating a campaign, which has button to save campaign as draft or enabled.
> No
> No

[ADVAPP-1448]: Improve the experience when creating a new campaign by providing a confirmation modal

---

app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php
app-modules/campaign/src/Policies/CampaignActionPolicy.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1432
> Rename 'Campaign Actions' to "Journey Steps" in frontend.
> No
> No

[ADVAPP-1432]: Align terminology by consistently using "Journey Steps" when managing Campaigns

---

app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ListRoles.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1461
> Improve the language used on the duplicate role modal overlay
> No
> No

[ADVAPP-1461]: Improve the language used on the duplicate role modal overlay

---

app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1465
Updates the labels in the AI Advisor form and removes the "Test" option for application.
No
No

[ADVAPP-1465]: Update the labeling of feature capabilities to be consistent for custom advisors

---

app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php
app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/EditCampaign.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1475
> Error thrown in campaigns caused by change of User / Team relationship
> No
> No

[ADVAPP-1475]: Error thrown in campaigns caused by change of User / Team relationship

---

composer.lock

- https://canyongbs.atlassian.net/browse/ADVAPP-1476
Update `league/commonmark` to [v2.7.0](https://github.com/thephpleague/commonmark/releases/tag/2.7.0)
No
No

[ADVAPP-1476]: Resolve the security issue tracked under CVE-2025-46734

---

app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1485
Relocate gender after the separator and before ethnicity
No
No

[ADVAPP-1485]: Relocate gender after the separator and before ethnicity

---

app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php
resources/views/infolists/components/engagement-body.blade.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1502
> Some users experience an issue when viewing some headings on an engagement (email) in-product when the dark theme is enabled
> No
> No

[ADVAPP-1502]: Some users experience an issue when viewing some headings on an engagement (email) in-product when the dark theme is enabled

---

app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1537
Fixes errors thrown when a Student does not have a primary phone or email sent.
No
No

[ADVAPP-1537]: Not having a primary phone or email results in errors thrown on Student records

---

app-modules/authorization/src/Http/Controllers/SocialiteController.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1487
> An error is thrown to Sentry if an Azure SSO login does not have a profile photo.
> No.
> No.

[ADVAPP-1487]: AAn error is thrown to Sentry if an Azure SSO login does not have a profile photo

---

app-modules/engagement/tests/Tenant/Filament/Actions/BulkEngagementActionTest.php
app-modules/engagement/tests/Tenant/Filament/Actions/RelationManagerSendEngagementActionTest.php
app-modules/engagement/tests/Tenant/Filament/Actions/SendEngagementActionTest.php
database/factories/UserFactory.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1541
Adds tests for the fix that went out to fix Engagement creation.
No
No

[ADVAPP-1541]: Single or bulk Engagement body saves as an empty array Tests

---

app-modules/campaign/src/Jobs/ExecuteCampaignAction.php
app-modules/engagement/tests/Tenant/Actions/FindEngagementResponseSenderTest.php
app-modules/integration-twilio/tests/Tenant/Feature/Http/Controllers/TwilioInboundWebhookControllerTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1559
Add tests for the EngagementResponse creation from inbound Twilio webhooks.
Attempt to fix reported User issues by clearing logged in session from Campaign Execution jobs.
No
No

[ADVAPP-1559]: Customer reporting that they don't see inbound text messages

---

app-modules/ai/database/migrations/2025_05_30_132953_add_research_assisstant_reasoning_effort_settings.php
app-modules/ai/src/Enums/AiResearchReasoningEffort.php
app-modules/ai/src/Filament/Pages/ManageAiResearchAssistantSettings.php
app-modules/ai/src/Settings/AiResearchAssistantSettings.php
app-modules/research/src/Jobs/Research.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1535
> Introduce reasoning effort as a configuration parameter for global administrators for the research advisor
> No
> No

[ADVAPP-1535]: Introduce reasoning effort as a configuration parameter for global administrators for the research advisor

---

app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
app-modules/timeline/src/Timelines/EngagementTimeline.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1566
Prevents issues with an SMS Engagement attempting to render subject even when it is null.
No
No

[ADVAPP-1566]: Certain Engagement records are throwing errors for Product Student records

---

app-modules/prospect/src/Filament/Widgets/ProspectsActionCenterWidget.php
app-modules/student-data-model/src/Filament/Widgets/StudentsActionCenterWidget.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1554
> Display pagination information x of y on the bottom left of the Action Center table.
> No.
> No.

[ADVAPP-1554]: Display pagination information x of y on the bottom left of the Action Center table

---

.github/workflows/ci.yml

- N/A
Fixes a bug in our GitHub CI process by making sure we checkout the branch properly and upgrades to the most recent version of the auto commit action.
No
No

[CHORE]: Upgrade stefanzweifel/git-auto-commit-action and fix checkout to not detach

---

app-modules/prospect/src/Filament/Resources/ProspectResource/Schemas/ProspectProfileInfolist.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1572
Display the primary email and phone number in a second location on the prospect profile
No
No

[ADVAPP-1572]: Display the primary email and phone number in a second location on the prospect profile

---

app-modules/authorization/src/Http/Controllers/SocialiteController.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1591
Stops truncating the full exception so we can properly match and ignore the error.
No
No

[ADVAPP-1591]: Users not having profile images causes Azure to throw error to Sentry unnecessarily

---

app-modules/integration-open-ai/src/Services/BaseOpenAiResponsesService.php
app-modules/integration-open-ai/src/Services/OpenAiResponsesGptTestService.php
app-modules/integration-open-ai/tests/Tenant/Feature/Services/OpenAiResponsesGptTestServiceTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1593
Makes an API request to check the validity of a response before using it for the next request.
Fixes an issue where user messages are not saved correctly when using the responses API.
No
No

[ADVAPP-1593]: When sending a message to the Response API ensure the Response object exists

---

Dockerfile

- N/A
Update Roadrunner binary to `2025.1.2`.
No
No

Update roadrunner to 2025.1.2

---

app/Console/Kernel.php

- N/A
Fix bug where the `UnmatchedInboundCommunicationsJob` is dispatched without being in the correct Tenant context.
No
No

[Bugfix]: Ensure the UnmatchedInboundCommunicationsJob is dispatched as a Tenant

---

composer.json
composer.lock

- https://canyongbs.atlassian.net/browse/ADVAPP-1617
- https://canyongbs.atlassian.net/browse/ADVAPP-1618
Update `ysfkaya/filament-phone-input` in `composer.json` and our lock file to go to the updated version without a reference to a package with CVE within its JavaScript developer dependencies.
We were not vulnerable to this vulnerability, as it was not installed on our system; it was only referenced in this downstream dependency as a JavaScript developer dependency. Updating to silence scanners.
No
No

[ADVAPP-1617]: Resolve the security issue tracked under CVE-2025-6545 & [ADVAPP-1618]: Resolve the security issue tracked under CVE-2025-6547

---

app/Overrides/Filament/Actions/Exports/Jobs/CreateXlsxFileOverride.php
app/Overrides/Filament/Actions/Exports/Jobs/ExportCompletionOverride.php
app/Overrides/Filament/Actions/Exports/Jobs/ExportCsvOverride.php
app/Overrides/Filament/Actions/Exports/Jobs/PrepareCsvExportOverride.php
app/Overrides/Filament/Actions/Imports/Jobs/ImportCsvOverride.php

- N/A
Update all import / export jobs to have a 10 minute timeout to prevent issues with processing large datasets.
No
No

[Bugfix]: Give all import and export jobs a 10 minute timeout

---

_ide_helper_models.php
app-modules/integration-open-ai/src/Console/Commands/UploadAssistantFilesToVectorStores.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1649
Fix issue where exceptions are thrown by the `UploadAssistantFilesToVectorStores` command when services do not have credentials.
No
No

[ADVAPP-1649]: Services that have no credentials cause the assistant vector store check scheduled command to fail

---

app/Overrides/LaravelSqsExtended/SqsDiskJob.php
app/Overrides/LaravelSqsExtended/SqsDiskQueue.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1664
Fix issue with large payload queued job handling. Makes sure that the correct Tenant folder is accessed to retrieve the payload if any. And deletes any jobs that are unable to be recovered.
No
No

[ADVAPP-1664]: Implement performance and infrastructure improvements for audit record consistency

---

app-modules/report/src/Filament/Pages/ResearchAdvisorReport.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1679
> Add a Research Advisor report as coming soon under Artificial Intelligence following the Utilization report
> No
> No

[ADVAPP-1679]: Add a Research Advisor report as coming soon under Artificial Intelligence following the Utilization report

---

app-modules/report/src/Filament/Pages/CustomAdvisorReport.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1678
> Add a Custom Advisors report as coming soon under Artificial Intelligence following the Utilization report
> No
> No

[ADVAPP-1678]: Add a Custom Advisors report as coming soon under Artificial Intelligence following the Utilization report

---

app/Console/Commands/CreateTenant.php
app/DataTransferObjects/LicenseManagement/LicenseSubscriptionData.php
app/Filament/Pages/ManageLicenseSettings.php
app/Http/Requests/Tenants/CreateTenantRequest.php
app/Http/Requests/Tenants/SyncTenantRequest.php
tests/TestCase.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1686
Remove the purchase order fields from Subscriptions. No need for any sort of migration as the data is loading into a setting via DTO. So it will just not be used and removed the next time the Subscription is updated.
No
No

[ADVAPP-1686]: Remove legacy purchase order fields in the data model and interface under subscription information for global administrators

---

app-modules/ai/src/Filament/Resources/PromptResource.php
app-modules/ai/src/Filament/Resources/QnaAdvisorResource.php

…r is not positioned correctly relative to the Prompt Library
- https://canyongbs.atlassian.net/browse/ADVAPP-1695
> Some users have reported an issue where the QnA Advisor is not positioned correctly relative to the Prompt Library.
> No.
> No.

[ADVAPP-1695]: Some users have reported an issue where the QnA Advisor is not positioned correctly relative to the Prompt Library

---

app/Http/Controllers/Tenants/CreateTenantController.php
app/Http/Requests/Tenants/CreateTenantRequest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1712
Update the Olympus API Tenant creation process to no longer require the name of the Tenant be passed and now instead use the domain provided as the name of the Tenant and the key for the folder names in storage.
No
No

[ADVAPP-1712]: Update Olympus API tenant creation to work without a name passed

---

app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1684
Some users are experiencing an issue when using the my teams tasks filter in the task list
No
No

[ADVAPP-1684]: Some users are experiencing an issue when using the my teams tasks filter in the task list

---

app-modules/case-management/src/Filament/Resources/CaseResource.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1675
Ensure that the cases resource does not register in the main navigation. This was forgotten about to be cleaned up in [ADVAPP-1675].
No
No
[ADVAPP-1675]: https://canyongbs.atlassian.net/browse/ADVAPP-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ADVAPP-1675]: Hide cases resource from the main navigation

---

app-modules/authorization/database/migrations/2025_07_29_134904_seed_permissions_add_partner_admin_role.php
app-modules/authorization/src/Enums/LicenseType.php
app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ListRoles.php
app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php
app/Models/Authenticatable.php
app/Providers/AuthServiceProvider.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1710
Adds a new Partner Admin role and gives it the ability to pass all permission gates but still make sure it is not allowed to do any global admin things.
Also make it so only super admins and other partners admins can see the partner admin role.
No
No

[ADVAPP-1710]: Set up new Partner Admin role

---

app-modules/alert/src/Listeners/NotifySubscribersOfAlertCreated.php
app-modules/alert/tests/Tenant/AlertCreateTest.php
app-modules/notification/src/Models/Concerns/HasSubscriptions.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1728
- Add a scope to only pull back Subscriptions if they have a user.
- No
- No

[ADVAPP-1728]: Bug Fix: Attempts to Send Alert to a Deleted User

---

app-modules/project/composer.json
app-modules/project/database/migrations/2025_08_01_095717_seed_permissions_for_projects.php
app-modules/project/database/migrations/2025_08_01_100758_data_activate_project_coming_soon_feature.php
app-modules/project/src/Filament/Pages/Projects.php
app-modules/project/src/ProjectPlugin.php
app-modules/project/src/Providers/ProjectServiceProvider.php
app/Features/ProjectComingSoonFeature.php
composer.json
composer.lock

- https://canyongbs.atlassian.net/browse/ADVAPP-1753
> Introduce the navigation item for Projects under Project Mangement
> No
Feature Flag: `ProjectComingSoonFeature`
Tmp Data Migration: `app-modules/project/database/migrations/2025_08_01_100758_data_activate_project_coming_soon_feature.php`

[ADVAPP-1753]: Introduce the navigation item for Projects under Project Mangement

---

app-modules/campaign/src/Jobs/SubscriptionCampaignActionJob.php
app-modules/notification/src/Actions/SubscriptionCreate.php
app-modules/notification/src/Filament/Actions/SubscribeBulkAction.php
app-modules/workflow/src/Jobs/SubscriptionWorkflowActionJob.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1775
Ensure that users and educatables are not deleted before creating a subscription between them.
No
No

[ADVAPP-1775]: Ensure that Subscriptions take into account soft deleted Users and/or the Educatables to prevent unnecessary exceptions

---

app-modules/case-management/src/Filament/Resources/CaseTypeResource/Pages/ManageCaseTypeEmailTemplate.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1881
> Solve the issue where contact name merge tag was not visible in case type email templates
> No
> No

[ADVAPP-1881]: Some users have reported that the merge value for contact name is missing in the case type templates

---

app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ListCases.php
app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/CasesRelationManager.php
app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/CasesRelationManager.php
app/Filament/Widgets/MyCases.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1909
Do not include priorities in the priority filter options lists without a type.
No
No

[ADVAPP-1909]: Some users are reporting that cases fail to load in holistic student profile

---

app-modules/ai/resources/js/chat.js
app-modules/ai/resources/views/components/assistant.blade.php
app-modules/ai/routes/web.php
app-modules/ai/src/Http/Controllers/Advisors/DownloadImageController.php
app-modules/ai/src/Http/Controllers/Advisors/ShowThreadController.php
app-modules/ai/src/Http/Controllers/DownloadImageController.php
app-modules/ai/src/Jobs/Advisors/SendAdvisorMessage.php
app-modules/ai/tests/Tenant/Feature/Http/Controllers/Advisors/ShowThreadControllerTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1875
Adds download buttons to generated images, if they have a `data-id` attribute when generated.
Moves markdown conversion and HTML sanitisation from backend to frontend then a thread is loaded, so the same functions can be used for existing messages and newly-received messages.
No
No

[ADVAPP-1875]: Improve image rendering by allowing a user to download an image

---

app-modules/engagement/src/Filament/Pages/Inbox.php
app-modules/engagement/src/Filament/Pages/SentItems.php
app-modules/engagement/tests/Tenant/Filament/Pages/InboxTest.php

- https://canyongbs.atlassian.net/browse/ADVAPP-1959
Add relations column to unified inbox to display if the sender/recipient is a student or prospect
No
No

[ADVAPP-1959]: Improve the unified inbox by adding an status as to whether the message is from a prospect or a student

---

app-modules/report/src/Filament/Widgets/QnaAdvisorReportStats.php

- https://canyongbs.atlassian.net/browse/ADVAPP-2000
Fix name of stat card in QnA Advisor Report.
No
No

[ADVAPP-2000]: Some users have reported that one of the summary cards in QnA Advisor report is incorrectly labeled
